# Generated by Django 5.2.5 on 2025-09-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commande_numero_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('PREP', 'En préparation'), ('ATT', 'En attente'), ('CLOT', 'Clôturée')], default='PREP', max_length=4),
        ),
    ]
