# Generated by Django 5.2.5

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_facture_factureproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte'), ('virement', 'Virement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.facture')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]

