# Generated by Django 5.2.5 on 2025-12-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_facture_date_annulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pourcentage_marge',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='rotation_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_marge',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=19.25, max_digits=5),
        ),
    ]
