# Generated by Django 5.2.5 on 2025-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_cloturecaisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte'), ('virement', 'Virement'), ('om', 'Orange Money'), ('momo', 'Mobile Money'), ('en_compte', 'En compte')], max_length=20),
        ),
    ]
