# Generated by Django 5.2.5 on 2025-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pmp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix Moyen Pondéré', max_digits=10),
        ),
    ]
