# Generated by Django 5.2.5 on 2025-12-17 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_free_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
