# Generated by Django 5.2.5 on 2025-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_relationtransformation_historiquetransformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Ma Société', max_length=255)),
                ('company_address', models.TextField(default="Adresse de l'entreprise\nTéléphone: 00 00 00 00 00")),
                ('footer_text', models.TextField(blank=True, default='Merci de votre confiance.')),
                ('header_layout', models.CharField(choices=[('split', 'Séparé (Logo Gauche / Info Droite)'), ('left', 'Tout à Gauche'), ('center', 'Tout Centré'), ('right', 'Tout à Droite')], default='split', max_length=20)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
