# Generated by Django 5.2.5 on 2025-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='part_assurance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Part prise en charge par l'assurance", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caisse',
            name='part_patient',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part payée par le patient (tiers payant)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='taux_couverture',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de couverture assurance en % (0-100) pour tiers payant', max_digits=5),
        ),
    ]
