# Generated by Django 5.2.5 on 2025-12-17 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_caisse_part_assurance_caisse_part_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayantdroit',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
