# Generated by Django 5.2.5 on 2025-12-19 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_ayantdroit_date_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, help_text='Nom du client (pour clients de passage)', max_length=100)),
                ('client_phone', models.CharField(blank=True, help_text='Téléphone du client', max_length=20)),
                ('quantite', models.IntegerField(help_text='Quantité promise au client')),
                ('status', models.CharField(choices=[('ATT', 'En attente'), ('DEL', 'Délivré'), ('ANN', 'Annulé')], default='ATT', max_length=4)),
                ('date_promis', models.DateTimeField(auto_now_add=True, help_text='Date de la promesse')),
                ('date_livraison', models.DateTimeField(blank=True, help_text='Date de livraison effective', null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promis', to='api.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promis', to='api.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promis', to='api.produit')),
            ],
            options={
                'verbose_name': 'Promis',
                'verbose_name_plural': 'Promis',
                'ordering': ['-date_promis'],
            },
        ),
    ]
