# Generated by Django 5.2.5 on 2025-12-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_promis'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factureproduit',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique choisi manuellement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stocklot'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de vente lors de la réception', max_digits=10),
        ),
    ]
