# Generated by Django 5.2.5 on 2025-12-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_stocklot_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='use_lot_management',
            field=models.BooleanField(default=True, help_text='Activer la gestion par lots FIFO pour ce produit (recommandé pour traçabilité)'),
        ),
    ]
