# Generated by Django 5.2.5 on 2025-12-22 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_lotsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementcaisse',
            options={'ordering': ['-date'], 'verbose_name': 'Mouvement de Caisse', 'verbose_name_plural': 'Mouvements de Caisse'},
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='motif',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='caisse',
            index=models.Index(fields=['statut'], name='api_caisse_statut_b3a657_idx'),
        ),
        migrations.AddIndex(
            model_name='caisse',
            index=models.Index(fields=['facture', 'statut'], name='api_caisse_facture_ca8c14_idx'),
        ),
        migrations.AddIndex(
            model_name='caisse',
            index=models.Index(fields=['-date_paiement'], name='api_caisse_date_pa_7ed591_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['status'], name='api_facture_status_310fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client', 'status'], name='api_facture_client__9d90f3_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['-date'], name='api_facture_date_dc8f48_idx'),
        ),
        migrations.AddIndex(
            model_name='factureproduit',
            index=models.Index(fields=['produit'], name='api_facture_produit_4b65b3_idx'),
        ),
        migrations.AddIndex(
            model_name='factureproduit',
            index=models.Index(fields=['facture', 'produit'], name='api_facture_facture_3b1e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['stock'], name='api_produit_stock_a2a21e_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['rayon', 'stock'], name='api_produit_rayon_i_d92850_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['fournisseur'], name='api_produit_fournis_5607f1_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['stock', 'stock_minimum'], name='api_produit_stock_1b61aa_idx'),
        ),
    ]
