# Generated by Django 5.2.5 on 2025-12-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_stocklot_unique_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_point', models.DecimalField(decimal_places=0, default=1000, help_text='Montant en FCFA pour gagner 1 point', max_digits=10)),
                ('point_value', models.DecimalField(decimal_places=0, default=10, help_text="Valeur d'un point en FCFA", max_digits=10)),
                ('auto_reward_threshold', models.IntegerField(default=0, help_text='Nombre de points pour déclencher la récompense auto (0=désactivé)')),
                ('auto_reward_percent', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de remise auto', max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuration Fidélité',
                'verbose_name_plural': 'Configuration Fidélité',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='pending_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remise en % acquise pour la prochaine vente', max_digits=5),
        ),
        migrations.AddField(
            model_name='client',
            name='points_fidelite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_fidelite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='points_fidelite_gagnes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='points_fidelite_utilises',
            field=models.IntegerField(default=0),
        ),
    ]
