# Generated by Django 5.2.5 on 2025-12-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_loyaltysetting_client_pending_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_loyalty_member',
            field=models.BooleanField(default=True, help_text='Si activé, ce client participe au programme de fidélité'),
        ),
    ]
