# Generated by Django 5.2.5 on 2025-12-23 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_facture_total_ht_facture_total_ttc_facture_total_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('width_mm', models.DecimalField(decimal_places=2, help_text="Largeur de l'étiquette en millimètres", max_digits=5, verbose_name='Largeur (mm)')),
                ('height_mm', models.DecimalField(decimal_places=2, help_text="Hauteur de l'étiquette en millimètres", max_digits=5, verbose_name='Hauteur (mm)')),
                ('dpi', models.IntegerField(choices=[(203, '203 DPI'), (300, '300 DPI'), (600, '600 DPI')], default=203, help_text="Résolution de l'imprimante Zebra", verbose_name='Résolution DPI')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'étiquette",
                'verbose_name_plural': "Templates d'étiquettes",
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom d'affichage")),
                ('printer_name', models.CharField(help_text="Nom de l'imprimante tel qu'enregistré dans le système", max_length=200, verbose_name="Nom système de l'imprimante")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Pour impression réseau (optionnel)', null=True, verbose_name='Adresse IP')),
                ('port', models.IntegerField(default=9100, help_text='Port ZPL (généralement 9100 pour Zebra)', verbose_name='Port')),
                ('is_default', models.BooleanField(default=False, verbose_name='Imprimante par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration imprimante',
                'verbose_name_plural': 'Configurations imprimantes',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mouvementcaisse',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='motif',
            field=models.CharField(help_text='Ex: Electricité, Carburant, etc.', max_length=200),
        ),
        migrations.CreateModel(
            name='LabelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('TEXT', 'Texte statique'), ('FIELD', 'Champ dynamique'), ('BARCODE', 'Code-barres'), ('QRCODE', 'QR Code'), ('LINE', 'Ligne'), ('RECTANGLE', 'Rectangle')], max_length=20)),
                ('x_mm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Position X (mm)')),
                ('y_mm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Position Y (mm)')),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largeur (mm)')),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hauteur (mm)')),
                ('static_text', models.CharField(blank=True, help_text='Pour les éléments de type TEXT', max_length=500, verbose_name='Texte statique')),
                ('field_name', models.CharField(blank=True, help_text="Pour les éléments de type FIELD (ex: 'product.name')", max_length=50, verbose_name='Nom du champ')),
                ('barcode_type', models.CharField(blank=True, choices=[('CODE128', 'Code 128'), ('EAN13', 'EAN-13'), ('CODE39', 'Code 39'), ('QRCODE', 'QR Code')], max_length=20, verbose_name='Type de code-barres')),
                ('barcode_height', models.IntegerField(default=50, help_text='Hauteur en dots pour le code-barres', verbose_name='Hauteur code-barres (dots)')),
                ('show_barcode_text', models.BooleanField(default=True, verbose_name='Afficher le texte du code-barres')),
                ('font_family', models.CharField(default='0', help_text='Font Zebra: 0=Default, A-Z pour polices spécifiques', max_length=50, verbose_name='Police Zebra')),
                ('font_size', models.IntegerField(default=30, help_text='Hauteur du caractère en dots', verbose_name='Taille de police (dots)')),
                ('font_bold', models.BooleanField(default=False, verbose_name='Gras')),
                ('text_align', models.CharField(choices=[('left', 'Gauche'), ('center', 'Centré'), ('right', 'Droite')], default='left', max_length=10)),
                ('rotation', models.IntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0, verbose_name='Rotation')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('line_thickness', models.IntegerField(default=2, help_text='Pour les lignes et rectangles', verbose_name='Épaisseur (dots)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.labeltemplate')),
            ],
            options={
                'verbose_name': "Élément d'étiquette",
                'verbose_name_plural': "Éléments d'étiquettes",
                'ordering': ['template', 'order'],
            },
        ),
    ]
