# Generated by Django 5.2.5 on 2025-12-24 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_labeltemplate_printerconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remise_automatique',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage de remise automatique (0-100%) appliqué à chaque vente', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise automatique (%)'),
        ),
    ]
