# Generated by Django 5.2.5 on 2025-12-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_commande_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelelement',
            name='template',
        ),
        migrations.DeleteModel(
            name='PrinterConfiguration',
        ),
        migrations.DeleteModel(
            name='LabelElement',
        ),
        migrations.DeleteModel(
            name='LabelTemplate',
        ),
    ]
