# Generated by Django 5.2.5 on 2025-12-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_tva_to_factureproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduit',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Montant de la remise unitaire', max_digits=10),
        ),
    ]
