# Generated by Django 5.2.5 on 2026-01-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_ligneavoir_stock_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique compté (si inventaire par lot)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='api.stocklot'),
        ),
        migrations.AddConstraint(
            model_name='ligneinventaire',
            constraint=models.UniqueConstraint(condition=models.Q(('stock_lot__isnull', False)), fields=('inventaire', 'stock_lot'), name='unique_inventaire_lot'),
        ),
    ]
