# Generated by Django 5.2.5 on 2026-01-03 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_facture_part_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ['-date'], 'verbose_name': 'Clôture de caisse', 'verbose_name_plural': 'Clôtures de caisse'},
        ),
        migrations.RemoveField(
            model_name='cloturecaisse',
            name='details',
        ),
        migrations.RemoveField(
            model_name='cloturecaisse',
            name='ecart',
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='date_debut',
            field=models.DateTimeField(blank=True, help_text='Début de la période de clôture', null=True),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Fin de la période de clôture', null=True),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='details_paiement',
            field=models.JSONField(blank=True, default=dict, help_text='Détails par mode de paiement'),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='ecart_caisse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Écart entre réel et théorique', max_digits=12),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='observation',
            field=models.TextField(blank=True, help_text='Notes ou observations sur la clôture', null=True),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_entrees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Entrées de caisse hors ventes', max_digits=12),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_sorties',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sorties de caisse', max_digits=12),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_ventes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_reel',
            field=models.DecimalField(decimal_places=2, help_text='Montant réellement compté en caisse', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_theorique',
            field=models.DecimalField(decimal_places=2, help_text='Montant théorique calculé', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL),
        ),
    ]
