# Generated by Django 5.2.5 on 2026-01-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_cloturecaisse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.IntegerField(help_text='Stock avant ajustement')),
                ('quantity_after', models.IntegerField(help_text='Stock après ajustement')),
                ('quantity_change', models.IntegerField(help_text='Différence (+/-)')),
                ('reason_type', models.CharField(choices=[('CASSE', 'Casse/Détérioration'), ('PERIME', 'Produit périmé'), ('INVENTAIRE', 'Correction inventaire'), ('VOL', 'Vol/Perte'), ('RETOUR_F', 'Retour fournisseur'), ('ERR_SAISIE', 'Erreur de saisie'), ('AUTRE', 'Autre motif')], max_length=10)),
                ('reason_detail', models.TextField(help_text='Description détaillée du motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='api.produit')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='api.stocklot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['produit', '-created_at'], name='api_stockad_produit_3417fa_idx'), models.Index(fields=['user', '-created_at'], name='api_stockad_user_id_066af7_idx')],
            },
        ),
    ]
