# Generated by Django 5.2.5 on 2026-01-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_stock_adjustment_simplified'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Description lisible de l'action"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('EXPORT', 'Export'), ('OTHER', 'Autre'), ('STOCK_ADJ', 'Ajustement stock'), ('PRICE_CHG', 'Changement prix'), ('CLOTURE', 'Clôture caisse'), ('INV_CANCEL', 'Annulation facture'), ('INV_DEL', 'Suppression facture'), ('INV_VALID', 'Validation facture'), ('INV_CRE', 'Création inventaire'), ('INV_VAL', 'Validation inventaire')], max_length=10),
        ),
    ]
