# Generated by Django 5.2.5 on 2026-01-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_ordonnancier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('BROU', 'Brouillon'), ('PROF', 'Proforma'), ('VAL', 'Validée'), ('PAY', 'Payée'), ('ANN', 'Annulée')], default='BROU', max_length=4),
        ),
    ]
