# Generated by Django 5.2.5 on 2026-01-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_facture_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dernier_achat',
            field=models.DateField(blank=True, help_text='Date du dernier achat (réception de commande)', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='dernier_vente',
            field=models.DateField(blank=True, help_text='Date de la dernière vente', null=True),
        ),
    ]
