# Generated by Django 5.2.5 on 2026-01-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_profile_can_adjust_stock_profile_can_close_commande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='PHARMA STOCK', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, default='Douala', max_length=100)),
                ('country', models.CharField(blank=True, default='Cameroun', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ticket_footer_message', models.TextField(blank=True, default='Merci de votre visite!')),
                ('receipt_header', models.TextField(blank=True, default='', help_text='Message en haut du ticket')),
            ],
            options={
                'verbose_name': 'Paramètres Pharmacie',
                'verbose_name_plural': 'Paramètres Pharmacie',
            },
        ),
    ]
