# Generated by Django 5.2.5 on 2026-01-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_add_pharmacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='niu',
            field=models.CharField(blank=True, default='', help_text="Numéro d'Identification Unique (14-15 caractères)", max_length=15),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='registre_commerce',
            field=models.CharField(blank=True, default='', help_text='Registre de Commerce', max_length=20),
        ),
    ]
