# Generated by Django 5.2.5 on 2026-01-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_pharmacysettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factureproduit',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historiquetransformation',
            name='produit_destination_nom',
            field=models.CharField(blank=True, help_text='Nom du produit destination sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historiquetransformation',
            name='produit_source_nom',
            field=models.CharField(blank=True, help_text='Nom du produit source sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='promis',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegardé', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='api.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit'),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit'),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='produit_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hist_trans_dest', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='produit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hist_trans_source', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit'),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique retourné (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit'),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique compté (si inventaire par lot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires', to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='promis',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promis', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='api.produit'),
        ),
    ]
