# Generated by Django 5.2.5 on 2026-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_avoir_fournisseur_nom_commande_fournisseur_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='commande',
            name='taux_change',
            field=models.DecimalField(decimal_places=3, default=655.957, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('LOC', 'Locale'), ('DIR', 'Directe')], default='LOC', help_text='Type de commande (Locale ou Directe)', max_length=3),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='prix_euro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='coefficient_direct_commande',
            field=models.DecimalField(decimal_places=2, default=1.35, help_text='Coefficient multiplicateur pour les commandes directes (Euro -> Revient)', max_digits=5),
        ),
    ]
