# Generated by Django 5.2.5 on 2026-01-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_stocklot_commande_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible sur le site vitrine ?'),
        ),
        migrations.AddField(
            model_name='produit',
            name='public_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix affiché en ligne (Laisser vide pour utiliser le prix de vente)', max_digits=10, null=True),
        ),
    ]
