# Generated by Django 5.2.5 on 2026-01-21 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_forme_alter_cloturecaisse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponMonnaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=10, unique=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('UTILISE', 'Utilisé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_crees', to=settings.AUTH_USER_MODEL)),
                ('facture_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_generes', to='api.facture')),
                ('facture_utilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_utilises', to='api.facture')),
                ('utilise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_utilises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Monnaie',
                'verbose_name_plural': 'Coupons Monnaie',
                'ordering': ['-date_creation'],
            },
        ),
    ]
