# Generated by Django 5.2.5 on 2026-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_couponmonnaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_generate_coupon',
            field=models.BooleanField(default=False, verbose_name='Générer des coupons'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte'), ('virement', 'Virement'), ('om', 'Orange Money'), ('momo', 'Mobile Money'), ('en_compte', 'En compte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entr├®e (Commande)'), ('SORTIE', 'Sortie (Vente)'), ('RETOUR', 'Retour (Annulation)'), ('AJUSTEMENT', 'Ajustement Inventaire'), ('AVOIR', 'Avoir (Retour Fournisseur)'), ('TRANSFORMATION_ENTREE', 'Transformation (Entrée)'), ('TRANSFORMATION_SORTIE', 'Transformation (Sortie)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_close_commande',
            field=models.BooleanField(default=False, verbose_name='Clôturer des commandes'),
        ),
    ]
