# Generated by Django 5.2.5 on 2026-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_profile_can_generate_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Produit visible sur la vitrine en ligne'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dernier_vente',
            field=models.DateField(blank=True, help_text='Date de la dernière vente', null=True),
        ),
    ]
