# Generated by Django 5.2.5 on 2026-01-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_add_is_public_to_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneavoir',
            name='est_cloture',
            field=models.BooleanField(default=False, help_text='Indique si cette ligne est administrativement clôturée'),
        ),
    ]
