# Generated by Django 5.2.5 on 2026-01-26 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_famillerisque_produit_famille_risque'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_modify_price',
            field=models.BooleanField(default=False, verbose_name='Modifier le prix de vente'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise maximum (%)'),
        ),
    ]
