# Generated by Django 5.2.5 on 2026-01-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_profile_can_modify_price_profile_max_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='rayon_capacity',
            field=models.IntegerField(blank=True, help_text='Capacité maximale du rayon', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_rayon_min',
            field=models.IntegerField(blank=True, help_text='Seuil minimal pour le rayon', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_reserve',
            field=models.IntegerField(default=0, help_text='Quantité en réserve (non disponible pour la vente directe)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Cr├®ation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('EXPORT', 'Export'), ('OTHER', 'Autre'), ('STOCK_ADJ', 'Ajustement stock'), ('PRICE_CHG', 'Changement prix'), ('CLOTURE', 'Cl├┤ture caisse'), ('INV_CANCEL', 'Annulation facture'), ('INV_DEL', 'Suppression facture'), ('INV_VALID', 'Validation facture'), ('INV_CRE', 'Cr├®ation inventaire'), ('INV_VAL', 'Validation inventaire'), ('ORD_RECV', 'R├®ception commande'), ('ORD_CNCL', 'Annulation r├®ception')], max_length=10),
        ),
    ]
