# Generated by Django 5.2.5 on 2026-01-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_produit_rayon_capacity_produit_stock_rayon_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('code_cas', models.CharField(blank=True, help_text='Code CAS pour identification unique', max_length=50, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='code_atc',
            field=models.CharField(blank=True, help_text='Code ATC (Anatomique Thérapeutique Chimique)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='substance_active',
            field=models.CharField(blank=True, help_text='Nom de la substance active principale (Texte libre)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='substances',
            field=models.ManyToManyField(blank=True, help_text='Substances actives structurées pour les interactions', related_name='produits', to='api.substance'),
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravity', models.CharField(choices=[('PRECAUTION', "Précaution d'emploi"), ('A_PRENDRE_EN_COMPTE', 'A prendre en compte'), ('DECONSEILLE', 'Déconseillé'), ('CONTRE_INDIQUE', 'Contre-indiqué')], default='PRECAUTION', max_length=20)),
                ('description', models.TextField(help_text='Description du risque et de la conduite à tenir')),
                ('substance_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_a', to='api.substance')),
                ('substance_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_b', to='api.substance')),
            ],
            options={
                'verbose_name': 'Interaction Médicamenteuse',
                'verbose_name_plural': 'Interactions Médicamenteuses',
                'unique_together': {('substance_a', 'substance_b')},
            },
        ),
    ]
