# Generated by Django 5.2.5 on 2026-01-27 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_substance_produit_code_atc_produit_substance_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ['-date'], 'verbose_name': 'Clôture de caisse', 'verbose_name_plural': 'Clôtures de caisse'},
        ),
        migrations.AlterModelOptions(
            name='loyaltysetting',
            options={'verbose_name': 'Configuration Fidélité', 'verbose_name_plural': 'Configuration Fidélité'},
        ),
        migrations.AlterModelOptions(
            name='pharmacysettings',
            options={'verbose_name': 'Paramètres Pharmacie', 'verbose_name_plural': 'Paramètres Pharmacie'},
        ),
        migrations.AddField(
            model_name='ligneavoir',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('EXPORT', 'Export'), ('OTHER', 'Autre'), ('STOCK_ADJ', 'Ajustement stock'), ('PRICE_CHG', 'Changement prix'), ('CLOTURE', 'Clôture caisse'), ('INV_CANCEL', 'Annulation facture'), ('INV_DEL', 'Suppression facture'), ('INV_VALID', 'Validation facture'), ('INV_CRE', 'Création inventaire'), ('INV_VAL', 'Validation inventaire'), ('ORD_RECV', 'Réception commande'), ('ORD_CNCL', 'Annulation réception')], max_length=10),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='type_avoir',
            field=models.CharField(choices=[('PERIME', 'Produit périmé'), ('AVARIE', 'Produit avarié'), ('NON_FACTURE', 'Livré non facturé'), ('ERREUR', 'Erreur de livraison'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='part_patient',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part payée par le patient (tiers payant)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_loyalty_member',
            field=models.BooleanField(default=True, help_text='Si activé, ce client participe au programme de fidélité'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='remise_automatique',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage de remise automatique (0-100%) appliqué à chaque vente', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise automatique (%)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='date_debut',
            field=models.DateTimeField(blank=True, help_text='Début de la période de clôture', null=True),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Fin de la période de clôture', null=True),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='details_paiement',
            field=models.JSONField(blank=True, default=dict, help_text='Détails par mode de paiement'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='ecart_caisse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Écart entre réel et théorique', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_reel',
            field=models.DecimalField(decimal_places=2, help_text='Montant réellement compté en caisse', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_theorique',
            field=models.DecimalField(decimal_places=2, help_text='Montant théorique calculé', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='observation',
            field=models.TextField(blank=True, help_text='Notes ou observations sur la clôture', null=True),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_entrees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Entrées de caisse hors ventes', max_digits=12),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('PREP', 'En préparation'), ('ATT', 'En attente'), ('CLOT', 'Clôturée')], default='PREP', max_length=4),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='quantity',
            field=models.IntegerField(help_text='Quantité commandée et payée'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='unites_gratuites',
            field=models.IntegerField(default=0, help_text='Unités gratuites reçues (ex: promotion 3+1)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='part_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part à payer par le client (Tiers Payant)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('BROU', 'Brouillon'), ('PROF', 'Proforma'), ('VAL', 'Validée'), ('PAY', 'Payée'), ('ANN', 'Annulée')], default='BROU', max_length=4),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique choisi manuellement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TVA applicable à cette ligne', max_digits=5),
        ),
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='quantity',
            field=models.IntegerField(help_text='Quantité prélevée de ce lot'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='produit_destination_nom',
            field=models.CharField(blank=True, help_text='Nom du produit destination sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='produit_source_nom',
            field=models.CharField(blank=True, help_text='Nom du produit source sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='quantite_destination',
            field=models.IntegerField(help_text='Quantité obtenue (destination)'),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='quantite_source',
            field=models.IntegerField(help_text='Quantité transformée (source)'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='centralized_cash_register',
            field=models.BooleanField(default=False, help_text='Activer le mode Caisse Centralisée'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='company_address',
            field=models.TextField(default="Adresse de l'entreprise\nTéléphone: 00 00 00 00 00"),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='company_name',
            field=models.CharField(default='Ma Société', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='header_layout',
            field=models.CharField(choices=[('split', 'Séparé (Logo Gauche / Info Droite)'), ('left', 'Tout à Gauche'), ('center', 'Tout Centré'), ('right', 'Tout à Droite')], default='split', max_length=20),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique retourné (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique compté (si inventaire par lot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires', to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='lotsequence',
            name='last_number',
            field=models.IntegerField(default=0, help_text='Dernier numéro de séquence utilisé'),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='auto_reward_threshold',
            field=models.IntegerField(default=0, help_text='Nombre de points pour déclencher la récompense auto (0=désactivé)'),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='motif',
            field=models.CharField(help_text='Ex: Électricité, Carburant, etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='type',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(help_text='Quantité mouvementée (positive ou négative)'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='stock_apres',
            field=models.IntegerField(blank=True, help_text='Stock après mouvement (snapshot)', null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée (Commande)'), ('SORTIE', 'Sortie (Vente)'), ('RETOUR', 'Retour (Annulation)'), ('AJUSTEMENT', 'Ajustement Inventaire'), ('AVOIR', 'Avoir (Retour Fournisseur)'), ('TRANSFORMATION_ENTREE', 'Transformation (Entrée)'), ('TRANSFORMATION_SORTIE', 'Transformation (Sortie)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordonnancier',
            name='prescripteur_nom',
            field=models.CharField(help_text='Nom du médecin prescripteur', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='niu',
            field=models.CharField(blank=True, default='', help_text="Numéro d'Identification Unique (14-15 caractères)", max_length=15),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dernier_achat',
            field=models.DateField(blank=True, help_text='Date du dernier achat (réception de commande)', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pmp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix Moyen Pondéré', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='requires_prescription',
            field=models.BooleanField(default=False, help_text='Ce produit nécessite une ordonnance'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='surveillance_category',
            field=models.CharField(choices=[('NONE', 'Aucune'), ('STANDARD', 'Surveillance standard'), ('RENFORCEE', 'Surveillance renforcée')], default='NONE', help_text='Catégorie de surveillance du médicament', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='use_lot_management',
            field=models.BooleanField(default=True, help_text='Activer la gestion par lots FIFO pour ce produit (recommandé pour traçabilité)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_cash_out',
            field=models.BooleanField(default=True, help_text='Autorisé à encaisser (si mode centralisé actif)'),
        ),
        migrations.AlterField(
            model_name='promis',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Téléphone du client', max_length=20),
        ),
        migrations.AlterField(
            model_name='promis',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='promis',
            name='quantite',
            field=models.IntegerField(help_text='Quantité promise au client'),
        ),
        migrations.AlterField(
            model_name='promis',
            name='status',
            field=models.CharField(choices=[('ATT', 'En attente'), ('DEL', 'Délivré'), ('ANN', 'Annulé')], default='ATT', max_length=4),
        ),
        migrations.AlterField(
            model_name='relationtransformation',
            name='produit_destination',
            field=models.ForeignKey(help_text='Produit résultant (ex: DETAIL)', on_delete=django.db.models.deletion.CASCADE, related_name='transformations_destination', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='relationtransformation',
            name='produit_source',
            field=models.ForeignKey(help_text='Produit à transformer (ex: BOITE)', on_delete=django.db.models.deletion.CASCADE, related_name='transformations_source', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='relationtransformation',
            name='ratio',
            field=models.DecimalField(decimal_places=2, help_text='Ratio de conversion (ex: 20.00 si 1 boîte = 20 détails)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_after',
            field=models.IntegerField(help_text='Stock après ajustement'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.IntegerField(help_text='Différence (+/-)'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason_type',
            field=models.CharField(choices=[('INVENTAIRE', 'Ajustement inventaire'), ('CASSE', 'Cassé'), ('VOL', 'Vol'), ('CONFUSION', 'Confusion'), ('ERR_ENTREE', "Erreur d'entrée en stock"), ('AVARIE', 'Avarié'), ('USAGE_INT', 'Usage interne')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='commande_produit',
            field=models.ForeignKey(blank=True, help_text='Référence à la ligne de commande (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_lot', to='api.commandeproduit'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='date_reception',
            field=models.DateTimeField(help_text='Date de réception du lot (pour FIFO)'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='lot',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro de lot auto-généré ou manuel', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='price_cost',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire effectif (ajusté avec UG)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegardé', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_free',
            field=models.IntegerField(default=0, help_text='Unités gratuites (UG)'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_initial',
            field=models.IntegerField(help_text='Quantité totale initiale (payée + gratuites)'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_paid',
            field=models.IntegerField(default=0, help_text='Quantité payée uniquement'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_remaining',
            field=models.IntegerField(help_text='Quantité restante dans le lot'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de vente lors de la réception', max_digits=10),
        ),
    ]
