# Generated by Django 5.2.5 on 2026-01-27 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_cloturecaisse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom du template (ex: 'Promis Dispo')", max_length=100, unique=True)),
                ('content', models.TextField(help_text="Contenu avec variables (ex: 'Bonjour {name}, votre {product} est arrivé.')")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modèle SMS',
                'verbose_name_plural': 'Modèles SMS',
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(help_text='Numéro de téléphone du destinataire', max_length=20)),
                ('recipient_name', models.CharField(blank=True, help_text='Nom du destinataire', max_length=100)),
                ('message', models.TextField(help_text='Contenu du SMS')),
                ('type', models.CharField(choices=[('PROMIS', 'Disponibilité Promis'), ('RAPPEL', 'Rappel Prise'), ('MANUEL', 'Envoi Manuel'), ('MARKETING', 'Marketing')], default='MANUEL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('DELIVERED', 'Reçu')], default='PENDING', max_length=20)),
                ('provider_id', models.CharField(blank=True, help_text='ID renvoyé par le fournisseur SMS', max_length=100, null=True)),
                ('provider_response', models.TextField(blank=True, help_text='Réponse brute du fournisseur (JSON)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='api.client')),
                ('promis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='api.promis')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal SMS',
                'verbose_name_plural': 'Journal SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
