# Generated by Django 5.2.5 on 2026-01-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_smstemplate_smslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='rayon_capacity',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock_rayon_min',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock_reserve',
        ),
    ]
