# Generated by Django 5.2.5 on 2026-01-28 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_paiementfournisseur_date_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='date_paiement',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
