# Generated by Django 5.2.5 on 2026-01-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_produit_is_supplier_exclusive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code technique (ex: PERIME)', max_length=50)),
                ('label', models.CharField(help_text='Libellé affiché (ex: Produit Périmé)', max_length=200)),
                ('type', models.CharField(choices=[('STOCK_ADJ', 'Motif Ajustement Stock'), ('SUPPLIER_RET', 'Motif Retour Fournisseur'), ('MONEY_DENOM', 'Coupure Monnaie')], max_length=20)),
                ('value', models.CharField(blank=True, help_text='Valeur optionnelle (ex: 10000 pour un billet)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Option de Configuration',
                'verbose_name_plural': 'Options de Configuration',
                'ordering': ['type', 'order', 'label'],
                'unique_together': {('type', 'code')},
            },
        ),
    ]
