# Generated by Django 5.2.5 on 2026-02-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_inventaire_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='inventory_type',
            field=models.CharField(choices=[('PARTIEL', 'Tournant / Partiel'), ('GENERAL', 'Général / Annuel')], default='PARTIEL', max_length=20),
        ),
    ]
