# Generated by Django 5.2.5 on 2026-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_remove_inventaire_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
