# Generated by Django 5.2.5 on 2026-02-05 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_add_is_active_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('JOUR', 'Journalier'), ('SEMAINE', 'Hebdomadaire'), ('MOIS', 'Mensuel')], help_text='Type de période pour cet objectif', max_length=10)),
                ('date_debut', models.DateField(help_text='Premier jour de la période (lundi pour semaine, 1er pour mois)')),
                ('ca_objectif', models.DecimalField(decimal_places=2, help_text="Objectif de chiffre d'affaires pour cette période", max_digits=15)),
                ('nb_ventes_objectif', models.IntegerField(blank=True, help_text='Objectif de nombre de ventes (optionnel)', null=True)),
                ('panier_moyen_objectif', models.DecimalField(blank=True, decimal_places=2, help_text='Objectif de panier moyen (optionnel)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur cet objectif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objectif Commercial',
                'verbose_name_plural': 'Objectifs Commerciaux',
                'ordering': ['-date_debut', 'periode'],
                'unique_together': {('periode', 'date_debut')},
            },
        ),
    ]
