# Generated by Django 5.2.5 on 2026-02-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caisse',
            name='idx_caisse_facture_status',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='idx_commande_fournisseur_date',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='idx_facture_date_status',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='idx_facture_user_date_status',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='idx_produit_stock_alerts',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='idx_produit_active_stock',
        ),
        migrations.AddField(
            model_name='facture',
            name='date_document',
            field=models.DateTimeField(blank=True, help_text='Date affichée sur les documents (si différente de la date de création)', null=True),
        ),
    ]
