# Generated by Django 5.2.5 on 2026-02-12 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_commande_closed_by_alter_commande_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a annulé la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validated', to=settings.AUTH_USER_MODEL),
        ),
    ]
