# Generated by Django 5.2.5 on 2026-02-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_avoir_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='facture',
            field=models.ForeignKey(blank=True, help_text='Facture associée au mouvement (pour les ventes/retours)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.facture'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason_type',
            field=models.CharField(choices=[('INVENTAIRE', 'Ajustement inventaire'), ('CASSE', 'Cassé'), ('VOL', 'Vol'), ('CONFUSION', 'Confusion'), ('ERR_ENTREE', "Erreur d'entrée en stock"), ('AVARIE', 'Avarié'), ('USAGE_INT', 'Usage interne'), ('PERIME', 'Périmé')], max_length=10),
        ),
    ]
