# Generated by Django 5.2.5 on 2026-02-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_mouvementstock_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='Commande associée au mouvement (pour les achats/réceptions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.commande'),
        ),
    ]
