# Generated by Django 5.2.5 on 2026-02-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_mouvementstock_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSessionSequence',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ticket_session_sequence',
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='ticket_session',
            field=models.IntegerField(blank=True, help_text='Numéro de ticket pour la session du jour', null=True),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='inventaire',
            field=models.ForeignKey(blank=True, help_text='Inventaire associé au mouvement (pour les ajustements)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.inventaire'),
        ),
    ]
