# Generated by Django 5.2.5 on 2026-02-16 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_profile_can_cancel_invoice_profile_can_cancel_promis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='central_server_url',
            field=models.URLField(blank=True, default='', help_text='URL du serveur central (ex: https://monitor.ma-pharma.com)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='monitoring_enabled',
            field=models.BooleanField(default=False, help_text="Activer l'envoi de données au serveur central"),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='monitoring_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique de cette instance pour le monitoring'),
        ),
    ]
