# Generated by Django 5.2.5 on 2026-02-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_echeance',
            field=models.DateField(blank=True, help_text='Calculée automatiquement selon le délai du fournisseur.', null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='delai_paiement_jours',
            field=models.IntegerField(default=0, help_text='Délai de paiement accordé en jours (ex: 10, 15). 0 = au comptant.'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_reglement',
            field=models.CharField(choices=[('FACTURE', 'À la facture'), ('RELEVE', 'Sur relevé')], default='FACTURE', help_text="Mode d'échéance des paiements. Ubipharm/Laborex = RELEVE, Autres = FACTURE.", max_length=20),
        ),
    ]
