# Generated by Django 5.2.5 on 2026-02-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_commande_date_echeance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfournisseur',
            name='commandes',
            field=models.ManyToManyField(blank=True, help_text='Les factures (commandes) réglées par ce paiement global (Pointage)', related_name='paiements_multiples', to='api.commande'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='[Déprécié] Facture spécifique liée à ce paiement (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='api.commande'),
        ),
    ]
