# Generated by Django 5.2.5 on 2026-02-27 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_alter_caisse_mode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationObjectifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MANUEL', 'Manuel'), ('FIXE', 'Objectif Fixe (Seuil de rentabilité)'), ('DYNAMIQUE', "Dynamique (Basé sur l'historique)")], default='MANUEL', help_text='Mode de calcul des objectifs (Manuel, Fixe ou Dynamique)', max_length=20)),
                ('seuil_rentabilite_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Seuil de rentabilité mensuel (utilisé en mode FIXE). Utilisé pour calculer l'objectif quotidien.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pourcentage_croissance', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Pourcentage de croissance visé (utilisé en mode DYNAMIQUE par rapport à N-1 ou la moyenne récente).', max_digits=5)),
                ('jours_ouverts_semaine', models.IntegerField(default=6, help_text="Nombre de jours d'ouverture par semaine (pour diviser l'objectif mensuel en quotidien).", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Objectifs',
                'verbose_name_plural': 'Configurations Objectifs',
            },
        ),
        migrations.AlterModelOptions(
            name='loyaltysetting',
            options={'ordering': ['pk'], 'verbose_name': 'Configuration Fidélité', 'verbose_name_plural': 'Configuration Fidélité'},
        ),
        migrations.AlterField(
            model_name='caisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte'), ('virement', 'Virement'), ('om', 'Orange Money'), ('momo', 'Mobile Money'), ('coupon', 'Coupon'), ('en_compte', 'En compte'), ('recouvrement', 'Recouvrement')], max_length=20),
        ),
    ]
