# Generated by Django 5.2.5 on 2026-02-28 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, default='', help_text='Meta Access Token (Permanent)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='whatsapp_business_id',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Business Account ID', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, default='', help_text='Phone Number ID', max_length=50),
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_path', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('FACTURE', 'Envoi Facture'), ('PROMIS', 'Disponibilité Promis'), ('MANUEL', 'Envoi Manuel'), ('RAPPEL', 'Rappel Paiement')], default='FACTURE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('DELIVERED', 'Reçu'), ('READ', 'Lu')], default='PENDING', max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='api.client')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='api.facture')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal WhatsApp',
                'verbose_name_plural': 'Journal WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
