# Generated by Django 5.2.5 on 2026-03-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_produit_capacite_rayon_produit_has_reserve_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée (Commande)'), ('SORTIE', 'Sortie (Vente)'), ('RETOUR', 'Retour (Annulation)'), ('AJUSTEMENT', 'Ajustement Inventaire'), ('AVOIR', 'Avoir (Retour Fournisseur)'), ('TRANSFORMATION_ENTREE', 'Transformation (Entrée)'), ('TRANSFORMATION_SORTIE', 'Transformation (Sortie)'), ('REAPPRO_INTERSTOCK', 'Réappro (Réserve -> Rayon)')], max_length=30),
        ),
    ]
