# Generated by Django 5.2.5 on 2026-03-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_inventaire_reference_alter_commande_numero_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='inventory_type',
            field=models.CharField(choices=[('GLOBAL', 'Stock Global'), ('RAYON', 'Stock Rayon'), ('RESERVE', 'Stock Réserve')], default='GLOBAL', help_text='Type de stock inventorié', max_length=20),
        ),
    ]
