# Generated by Django 5.2.5 on 2026-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_inventaire_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='quantity_free_remaining',
            field=models.IntegerField(default=0, help_text='Unités gratuites restantes en rayon'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_remaining',
            field=models.IntegerField(help_text='Quantité totale restante en rayon'),
        ),
    ]
