# Generated by Django 5.2.5 on 2026-03-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_userdailysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='backup_enabled',
            field=models.BooleanField(default=True, help_text='Activer la sauvegarde automatique quotidienne'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='backup_time',
            field=models.TimeField(default='02:00:00', help_text='Heure de la sauvegarde automatique (ex: 02:00)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='secondary_backup_path',
            field=models.CharField(blank=True, default='', help_text='Chemin secondaire (ex: E:\\Backups_Pharmacie) pour double sauvegarde', max_length=500),
        ),
    ]
