# Generated by Django 5.2.5 on 2026-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_cloturecaisse_cloture_par_alter_cloturecaisse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmonnaie',
            name='numero',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
