# Generated by Django 5.2.5 on 2026-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_profile_can_modify_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailysession',
            name='workstation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
