# Generated by Django 5.2.5 on 2026-03-23 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_alter_auditlog_timestamp_alter_mouvementcaisse_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='solde_depot',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Solde actuel du dépôt/acompte du client', max_digits=12),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte'), ('virement', 'Virement'), ('om', 'Orange Money'), ('momo', 'Mobile Money'), ('coupon', 'Coupon'), ('en_compte', 'En compte'), ('depot', 'Dépôt/Acompte'), ('recouvrement', 'Recouvrement')], max_length=20),
        ),
        migrations.CreateModel(
            name='DepotClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOT', 'Dépôt (Crédit)'), ('RETRAIT', 'Retrait/Remboursement (Débit)'), ('ACHAT', 'Utilisation pour achat (Débit)'), ('ANNUL', 'Annulation achat (Crédit)')], default='DEPOT', max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(blank=True, help_text='Mode de versement initial (ESP, CHQ, etc.)', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots_historique', to='api.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_utilises', to='api.facture')),
                ('mouvement_caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depot_associe', to='api.mouvementcaisse')),
            ],
            options={
                'verbose_name': 'Dépôt Client',
                'verbose_name_plural': 'Dépôts Clients',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', '-date'], name='api_depotcl_client__f62cc0_idx'), models.Index(fields=['type'], name='api_depotcl_type_e4dea4_idx')],
            },
        ),
    ]
