# Generated by Django 5.2.5 on 2026-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_client_is_deposit_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_deposit_enabled',
            field=models.BooleanField(blank=True, default=False, help_text='Si activé, ce client peut utiliser le système de dépôt'),
        ),
    ]
