# Generated by Django 6.0.3 on 2026-03-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=19.25, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='pharmacy_name',
            field=models.CharField(default='ZENITH', max_length=200),
        ),
    ]
