# Generated by Django 6.0.3 on 2026-03-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_commandeproduit_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='produit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
