# Generated by Django 6.0.3 on 2026-03-24 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_alter_commandeproduit_tva_alter_produit_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stocklot'),
        ),
    ]
