# Generated by Django 6.0.3 on 2026-03-28 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_remove_internalmessage_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmessage',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_internal_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='internal_messages/attachments/'),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='api.internalmessage'),
        ),
    ]
