# Generated by Django 6.0.3 on 2026-03-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_internalmessage_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='message_alerte',
            field=models.TextField(blank=True, help_text="Message d'alerte affiché lors de la sélection du client en caisse", null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='message_alerte',
            field=models.TextField(blank=True, help_text="Message d'alerte affiché lors de la saisie en caisse", null=True),
        ),
    ]
