# Generated by Django 6.0.3 on 2026-03-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_client_message_alerte_produit_message_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blocking_alerte',
            field=models.BooleanField(default=False, help_text="Si coché, l'alerte bloque la facturation tant qu'elle n'est pas acquittée."),
        ),
        migrations.AddField(
            model_name='produit',
            name='blocking_alerte',
            field=models.BooleanField(default=False, help_text="Si coché, l'alerte bloque la validation de la vente tant qu'elle n'est pas acquittée."),
        ),
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.stocklot'),
        ),
    ]
