# Generated by Django 6.0.3 on 2026-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_client_blocking_alerte_produit_blocking_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='reserve_after',
            field=models.IntegerField(default=0, help_text='Stock Réserve après ajustement'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reserve_before',
            field=models.IntegerField(default=0, help_text='Stock Réserve avant ajustement'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reserve_change',
            field=models.IntegerField(default=0, help_text='Différence Réserve (+/-)'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_after',
            field=models.IntegerField(help_text='Stock Rayon après ajustement'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_before',
            field=models.IntegerField(help_text='Stock Rayon avant ajustement'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.IntegerField(help_text='Différence Rayon (+/-)'),
        ),
    ]
