# Generated by Django 6.0.3 on 2026-04-09 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_stockadjustment_reserve_after_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason_type',
            field=models.CharField(choices=[('INVENTAIRE', 'Ajustement inventaire'), ('CASSE', 'Cassé'), ('VOL', 'Vol'), ('CONFUSION', 'Confusion'), ('ERR_ENTREE', "Erreur d'entrée en stock"), ('AVARIE', 'Avarié'), ('USAGE_INT', 'Usage interne'), ('PERIME', 'Périmé'), ('REAPPRO', 'Réapprovisionnement')], max_length=10),
        ),
        migrations.CreateModel(
            name='ReapproSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(default=0, help_text='Nombre de produits distincts impactés')),
                ('total_units', models.IntegerField(default=0, help_text="Nombre total d'unités transférées")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(help_text='Utilisateur ayant effectué le réappro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reappro_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reappro_session',
            field=models.ForeignKey(blank=True, help_text='Session de réapprovisionnement associée (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='api.reapprosession'),
        ),
    ]
