# Generated by Django 6.0.3 on 2026-04-12 20:34

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_alter_stockadjustment_reason_type_reapprosession_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name='produit',
            name='cip1',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cip2',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cip3',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='produit_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
