# Generated by Django 6.0.3 on 2026-04-21 11:39

import django.contrib.postgres.operations
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_pharmacysettings_availability_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        django.contrib.postgres.operations.BtreeGinExtension(),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='client_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=django.contrib.postgres.indexes.GinIndex(fields=['numero_facture'], name='facture_num_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
