# Generated by Django 6.0.3 on 2026-04-21 11:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_client_client_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cip1'], name='produit_cip1_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cip2'], name='produit_cip2_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cip3'], name='produit_cip3_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
