# Generated by Django 6.0.3 on 2026-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_produit_produit_cip1_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='pharmacist_whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Numéro WhatsApp de la pharmacienne titulaires (format international sans +)', max_length=50),
        ),
    ]
