# Generated by Django 6.0.3 on 2026-04-28 19:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_ordonnancier_image_ordonnance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active_days', models.JSONField(default=list, help_text='List of active days [0-6]')),
                ('frequency_weeks', models.IntegerField(default=1)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default='12:00')),
                ('is_active', models.BooleanField(default=True)),
                ('has_alert_sound', models.BooleanField(default=True)),
                ('has_teletransmission', models.BooleanField(default=False)),
                ('teletransmission_mode', models.CharField(choices=[('IMMEDIATE', 'Immédiate'), ('BATCH', 'Par lots')], default='IMMEDIATE', max_length=20)),
                ('needs_financial_reception', models.BooleanField(default=True)),
                ('print_copies', models.IntegerField(default=1)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('auto_reception_delay', models.IntegerField(default=0, help_text='Minutes before auto-reception')),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('special_code', models.CharField(blank=True, max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_items', models.IntegerField(default=0)),
                ('condition_logic', models.CharField(choices=[('AND', 'ET'), ('OR', 'OU')], default='AND', max_length=3)),
                ('comment', models.TextField(blank=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.fournisseur')),
            ],
        ),
    ]
