# Generated by Django 6.0.3 on 2026-04-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_alter_mouvementcaisse_id_orderschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderschedule',
            name='analysis_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='execution_mode',
            field=models.CharField(choices=[('SIMPLE', 'Mode Simple (Seuils)'), ('OPTIMISE', 'Mode Intelligent (IA/Ventes)')], default='OPTIMISE', max_length=10),
        ),
    ]
