# Generated by Django 6.0.3 on 2026-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_add_periode_releve_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Avoir actif (non supprimé dans la corbeille)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Commande active (non supprimée dans la corbeille)'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inventaire actif (non supprimé dans la corbeille)'),
        ),
        migrations.AddField(
            model_name='promis',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Promis actif (non supprimé dans la corbeille)'),
        ),
    ]
