# Generated by Django 6.0.3 on 2026-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_optimistic_locking_version'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_auditlog_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='caisse',
            name='idx_caisse_facture_statut',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='idx_client_name',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='idx_client_solde',
        ),
        migrations.RemoveIndex(
            model_name='commandeproduit',
            name='idx_cmdproduit_commande',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='idx_facture_client_status',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='idx_facture_date',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='idx_facture_status_active',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='idx_facture_version',
        ),
        migrations.RemoveIndex(
            model_name='mouvementcaisse',
            name='idx_mvtcaisse_date_type',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='idx_produit_name_full',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='idx_produit_rayon',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='idx_produit_version',
        ),
        migrations.RemoveIndex(
            model_name='stocklot',
            name='idx_stocklot_produit_qty',
        ),
        migrations.RemoveIndex(
            model_name='stocklot',
            name='idx_stocklot_expiration',
        ),
        migrations.RemoveIndex(
            model_name='stocklot',
            name='idx_stocklot_version',
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Token du bot Telegram (de @BotFather)', max_length=200),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Chat ID de la pharmacienne (récupéré via /start sur le bot)', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
