# Generated by Django 6.0.3 on 2026-05-07 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_client_majoration_pro_pourcentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro de compte (ex: 701100)', max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte Comptable',
                'verbose_name_plural': 'Comptes Comptables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Journal Comptable',
                'verbose_name_plural': 'Journaux Comptables',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='plafond',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(help_text='N° de facture ou référence pièce', max_length=100)),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_compta', to='api.commande')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_compta', to='api.facture')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_compta', to='api.caisse')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='api.journalcomptable')),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'verbose_name_plural': 'Écritures Comptables',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_ligne', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='api.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.ecriturecomptable')),
            ],
            options={
                'verbose_name': "Ligne d'Écriture",
                'verbose_name_plural': "Lignes d'Écritures",
            },
        ),
    ]
