# Generated by Django 5.2.13 on 2026-05-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_comptecomptable_journalcomptable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Exercice 2026', max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_cloture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercice Comptable',
                'verbose_name_plural': 'Exercices Comptables',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='api.exercicecomptable'),
        ),
    ]
