# Generated by Django 6.0.3 on 2026-05-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_exercicecomptable_ecriturecomptable_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriturecomptable',
            name='paiement_fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_compta', to='api.paiementfournisseur'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PHARMACIEN', 'Pharmacien'), ('VENDEUR', 'Vendeur'), ('CAISSIER', 'Caissier'), ('COMPTABLE', 'Comptable')], default='VENDEUR', max_length=20),
        ),
    ]
