# Generated by Django 6.0.3 on 2026-05-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_ecriturecomptable_paiement_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='niu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIU'),
        ),
        migrations.AddField(
            model_name='client',
            name='registre_commerce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registre de Commerce'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
