# Generated by Django 6.0.3 on 2026-05-10 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_stocklot_is_divers_alter_commande_type'),
    ]

    operations = [
        # Ajouter le champ numero_piece manquant
        migrations.AddField(
            model_name='ecriturecomptable',
            name='numero_piece',
            field=models.CharField(
                max_length=30, 
                unique=True, 
                blank=True, 
                null=True,  # Temporairement nullable pour la migration
                help_text="Numéro folioté OHADA (EX2026-VT-00001)"
            ),
        ),
        # Modifier les options Meta
        migrations.AlterModelOptions(
            name='ecriturecomptable',
            options={
                'ordering': ['exercice', 'journal', 'numero_piece'],
                'verbose_name': "Écriture Comptable",
                'verbose_name_plural': "Écritures Comptables",
            },
        ),
        # Modifier le champ exercice pour permettre null (comme dans le modèle actuel)
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='exercice',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='ecritures', 
                to='api.exercicecomptable'
            ),
        ),
        # Ajouter le unique_together
        migrations.AlterUniqueTogether(
            name='ecriturecomptable',
            unique_together={('exercice', 'journal', 'numero_piece')},
        ),
    ]
