# Generated by Django 6.0.3 on 2026-05-10 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_alter_ecriturecomptable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lettrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Code lettrage automatique (L-2024-0001)', max_length=20, unique=True)),
                ('date_lettrage', models.DateField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, help_text='True si Débit = Crédit du lettrage', max_digits=15)),
                ('est_equilibre', models.BooleanField(default=False, help_text='True si Débit = Crédit du lettrage')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte_tiers', models.ForeignKey(help_text='Compte tiers (411xxx ou 401xxx)', limit_choices_to={'numero__startswith': '4'}, on_delete=django.db.models.deletion.PROTECT, to='api.comptecomptable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={
                'ordering': ['-date_lettrage', '-created_at'],
                'verbose_name': 'Lettrage',
                'verbose_name_plural': 'Lettrages',
            },
        ),
        migrations.CreateModel(
            name='LettrageLignes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lettrage')),
                ('ligneecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ligneecriture')),
            ],
            options={
                'db_table': 'api_lettrage_lignes',
            },
        ),
        migrations.AddField(
            model_name='lettrage',
            name='lignes',
            field=models.ManyToManyField(related_name='lettrages', through='api.LettrageLignes', to='api.ligneecriture'),
        ),
    ]
