# Generated by Django 6.0.3 on 2026-05-10 18:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_create_lettrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='is_divers',
            field=models.BooleanField(default=False, help_text='Fournisseur utilisé pour les achats divers (produits sans lien avec le stock normal)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('LOC', 'Locale'), ('DIR', 'Directe'), ('DIV', 'Divers')], default='LOC', help_text='Type de commande (Locale, Directe ou Divers)', max_length=3),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='code',
            field=models.CharField(help_text='Code lettrage automatique (L-2024-0001)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='lignes',
            field=models.ManyToManyField(related_name='lettrages', to='api.ligneecriture'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='is_divers',
            field=models.BooleanField(db_index=True, default=False, help_text="Lot provenant d'une commande diverse"),
        ),
        migrations.DeleteModel(
            name='LettrageLignes',
        ),
    ]
