# Generated by Django 6.0.3 on 2026-05-10 18:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_create_lettrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='is_divers',
            field=models.BooleanField(default=False, help_text='Fournisseur utilisé pour les achats divers (produits sans lien avec le stock normal)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('LOC', 'Locale'), ('DIR', 'Directe'), ('DIV', 'Divers')], default='LOC', help_text='Type de commande (Locale, Directe ou Divers)', max_length=3),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='code',
            field=models.CharField(help_text='Code lettrage automatique (L-2024-0001)', max_length=20, unique=True),
        ),
        
        # Utilisation de SeparateDatabaseAndState pour gérer le changement de ManyToManyField (through -> non-through)
        # Cela évite l'erreur "ValueError: Cannot alter field ... add or remove through="
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='lettrage',
                    name='lignes',
                ),
                migrations.AddField(
                    model_name='lettrage',
                    name='lignes',
                    field=models.ManyToManyField(related_name='lettrages', to='api.ligneecriture'),
                ),
            ],
            database_operations=[
                # 1. Supprimer l'ancienne table de liaison (manuelle via through)
                migrations.RunSQL("DROP TABLE IF EXISTS api_lettrage_lignes CASCADE;"),
                # 2. Créer la nouvelle table de liaison (automatique)
                # On utilise RunSQL pour créer la table exactement comme Django le ferait par défaut
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE api_lettrage_lignes (
                        id bigserial NOT NULL PRIMARY KEY,
                        lettrage_id bigint NOT NULL REFERENCES api_lettrage(id) DEFERRABLE INITIALLY DEFERRED,
                        ligneecriture_id bigint NOT NULL REFERENCES api_ligneecriture(id) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT api_lettrage_lignes_lettrage_id_ligneecriture_id_key UNIQUE (lettrage_id, ligneecriture_id)
                    );
                    CREATE INDEX api_lettrage_lignes_lettrage_id_idx ON api_lettrage_lignes (lettrage_id);
                    CREATE INDEX api_lettrage_lignes_ligneecriture_id_idx ON api_lettrage_lignes (ligneecriture_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS api_lettrage_lignes CASCADE;"
                ),
            ]
        ),

        migrations.AlterField(
            model_name='lettrage',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='is_divers',
            field=models.BooleanField(db_index=True, default=False, help_text="Lot provenant d'une commande diverse"),
        ),
        migrations.DeleteModel(
            name='LettrageLignes',
        ),
    ]
