# Generated by Django 6.0.3 on 2026-05-14 20:58

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_telegramlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dci_reference',
            field=models.ForeignKey(blank=True, help_text='DCI de référence pour la substitution générique (ex: Paracétamol)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_generiques', to='api.substance'),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_generic',
            field=models.BooleanField(default=False, help_text='Ce produit est un générique (prix généralement plus bas)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='produit_reference',
            field=models.ForeignKey(blank=True, help_text='Produit de marque/origine de référence (si ce produit est un générique)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generiques', to='api.produit'),
        ),
        migrations.CreateModel(
            name='MedicamentReference',
            fields=[
                ('cis', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code CIS')),
                ('nom', models.CharField(db_index=True, max_length=500)),
                ('forme', models.CharField(blank=True, max_length=255, null=True)),
                ('substances', models.TextField(blank=True, help_text='Liste des substances actives séparées par des points-virgules', null=True)),
            ],
            options={
                'verbose_name': 'Référence Médicament',
                'verbose_name_plural': 'Références Médicaments',
                'ordering': ['nom'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='med_ref_nom_trgm_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
