# Generated by Django 5.2.5 on 2026-05-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_produit_dci_reference_produit_is_generic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='contre_indications',
            field=models.TextField(blank=True, help_text='Contre-indications et avertissements (source OpenFDA)', null=True),
        ),
    ]
