# Generated by Django 5.2.14 on 2026-05-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_substance_contre_indications'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='monthly_report_day',
            field=models.IntegerField(default=1, help_text="Jour du mois pour l'envoi du rapport (1-28)"),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='monthly_report_enabled',
            field=models.BooleanField(default=True, help_text='Activer le rapport automatique mensuel'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_comparison',
            field=models.BooleanField(default=False, help_text='Inclure la comparaison avec le mois précédent'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_debt',
            field=models.BooleanField(default=True, help_text='Inclire la dette clients et fournisseurs'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_expiration',
            field=models.BooleanField(default=True, help_text='Inclure les alertes péremption'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_financial_summary',
            field=models.BooleanField(default=True, help_text='Inclure le résumé financier'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_margin',
            field=models.BooleanField(default=True, help_text='Inclure les marges réalisées'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_ruptures',
            field=models.BooleanField(default=True, help_text='Inclure les ruptures de stock'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_sales',
            field=models.BooleanField(default=True, help_text='Inclure les ventes du mois'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_slow_moving',
            field=models.BooleanField(default=True, help_text='Inclure les produits à rotation lente'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_stock_health',
            field=models.BooleanField(default=True, help_text='Inclure le score de santé du stock'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_include_top_products',
            field=models.BooleanField(default=True, help_text='Inclure le top 10 des produits vendus'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_recipients_email',
            field=models.TextField(blank=True, default='', help_text='Emails destinataires (séparés par des virgules)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_send_telegram',
            field=models.BooleanField(default=False, help_text='Envoyer aussi via Telegram'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='report_send_whatsapp',
            field=models.BooleanField(default=False, help_text='Envoyer aussi via WhatsApp'),
        ),
    ]
