# Generated by Django 5.2.5 on 2026-06-02 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_avoir_stock_decharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postecaisse',
            name='fond_de_caisse',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Fond de caisse initial saisi à l'ouverture", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUG', 'Bug / Erreur'), ('FEATURE', 'Nouvelle fonctionnalité'), ('IMPROVEMENT', 'Amélioration'), ('QUESTION', 'Question'), ('OTHER', 'Autre')], default='OTHER', help_text='Catégorie du feedback', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', help_text='Priorité du feedback', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='NEW', help_text='Statut du feedback', max_length=20)),
                ('subject', models.CharField(help_text='Sujet du feedback', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du feedback')),
                ('screenshot', models.ImageField(blank=True, help_text="Capture d'écran optionnelle", null=True, upload_to='feedback/screenshots/')),
                ('page_url', models.CharField(blank=True, help_text='URL de la page concernée', max_length=500)),
                ('browser_info', models.TextField(blank=True, help_text='Informations sur le navigateur')),
                ('admin_response', models.TextField(blank=True, help_text="Réponse de l'administrateur")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fond_de_caisse', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('montant_total_encaisse', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouvert_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_caisses', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.postecaisse')),
            ],
            options={
                'verbose_name': 'Session de Caisse',
                'verbose_name_plural': 'Sessions de Caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
    ]
