# Generated by Django 5.2.5 on 2026-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_squashed_0195_add_taux_change_actif_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='delai_couverture_jours',
            field=models.IntegerField(default=30, help_text='Autonomie de stock souhaitée après réception (jours de vente à couvrir).'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='delai_livraison_jours',
            field=models.IntegerField(default=7, help_text='Délai moyen entre validation de la commande et réception physique (jours).'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='marge_retard_jours',
            field=models.IntegerField(default=2, help_text='Marge de sécurité pour les retards de livraison fréquents (jours).'),
        ),
    ]
