# Generated by Django 5.2.5 on 2026-06-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_remove_fournisseur_couverture_add_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderschedule',
            name='active_month_days',
            field=models.JSONField(default=list, help_text='List of active month days [1-31]'),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='active_days',
            field=models.JSONField(default=list, help_text='List of active weekdays [0-6]'),
        ),
    ]
