# Generated by Django 5.2.14 on 2026-06-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_add_order_schedule_month_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='backup_interval_minutes',
            field=models.IntegerField(default=1440, help_text='Intervalle entre deux sauvegardes automatiques (en minutes, ex: 60=toutes les heures, 1440=quotidien, 10080=hebdomadaire)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='backup_retention_count',
            field=models.IntegerField(default=30, help_text='Nombre maximal de sauvegardes à conserver'),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='backup_enabled',
            field=models.BooleanField(default=True, help_text='Activer la sauvegarde automatique'),
        ),
    ]
