# Generated by Django 5.2.15 on 2026-06-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_add_backup_interval_and_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='cloud_backup_access_key',
            field=models.CharField(blank=True, default='', help_text='Access Key ID S3', max_length=200),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='cloud_backup_bucket',
            field=models.CharField(blank=True, default='', help_text='Nom du bucket S3', max_length=200),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='cloud_backup_enabled',
            field=models.BooleanField(default=False, help_text='Activer la sauvegarde vers le cloud (S3-compatible)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='cloud_backup_endpoint',
            field=models.CharField(blank=True, default='', help_text='Endpoint S3 (ex: s3.amazonaws.com, s3.wasabisys.com, s3.fr-par.scw.cloud)', max_length=500),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='cloud_backup_path_prefix',
            field=models.CharField(blank=True, default='pharmacie-backups/', help_text='Préfixe de chemin dans le bucket (ex: pharmacie-backups/)', max_length=200),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='cloud_backup_region',
            field=models.CharField(blank=True, default='', help_text='Région S3 (ex: us-east-1, eu-west-1, fr-par — laisser vide si non requis)', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='cloud_backup_secret_key',
            field=models.CharField(blank=True, default='', help_text='Secret Access Key S3', max_length=200),
        ),
    ]
