# Generated by Django 5.2.15 on 2026-07-03 20:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_add_version_to_inventaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationobjectifs',
            name='coefficient_marge',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.40'), help_text='Coefficient multiplicateur moyen (prix de vente = coût × coefficient). Défaut 1.40. Taux de marge = (coeff - 1) / coeff.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))]),
        ),
        migrations.AddField(
            model_name='configurationobjectifs',
            name='marge_objectif_mensuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Objectif de marge brute mensuelle saisi par le pharmacien. Le CA nécessaire est calculé automatiquement via le coefficient.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='objectifcommercial',
            name='marge_objectif',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Objectif de marge brute pour cette période (saisi par le pharmacien)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='objectifcommercial',
            name='ca_objectif',
            field=models.DecimalField(decimal_places=2, help_text='CA objectif calculé automatiquement : marge / taux_marge, où taux_marge = (coeff - 1) / coeff', max_digits=15),
        ),
    ]
