# Generated by Django 6.0.3 on 2026-07-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_add_disabled_payment_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='custom_payment_modes',
            field=models.JSONField(blank=True, default=list, help_text="Modes de paiement personnalisés (ex: [{'value': 'paypal', 'label': 'PayPal'}])"),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='mode_paiement',
            field=models.CharField(max_length=50),
        ),
    ]
