# Generated by Django 6.0.3 on 2026-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0215_create_lettrage_lignes_if_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_terminal_account',
            field=models.BooleanField(default=False, help_text="Si coché, ce compte représente un poste de vente physique. Le vrai vendeur doit s'identifier par mot de passe à chaque vente.", verbose_name='Compte poste de vente partagé'),
        ),
    ]
