# Generated by Django 6.0.3 on 2026-07-15 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def creer_postes_vente_et_migrer_factures(apps, schema_editor):
    """Crée un PosteVente par PosteCaisse ayant une session active,
    et rattache les factures existantes à ce PosteVente."""
    PosteCaisse = apps.get_model('api', 'PosteCaisse')
    PosteVente = apps.get_model('api', 'PosteVente')
    Facture = apps.get_model('api', 'Facture')
    now = django.utils.timezone.now()

    for caisse in PosteCaisse.objects.all():
        date_ouv = getattr(caisse, 'date_ouverture', None) or now
        # Évite les doublons si la migration est ré-exécutée
        existing = PosteVente.objects.filter(caisse=caisse).first()
        if existing:
            continue
        # Crée un poste de vente actif si la caisse était ouverte
        if getattr(caisse, 'est_ouvert', False):
            poste = PosteVente.objects.create(
                nom=caisse.nom,
                caisse=caisse,
                vendeur_id=getattr(caisse, 'ouvert_par_id', None),
                fond_de_caisse=getattr(caisse, 'fond_de_caisse', None),
                date_ouverture=date_ouv,
                est_actif=True,
            )
            # Rattache les factures de cette caisse au poste de vente
            Facture.objects.filter(poste_caisse=caisse).update(poste_vente=poste)
        else:
            # Rattache les factures à un poste de vente historique fermé
            if Facture.objects.filter(poste_caisse=caisse).exists():
                poste = PosteVente.objects.create(
                    nom=caisse.nom,
                    caisse=caisse,
                    vendeur_id=getattr(caisse, 'ouvert_par_id', None),
                    fond_de_caisse=getattr(caisse, 'fond_de_caisse', None),
                    date_ouverture=date_ouv,
                    date_fermeture=now,
                    est_actif=False,
                )
                Facture.objects.filter(poste_caisse=caisse).update(poste_vente=poste)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_profile_is_terminal_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Créer la table PosteVente
        migrations.CreateModel(
            name='PosteVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Point de vente', help_text='Nom du point de vente', max_length=100)),
                ('fond_de_caisse', models.DecimalField(blank=True, decimal_places=2, help_text="Fond de caisse initial saisi à l'ouverture", max_digits=12, null=True)),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('montant_total_encaisse', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_vente', to='api.postecaisse')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_vente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poste de Vente',
                'verbose_name_plural': 'Postes de Vente',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='poste_vente',
            field=models.ForeignKey(blank=True, help_text='Poste de vente (session) ayant généré cette facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='api.postevente'),
        ),
        # 2. Migrer les données
        migrations.RunPython(creer_postes_vente_et_migrer_factures, reverse_migration),
        # 3. Supprimer les champs de session de PosteCaisse
        migrations.RemoveField(
            model_name='postecaisse',
            name='date_ouverture',
        ),
        migrations.RemoveField(
            model_name='postecaisse',
            name='est_ouvert',
        ),
        migrations.RemoveField(
            model_name='postecaisse',
            name='fond_de_caisse',
        ),
        migrations.RemoveField(
            model_name='postecaisse',
            name='ouvert_par',
        ),
        # 4. Mettre à jour les options des modèles
        migrations.AlterModelOptions(
            name='postecaisse',
            options={'ordering': ['nom'], 'verbose_name': 'Caisse', 'verbose_name_plural': 'Caisses'},
        ),
        migrations.AlterModelOptions(
            name='sessioncaisse',
            options={'managed': False, 'ordering': ['-date_ouverture'], 'verbose_name': 'Session de Caisse (historique)', 'verbose_name_plural': 'Sessions de Caisse (historique)'},
        ),
        migrations.AlterField(
            model_name='facture',
            name='poste_caisse',
            field=models.ForeignKey(blank=True, help_text='Caisse physique auquel cette facture est assignée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_assignees', to='api.postecaisse'),
        ),
    ]
