# Generated by Django 5.2.15 on 2026-07-15 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_alter_postecaisse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevente',
            name='caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_vente', to='api.postecaisse'),
        ),
        migrations.AlterField(
            model_name='postevente',
            name='date_ouverture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postevente',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
    ]
