# Generated by Django 5.2.15 on 2026-07-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0220_add_montant_verse_rendu_to_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='mode_imposition',
            field=models.CharField(choices=[('MARGE_ADMINISTREE', 'Marge Administrée (14% sur marge brute)'), ('DROIT_COMMUN', "Droit Commun (sur chiffre d'affaires global)")], default='MARGE_ADMINISTREE', help_text="Mode d'imposition : marge administrée (pharmacie) ou droit commun", max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='regime_fiscal',
            field=models.CharField(choices=[('REEL', 'Régime du Réel'), ('SIMPLIFIE', 'Régime Simplifié')], default='REEL', help_text='Régime fiscal de la pharmacie', max_length=15),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='taux_accompte_reel',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text="Taux d'accompte mensuel sur CA en régime Réel (2% par défaut)", max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='taux_accompte_simplifie',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Taux d'accompte mensuel sur CA en régime Simplifié (5% par défaut)", max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='taux_cac',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Taux CAC (Centimes Additionnels Communaux) appliqué sur l'accompte (10% par défaut)", max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='taux_marge_brute',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Taux sur marge brute en mode marge administrée (14% par défaut)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='taux_precompte_reel',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Taux de précompte sur achats en régime Réel (1% par défaut)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='taux_precompte_simplifie',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Taux de précompte sur achats en régime Simplifié (3-5%, 5% par défaut)', max_digits=5),
        ),
    ]
