# Generated by Django 5.2.16 on 2026-07-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_shiftconfig_team_mode_shiftconfig_team_rotation_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='phone2',
            field=models.CharField(blank=True, default='', help_text='Second numéro de téléphone', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='dormant_stock_days',
            field=models.IntegerField(default=90, help_text='Seuil pour considérer un stock comme dormant (sans vente depuis X jours)'),
        ),
    ]
