# Generated by Django 5.2.16 on 2026-08-13 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_historiquetransformation_reversed_reversed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('PROFESSIONNEL', 'Professionnel')], db_index=True, default='PARTICULIER', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Client actif (visible dans les recherches)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Commande active (non supprimée dans la corbeille)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('PREP', 'En préparation'), ('ATT', 'En attente'), ('CLOT', 'Clôturée')], db_index=True, default='PREP', max_length=10),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Fournisseur actif (visible dans les recherches)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Produit actif (visible dans les recherches)'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['poste_caisse', 'status', '-date'], name='facture_poste_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['created_by', '-date'], name='facture_creator_date_idx'),
        ),
    ]
