# Generated by Django 5.2.5 on 2026-08-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_commande_mise_en_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paye_a_la_cloture',
            field=models.BooleanField(default=False, help_text='Achat payé intégralement au comptant (certains grossistes ne font pas crédit). Utilisé uniquement si is_mise_en_place=True : un paiement fournisseur pour le montant total est enregistré automatiquement à la clôture de la commande.'),
        ),
    ]
