# Generated by Django 5.2.5 on 2026-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0233_commande_paye_a_la_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_validate_sales',
            field=models.BooleanField(default=False, verbose_name='Valider les ventes'),
        ),
    ]
