# Generated by Django 5.2.17 on 2026-09-01 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_profile_can_create_client_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['poste_caisse', 'status', '-date'], name='facture_poste_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['created_by', '-date'], name='facture_creator_date_idx'),
        ),
    ]
