# Generated by Django 5.2.17 on 2026-09-01 22:10
# Redondante avec 0239 (qui crée déjà ces index en CONCURRENTLY IF NOT EXISTS).
# Rendue no-op pour éviter les erreurs de duplication.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_profile_can_create_client_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
