# Generated by Django 5.2.17 on 2026-09-06 00:22

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0250_facture_facture_poste_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='produit',
                    name='cip4',
                    field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_produit ADD COLUMN IF NOT EXISTS cip4 varchar(20) NULL",
                    reverse_sql="ALTER TABLE api_produit DROP COLUMN IF EXISTS cip4",
                ),
                migrations.RunSQL(
                    sql="CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS produit_cip4_unique ON api_produit (cip4) WHERE cip4 IS NOT NULL",
                    reverse_sql="DROP INDEX IF EXISTS produit_cip4_unique",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='produit',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['cip4'], name='produit_cip4_trgm_idx', opclasses=['gin_trgm_ops']),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS produit_cip4_trgm_idx ON api_produit USING gin (cip4 gin_trgm_ops)",
                    reverse_sql="DROP INDEX IF EXISTS produit_cip4_trgm_idx",
                ),
            ],
        ),
    ]
