# Generated by Django 5.2.17 on 2026-09-07 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0251_produit_cip4_facture_facture_poste_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_cash_totals',
            field=models.BooleanField(default=True, verbose_name='Voir les totaux du journal de caisse'),
        ),
    ]
