# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0254_facture_facture_poste_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postecaisse',
            name='actif',
            field=models.BooleanField(default=True, help_text="False = caisse désactivée (masquée à l'ouverture, historique conservé)"),
        ),
    ]
