# Generated by Django 5.2.17 on 2026-09-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0258_remove_pharmacist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacysettings',
            name='show_pharmacist_on_documents',
            field=models.BooleanField(default=False, help_text='Afficher le nom du pharmacien (issu de la licence) sur les tickets et factures'),
        ),
    ]
