# Generated by Django 5.2.17 on 2026-10-01 16:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0260_seed_defauts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoirclient',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_factures_impayees',
            field=models.IntegerField(default=0, help_text='Nombre de factures non réglées (denormalisé)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Factures impayées'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pending_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remise en % acquise pour la prochaine vente', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='plafond',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('-1.00'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='points_fidelite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='taux_couverture',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de couverture assurance en % (0-100) pour tiers payant', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_reel',
            field=models.DecimalField(decimal_places=2, help_text='Montant réellement compté en caisse', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_entrees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Entrées de caisse hors ventes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_sorties',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sorties de caisse', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='delai_paiement_negocie_jours',
            field=models.IntegerField(blank=True, help_text='Délai de paiement négocié en jours pour cette commande (utilisé uniquement si is_mise_en_place=True, remplace le délai standard du fournisseur).', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='frais_coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='taux_change',
            field=models.DecimalField(decimal_places=3, default=655.957, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='price_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='prix_euro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='quantity',
            field=models.IntegerField(help_text='Quantité commandée et payée', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='taux_marge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux de marge appliqué (ex: 1.60)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='unites_gratuites',
            field=models.IntegerField(default=0, help_text='Unités gratuites reçues (ex: promotion 3+1)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='couponmonnaie',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_fidelite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_rendu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Monnaie rendue au client (pour ticket de caisse)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Montant total reçu du client (pour ticket de caisse)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='part_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part à payer par le client (Tiers Payant)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='points_fidelite_gagnes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='points_fidelite_utilises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=19.25, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Montant de la remise unitaire', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='free_quantity',
            field=models.IntegerField(default=0, help_text='Unités gratuites (Promotion)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='treatment_duration_days',
            field=models.IntegerField(blank=True, help_text='Durée du traitement en jours pour ce produit (pour rappels chroniques)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TVA applicable à cette ligne', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat du lot", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='quantity',
            field=models.IntegerField(help_text='Quantité prélevée de ce lot', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='quantity_free',
            field=models.IntegerField(default=0, help_text='Part de la quantité prélevée sur les unités gratuites (UG) du lot', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='delai_livraison_jours',
            field=models.IntegerField(default=7, help_text='Délai moyen entre validation de la commande et réception physique (jours).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='delai_paiement_jours',
            field=models.IntegerField(default=0, help_text='Délai de paiement accordé en jours après fin de tranche/facture (ex: 10, 15). 0 = au comptant.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='marge_retard_jours',
            field=models.IntegerField(default=2, help_text='Marge de sécurité pour les retards de livraison fréquents (jours).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='periode_releve_jours',
            field=models.IntegerField(default=10, help_text="Durée en jours d'une tranche de relevé (ex: 10 = du 1-10, 11-20, 21-31). Utilisé uniquement si type_reglement=RELEVE.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='quantite_destination',
            field=models.IntegerField(help_text='Quantité obtenue (destination)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='quantite_source',
            field=models.IntegerField(help_text='Quantité transformée (source)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de retour', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ligneavoirclient',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ligneavoirclient',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ligneavoirclient',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='pmp_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='quantite_physique',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lotsequence',
            name='last_number',
            field=models.IntegerField(default=0, help_text='Dernier numéro de séquence utilisé', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loyaltyhistory',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur monétaire (FCFA) si applicable', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='amount_per_point',
            field=models.DecimalField(decimal_places=0, default=1000, help_text='Montant en FCFA pour gagner 1 point', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='auto_reward_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de remise auto', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='auto_reward_threshold',
            field=models.IntegerField(default=0, help_text='Nombre de points pour déclencher la récompense auto (0=désactivé)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='point_value',
            field=models.DecimalField(decimal_places=0, default=10, help_text="Valeur d'un point en FCFA", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='analysis_period_days',
            field=models.IntegerField(default=30, help_text="Période d'analyse des ventes pour calculer la VMD (jours).", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='auto_reception_delay',
            field=models.IntegerField(default=0, help_text='Minutes before auto-reception', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='delai_couverture_jours',
            field=models.IntegerField(default=30, help_text='Autonomie de stock souhaitée après réception (jours de vente à couvrir). Peut varier pour un même fournisseur.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='frequency_weeks',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='min_items',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='print_copies',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='auto_logout_timeout',
            field=models.IntegerField(default=15, help_text="Délai d'inactivité avant déconnexion automatique (en minutes, 0 pour désactiver)", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='availability_weight',
            field=models.IntegerField(default=60, help_text='Poids de la disponibilité dans le score de santé global (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='backup_interval_minutes',
            field=models.IntegerField(default=1440, help_text='Intervalle entre deux sauvegardes automatiques (en minutes, ex: 60=toutes les heures, 1440=quotidien, 10080=hebdomadaire)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='backup_retention_count',
            field=models.IntegerField(default=30, help_text='Nombre maximal de sauvegardes à conserver', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='coefficient_direct_commande',
            field=models.DecimalField(decimal_places=2, default=1.35, help_text='Coefficient multiplicateur pour les commandes directes (Euro -> Revient)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='critical_stock_days',
            field=models.IntegerField(default=7, help_text='Seuil stock critique (jours)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='debt_alert_threshold',
            field=models.DecimalField(decimal_places=0, default=100000, help_text="Seuil d'alerte pour la dette client (FCFA)", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='dormant_stock_days',
            field=models.IntegerField(default=90, help_text='Seuil pour considérer un stock comme dormant (sans vente depuis X jours)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='good_coverage_max_days',
            field=models.IntegerField(default=90, help_text='Couverture stock max (jours) pour score santé', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='good_coverage_min_days',
            field=models.IntegerField(default=15, help_text='Couverture stock min (jours) pour score santé', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='imminent_rupture_days',
            field=models.IntegerField(default=3, help_text='Seuil rupture imminente (jours)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='low_stock_threshold_days',
            field=models.IntegerField(default=15, help_text="Seuil d'alerte stock bas (en jours de couverture)", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='min_margin_threshold',
            field=models.DecimalField(decimal_places=2, default=1.34, help_text='Taux de marge minimum acceptable pour les commandes (ex: 1.34 = 25% de marge)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='monthly_report_day',
            field=models.IntegerField(default=1, help_text="Jour du mois pour l'envoi du rapport (1-28)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='perf_alert_hour',
            field=models.IntegerField(default=14, help_text="Heure à partir de laquelle l'alerte performance se déclenche", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='perf_drop_threshold',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Seuil de baisse CA pour alerte (0.7 = 30% de baisse)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='rotation_weight',
            field=models.IntegerField(default=40, help_text='Poids de la rotation dans le score de santé global (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='shortage_alert_threshold',
            field=models.IntegerField(default=10, help_text='Nb de produits en rupture avant alerte', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_accompte_reel',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text="Taux d'accompte mensuel sur CA en régime Réel (2% par défaut)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_accompte_simplifie',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Taux d'accompte mensuel sur CA en régime Simplifié (5% par défaut)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_cac',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Taux CAC (Centimes Additionnels Communaux) appliqué sur l'accompte (10% par défaut)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_change_actif',
            field=models.DecimalField(decimal_places=3, default=655.957, help_text='Taux de change actif pour les commandes directes (Euro -> FCFA). Source de vérité unique.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_marge_brute',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Taux sur marge brute en mode marge administrée (14% par défaut)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_precompte_reel',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Taux de précompte sur achats en régime Réel (1% par défaut)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_precompte_simplifie',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Taux de précompte sur achats en régime Simplifié (3-5%, 5% par défaut)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='traffic_analysis_days',
            field=models.IntegerField(default=30, help_text="Fenêtre d'analyse du trafic horaire (jours)", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='postevente',
            name='fond_de_caisse',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Fond de caisse initial saisi à l'ouverture", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='postevente',
            name='montant_total_encaisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='capacite_rayon',
            field=models.IntegerField(default=0, help_text="Capacité maximale d'exposition en rayon", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='default_treatment_days',
            field=models.IntegerField(default=30, help_text='Durée par défaut du traitement en jours (utilisé pour les rappels)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='min_rayon',
            field=models.IntegerField(default=0, help_text='Seuil de déclenchement du réapprovisionnement', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pmp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix Moyen Pondéré', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='rotation_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_alert',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_maximum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_minimum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_reserve',
            field=models.IntegerField(default=0, help_text='Quantité totale en réserve (stock tampon)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='promis',
            name='quantite',
            field=models.IntegerField(help_text='Quantité promise au client', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='buy_quantity',
            field=models.IntegerField(default=1, help_text='Quantité minimale à acheter pour déclencher la promo', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='get_quantity',
            field=models.IntegerField(default=0, help_text='Quantité offerte (pour Buy X Get Y)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur de la remise (en % ou en F) ou Prix Total du Pack', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='promotionpackitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantité requise dans le pack', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reapprosession',
            name='total_products',
            field=models.IntegerField(default=0, help_text='Nombre de produits distincts impactés', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reapprosession',
            name='total_units',
            field=models.IntegerField(default=0, help_text="Nombre total d'unités transférées", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='relationtransformation',
            name='ratio',
            field=models.DecimalField(decimal_places=2, help_text='Ratio de conversion (ex: 20.00 si 1 boîte = 20 détails)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='relevepaiement',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='price_cost',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire effectif (ajusté avec UG)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_free',
            field=models.IntegerField(default=0, help_text='Unités gratuites (UG)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_free_remaining',
            field=models.IntegerField(default=0, help_text='Unités gratuites restantes en rayon', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_initial',
            field=models.IntegerField(help_text='Quantité totale initiale (payée + gratuites)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_paid',
            field=models.IntegerField(default=0, help_text='Quantité payée uniquement', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_remaining',
            field=models.IntegerField(help_text='Quantité totale restante en rayon', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_reserved',
            field=models.IntegerField(default=0, help_text='Quantité en réserve pour ce lot', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de vente lors de la réception', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ticketsessionsequence',
            name='last_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tva',
            name='taux',
            field=models.DecimalField(decimal_places=2, help_text='Taux de TVA en pourcentage (ex: 19.25)', max_digits=5, unique=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
