# Generated by Django 5.2.17 on 2026-10-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0263_drop_redundant_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='last_retention_run',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la dernière exécution de la rétention des données', null=True),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_activity_days',
            field=models.PositiveIntegerField(default=365, help_text="Durée de conservation des logs d'activité (ActivityLog) en jours"),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_audit_days',
            field=models.PositiveIntegerField(default=730, help_text="Durée de conservation du journal d'audit (AuditLog) en jours"),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_draft_invoice_days',
            field=models.PositiveIntegerField(default=30, help_text='Durée de conservation des factures brouillon en jours'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_enabled',
            field=models.BooleanField(default=False, help_text='Activer la purge automatique des données anciennes (commande run_retention)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_message_log_days',
            field=models.PositiveIntegerField(default=365, help_text='Durée de conservation des journaux SMS / WhatsApp / Telegram en jours'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_mouvement_stock_days',
            field=models.PositiveIntegerField(default=1095, help_text='Durée de conservation des mouvements de stock en jours (36 mois)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_session_days',
            field=models.PositiveIntegerField(default=90, help_text='Durée de conservation des sessions Django et des logs axes en jours'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='retention_trash_days',
            field=models.PositiveIntegerField(default=90, help_text='Durée de conservation des éléments dans la corbeille (is_active=False) en jours'),
        ),
    ]
