# Generated by Django 5.2.17 on 2026-10-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0264_pharmacysettings_last_retention_run_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('INTEGRE', 'Intégré à une commande'), ('IGNORE', 'Ignoré')], default='NOUVEAU', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_besoins', to='api.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', '-created_at'], name='api_signale_statut_1c9f24_idx')],
            },
        ),
    ]
