# Generated by Django 5.2.17 on 2026-10-08 06:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_stock_obligations(apps, schema_editor):
    Produit = apps.get_model('api', 'Produit')
    Promis = apps.get_model('api', 'Promis')
    FactureProduit = apps.get_model('api', 'FactureProduit')
    FactureProduitAllocation = apps.get_model('api', 'FactureProduitAllocation')
    StockObligation = apps.get_model('api', 'StockObligation')

    # Promis existants : les promis liés à une facture n'étaient pas sortis du
    # stock sous l'ancien contrat, donc stock_applied=False. Un promis manuel
    # sans gestion de lots était quant à lui déjà réservé dans Produit.stock.
    for promis in Promis.objects.filter(
        status='ATT', is_active=True
    ).select_related('produit', 'facture').order_by('id'):
        if StockObligation.objects.filter(promis=promis, status='ATT').exists():
            continue

        facture_produit = FactureProduit.objects.filter(
            facture=promis.facture,
            produit=promis.produit,
        ).order_by('id').first() if promis.facture_id and promis.produit_id else None

        stock_applied = bool(
            not promis.facture_id
            and promis.produit
            and not promis.produit.use_lot_management
        )
        obligation = StockObligation.objects.create(
            produit=promis.produit,
            produit_nom=promis.produit.name if promis.produit else promis.produit_nom,
            facture=promis.facture,
            facture_produit=facture_produit,
            promis=promis,
            type='PROMIS',
            status='ATT',
            quantity=promis.quantite,
            quantity_remaining=promis.quantite,
            stock_applied=stock_applied,
            stock_location='RAYON',
            cost_price=(
                (promis.produit.pmp or promis.produit.cost_price)
                if promis.produit else Decimal('0')
            ),
            selling_price=facture_produit.selling_price if facture_produit else Decimal('0'),
            created_by=promis.created_by,
        )
        if facture_produit:
            FactureProduitAllocation.objects.create(
                facture_produit=facture_produit,
                stock_obligation=obligation,
                is_pending=True,
                quantity=promis.quantite,
                cost_price=obligation.cost_price,
                selling_price=obligation.selling_price,
            )

    # Déficit négatif résiduel sans promis : conserver le signal métier comme
    # dette FORCE au lieu de laisser une resynchronisation de lots l'effacer.
    for produit in Produit.objects.filter(stock__lt=0).order_by('id'):
        applied_debt = StockObligation.objects.filter(
            produit=produit,
            status='ATT',
            stock_applied=True,
            stock_location='RAYON',
        ).aggregate(total=models.Sum('quantity_remaining'))['total'] or 0
        deficit = -produit.stock - applied_debt
        if deficit <= 0:
            continue
        StockObligation.objects.create(
            produit=produit,
            produit_nom=produit.name,
            type='FORCE',
            status='ATT',
            quantity=deficit,
            quantity_remaining=deficit,
            stock_applied=True,
            stock_location='RAYON',
            cost_price=produit.pmp or produit.cost_price or Decimal('0'),
            selling_price=produit.selling_price or Decimal('0'),
            notes='Backfill migration 0266 - déficit de stock historique',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0265_signalementbesoin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduitallocation',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='Quantité facturée mais non encore rattachée à un stock physique'),
        ),
        migrations.AddField(
            model_name='promis',
            name='quantite_livree',
            field=models.IntegerField(default=0, help_text='Part du promis déjà couverte par du stock', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='StockObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(choices=[('PROMIS', 'Promis'), ('FORCE', 'Vente forcée')], max_length=10)),
                ('status', models.CharField(choices=[('ATT', 'En attente'), ('RES', 'Résolue'), ('ANN', 'Annulée')], db_index=True, default='ATT', max_length=4)),
                ('quantity', models.IntegerField(help_text='Quantité initialement non couverte', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_remaining', models.IntegerField(help_text='Quantité restant à couvrir', validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_applied', models.BooleanField(default=True, help_text='La dette restante est actuellement incluse dans le stock produit')),
                ('stock_location', models.CharField(choices=[('RAYON', 'Rayon'), ('RESERVE', 'Réserve')], default='RAYON', help_text='Compteur de stock impacté par la dette', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coût estimé au moment de la vente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix de vente au moment de la vente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_stock_obligations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_obligations', to='api.facture')),
                ('facture_produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_obligations', to='api.factureproduit')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_obligations', to='api.produit')),
                ('promis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_obligations', to='api.promis')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_stock_obligations', to=settings.AUTH_USER_MODEL)),
                ('resolved_stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_stock_obligations', to='api.stocklot')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='factureproduitallocation',
            name='stock_obligation',
            field=models.ForeignKey(blank=True, help_text='Dette de stock associée à une quantité non encore couverte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='api.stockobligation'),
        ),
        migrations.AddIndex(
            model_name='stockobligation',
            index=models.Index(fields=['produit', 'status'], name='stockobl_prod_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockobligation',
            index=models.Index(fields=['promis', 'status'], name='stockobl_promis_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockobligation',
            index=models.Index(fields=['facture', 'status'], name='stockobl_facture_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockobligation',
            index=models.Index(fields=['stock_applied', 'status'], name='stockobl_applied_status_idx'),
        ),
        migrations.RunPython(backfill_stock_obligations, migrations.RunPython.noop),
    ]
