# Generated by Django 5.2.17 on 2026-10-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_stock_obligations'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduitallocation',
            name='resolved_commande',
            field=models.ForeignKey(blank=True, help_text='Commande de réception qui a couvert cette dette', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_stock_allocations', to='api.commande'),
        ),
    ]
