# Generated by Devin on 2026-10-08

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0267_allocation_resolution_commande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockObligationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantité de dette couverte', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_free', models.IntegerField(default=0, help_text='Part couverte par les unités gratuites du lot', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_obligation_resolutions', to='api.commande')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='api.stockobligation')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_obligation_resolutions', to='api.produit')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_obligation_resolutions', to='api.stocklot')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='stockobligationresolution',
            index=models.Index(fields=['commande'], name='stockoblres_commande_idx'),
        ),
        migrations.AddIndex(
            model_name='stockobligationresolution',
            index=models.Index(fields=['obligation', 'commande'], name='stockoblres_obligation_cmd_idx'),
        ),
    ]
