# Generated by Devin on 2026-10-08

from django.db import migrations


def delete_zero_qty_resolution_movements(apps, schema_editor):
    """
    Les résolutions de dettes PROMIS/FORCE déjà appliquées au compteur
    produit créaient un MouvementStock AJUSTEMENT de quantité 0 dont le
    snapshot stock_apres cassait la lecture chaînée de l'historique.
    La trace métier reste dans StockObligationResolution : ces lignes
    d'affichage sont supprimées.
    """
    MouvementStock = apps.get_model('api', 'MouvementStock')
    MouvementStock.objects.filter(
        type_mouvement='AJUSTEMENT',
        quantite=0,
        description__regex=r'- (Promis|Vente forcée) #[0-9]+ \([0-9]+ unité\(s\)\)$',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0268_stock_obligation_resolution'),
    ]

    operations = [
        migrations.RunPython(
            delete_zero_qty_resolution_movements,
            migrations.RunPython.noop,
        ),
    ]
