# Generated by Django 5.2.17 on 2026-10-09 07:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0269_drop_zero_qty_resolution_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='taux_change',
            field=models.DecimalField(decimal_places=3, default=Decimal('655.957'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='coefficient_direct_commande',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.35'), help_text='Coefficient multiplicateur pour les commandes directes (Euro -> Revient)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='min_margin_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.34'), help_text='Taux de marge minimum acceptable pour les commandes (ex: 1.34 = 25% de marge)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='perf_drop_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Seuil de baisse CA pour alerte (0.7 = 30% de baisse)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='taux_change_actif',
            field=models.DecimalField(decimal_places=3, default=Decimal('655.957'), help_text='Taux de change actif pour les commandes directes (Euro -> FCFA). Source de vérité unique.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
