# Generated by Django 5.2.17 on 2026-10-09 19:23

from django.db import migrations, models
from django.db.models import IntegerField, Max
from django.db.models.functions import Cast, Substr


def init_document_counters(apps, schema_editor):
    """Amorce les compteurs DEV/FAC sur le max des numéros existants
    (numérotation historique basée sur l'id : DEV-XXXXXX / FAC-XXXXXX)."""
    Facture = apps.get_model('api', 'Facture')
    DocumentCounter = apps.get_model('api', 'DocumentCounter')
    for prefix in ('DEV', 'FAC'):
        max_seq = (
            Facture.objects.filter(numero_facture__regex=rf'^{prefix}-[0-9]+$')
            .annotate(seq=Cast(Substr('numero_facture', len(prefix) + 2), output_field=IntegerField()))
            .aggregate(m=Max('seq'))['m'] or 0
        )
        DocumentCounter.objects.get_or_create(name=prefix, defaults={'value': max_seq})


def reset_document_counters(apps, schema_editor):
    DocumentCounter = apps.get_model('api', 'DocumentCounter')
    DocumentCounter.objects.filter(name__in=('DEV', 'FAC')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0270_alter_commande_taux_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de documents',
            },
        ),
        migrations.RunPython(init_document_counters, reset_document_counters),
    ]
