# Generated by Django 5.2.5 on 2025-09-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_commande_total_remove_produit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
