# Generated by Django 5.2.5 on 2025-12-03 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_facture_client_name_override_alter_facture_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_initial', models.IntegerField(help_text='Quantité initiale du lot')),
                ('quantity_remaining', models.IntegerField(help_text='Quantité restante dans le lot')),
                ('price_cost', models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire", max_digits=10)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(help_text='Date de réception du lot (pour FIFO)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lot', to='api.commandeproduit')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='api.produit')),
            ],
            options={
                'ordering': ['date_reception'],
            },
        ),
        migrations.CreateModel(
            name='FactureProduitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantité prélevée de ce lot')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text="Prix d'achat du lot", max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Prix de vente', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.factureproduit')),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.stocklot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['produit', 'date_reception'], name='api_stocklo_produit_f82978_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['produit', 'quantity_remaining'], name='api_stocklo_produit_315126_idx'),
        ),
    ]
