# Generated by Django 5.2.5 on 2025-12-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_invoicesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_rayons', to='api.rayon', verbose_name='Rayon Parent'),
        ),
    ]
