# Generated by Django 5.2.5 on 2025-12-31 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_factureproduit_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneavoir',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique retourné (si applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='api.stocklot'),
        ),
    ]
