# Generated by Django 5.2.5 on 2026-01-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_stock_lot_to_inventaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='centralized_cash_register',
            field=models.BooleanField(default=False, help_text='Activer le mode Caisse Centralisée'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_cash_out',
            field=models.BooleanField(default=True, help_text='Autorisé à encaisser (si mode centralisé actif)'),
        ),
    ]
