# Generated by Django 5.2.5 on 2026-01-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_niu_registre_commerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la pharmacie', null=True, upload_to='pharmacy_logos/'),
        ),
    ]
