# Generated by Django 5.2.5 on 2026-01-20 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_facture_type_produit_last_purchase_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ['-date'], 'verbose_name': 'Cl├┤ture de caisse', 'verbose_name_plural': 'Cl├┤tures de caisse'},
        ),
        migrations.AlterModelOptions(
            name='loyaltysetting',
            options={'verbose_name': 'Configuration Fid├®lit├®', 'verbose_name_plural': 'Configuration Fid├®lit├®'},
        ),
        migrations.AlterModelOptions(
            name='pharmacysettings',
            options={'verbose_name': 'Param├¿tres Pharmacie', 'verbose_name_plural': 'Param├¿tres Pharmacie'},
        ),
        migrations.RemoveField(
            model_name='facture',
            name='type',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='last_purchase_price',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='public_price',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Cr├®ation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('EXPORT', 'Export'), ('OTHER', 'Autre'), ('STOCK_ADJ', 'Ajustement stock'), ('PRICE_CHG', 'Changement prix'), ('CLOTURE', 'Cl├┤ture caisse'), ('INV_CANCEL', 'Annulation facture'), ('INV_DEL', 'Suppression facture'), ('INV_VALID', 'Validation facture'), ('INV_CRE', 'Cr├®ation inventaire'), ('INV_VAL', 'Validation inventaire')], max_length=10),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Valid├®e')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='type_avoir',
            field=models.CharField(choices=[('PERIME', 'Produit p├®rim├®'), ('AVARIE', 'Produit avari├®'), ('NON_FACTURE', 'Livr├® non factur├®'), ('ERREUR', 'Erreur de livraison'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Esp├¿ces'), ('cheque', 'Ch├¿que'), ('carte', 'Carte'), ('virement', 'Virement'), ('om', 'Orange Money'), ('momo', 'Mobile Money'), ('en_compte', 'En compte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='part_patient',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part pay├®e par le patient (tiers payant)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('completee', 'Compl├®t├®e'), ('annulee', 'Annul├®e')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_loyalty_member',
            field=models.BooleanField(default=True, help_text='Si activ├®, ce client participe au programme de fid├®lit├®'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le num├®ro de t├®l├®phone doit ├¬tre au format: '+999999999'. Jusqu'├á 15 chiffres autoris├®s.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='remise_automatique',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage de remise automatique (0-100%) appliqu├® ├á chaque vente', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise automatique (%)'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='date_debut',
            field=models.DateTimeField(blank=True, help_text='D├®but de la p├®riode de cl├┤ture', null=True),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Fin de la p├®riode de cl├┤ture', null=True),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='details_paiement',
            field=models.JSONField(blank=True, default=dict, help_text='D├®tails par mode de paiement'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='ecart_caisse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='├ëcart entre r├®el et th├®orique', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_reel',
            field=models.DecimalField(decimal_places=2, help_text='Montant r├®ellement compt├® en caisse', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_theorique',
            field=models.DecimalField(decimal_places=2, help_text='Montant th├®orique calcul├®', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='observation',
            field=models.TextField(blank=True, help_text='Notes ou observations sur la cl├┤ture', null=True),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_entrees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Entr├®es de caisse hors ventes', max_digits=12),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de cl├┤ture'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('PREP', 'En pr├®paration'), ('ATT', 'En attente'), ('CLOT', 'Cl├┤tur├®e')], default='PREP', max_length=4),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='quantity',
            field=models.IntegerField(help_text='Quantit├® command├®e et pay├®e'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='unites_gratuites',
            field=models.IntegerField(default=0, help_text='Unit├®s gratuites re├ºues (ex: promotion 3+1)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a cr├®├® la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='part_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part ├á payer par le client (Tiers Payant)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('BROU', 'Brouillon'), ('PROF', 'Proforma'), ('VAL', 'Valid├®e'), ('PAY', 'Pay├®e'), ('ANN', 'Annul├®e')], default='BROU', max_length=4),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot sp├®cifique choisi manuellement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='factureproduit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TVA applicable ├á cette ligne (copi├®e du produit lors de la cr├®ation)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='factureproduitallocation',
            name='quantity',
            field=models.IntegerField(help_text='Quantit├® pr├®lev├®e de ce lot'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le num├®ro de t├®l├®phone doit ├¬tre au format: '+999999999'. Jusqu'├á 15 chiffres autoris├®s.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='produit_destination_nom',
            field=models.CharField(blank=True, help_text='Nom du produit destination sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='produit_source_nom',
            field=models.CharField(blank=True, help_text='Nom du produit source sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='quantite_destination',
            field=models.IntegerField(help_text='Quantit├® obtenue (destination)'),
        ),
        migrations.AlterField(
            model_name='historiquetransformation',
            name='quantite_source',
            field=models.IntegerField(help_text='Quantit├® transform├®e (source)'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Valid├®e')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='centralized_cash_register',
            field=models.BooleanField(default=False, help_text='Activer le mode Caisse Centralis├®e'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='company_address',
            field=models.TextField(default="Adresse de l'entreprise\nT├®l├®phone: 00 00 00 00 00"),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='company_name',
            field=models.CharField(default='Ma Soci├®t├®', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='header_layout',
            field=models.CharField(choices=[('split', 'S├®par├® (Logo Gauche / Info Droite)'), ('left', 'Tout ├á Gauche'), ('center', 'Tout Centr├®'), ('right', 'Tout ├á Droite')], default='split', max_length=20),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot sp├®cifique retourn├® (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Lot sp├®cifique compt├® (si inventaire par lot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires', to='api.stocklot'),
        ),
        migrations.AlterField(
            model_name='lotsequence',
            name='last_number',
            field=models.IntegerField(default=0, help_text='Dernier num├®ro de s├®quence utilis├®'),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='auto_reward_threshold',
            field=models.IntegerField(default=0, help_text='Nombre de points pour d├®clencher la r├®compense auto (0=d├®sactiv├®)'),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='motif',
            field=models.CharField(help_text='Ex: Electricit├®, Carburant, etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='type',
            field=models.CharField(choices=[('ENTREE', 'Entr├®e'), ('SORTIE', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(help_text='Quantit├® mouvement├®e (positive ou n├®gative)'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='stock_apres',
            field=models.IntegerField(blank=True, help_text='Stock apr├¿s mouvement (snapshot)', null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entr├®e (Commande)'), ('SORTIE', 'Sortie (Vente)'), ('RETOUR', 'Retour (Annulation)'), ('AJUSTEMENT', 'Ajustement Inventaire'), ('TRANSFORMATION_ENTREE', 'Transformation (Entr├®e)'), ('TRANSFORMATION_SORTIE', 'Transformation (Sortie)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordonnancier',
            name='prescripteur_nom',
            field=models.CharField(help_text='Nom du m├®decin prescripteur', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='niu',
            field=models.CharField(blank=True, default='', help_text="Num├®ro d'Identification Unique (14-15 caract├¿res)", max_length=15),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dernier_achat',
            field=models.DateField(blank=True, help_text='Date du dernier achat (r├®ception de commande)', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dernier_vente',
            field=models.DateField(blank=True, help_text='Date de la derni├¿re vente', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pmp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix Moyen Pond├®r├®', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='requires_prescription',
            field=models.BooleanField(default=False, help_text='Ce produit n├®cessite une ordonnance'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='surveillance_category',
            field=models.CharField(choices=[('NONE', 'Aucune'), ('STANDARD', 'Surveillance standard'), ('RENFORCEE', 'Surveillance renforc├®e')], default='NONE', help_text='Cat├®gorie de surveillance du m├®dicament', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='use_lot_management',
            field=models.BooleanField(default=True, help_text='Activer la gestion par lots FIFO pour ce produit (recommand├® pour tra├ºabilit├®)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_cash_out',
            field=models.BooleanField(default=True, help_text='Autoris├® ├á encaisser (si mode centralis├® actif)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_close_commande',
            field=models.BooleanField(default=False, verbose_name='Cl├┤turer des commandes'),
        ),
        migrations.AlterField(
            model_name='promis',
            name='client_phone',
            field=models.CharField(blank=True, help_text='T├®l├®phone du client', max_length=20),
        ),
        migrations.AlterField(
            model_name='promis',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='promis',
            name='quantite',
            field=models.IntegerField(help_text='Quantit├® promise au client'),
        ),
        migrations.AlterField(
            model_name='promis',
            name='status',
            field=models.CharField(choices=[('ATT', 'En attente'), ('DEL', 'D├®livr├®'), ('ANN', 'Annul├®')], default='ATT', max_length=4),
        ),
        migrations.AlterField(
            model_name='relationtransformation',
            name='produit_destination',
            field=models.ForeignKey(help_text='Produit r├®sultant (ex: DETAIL)', on_delete=django.db.models.deletion.CASCADE, related_name='transformations_destination', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='relationtransformation',
            name='produit_source',
            field=models.ForeignKey(help_text='Produit ├á transformer (ex: BOITE)', on_delete=django.db.models.deletion.CASCADE, related_name='transformations_source', to='api.produit'),
        ),
        migrations.AlterField(
            model_name='relationtransformation',
            name='ratio',
            field=models.DecimalField(decimal_places=2, help_text='Ratio de conversion (ex: 20.00 si 1 bo├«te = 20 d├®tails)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_after',
            field=models.IntegerField(help_text='Stock apr├¿s ajustement'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.IntegerField(help_text='Diff├®rence (+/-)'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason_type',
            field=models.CharField(choices=[('INVENTAIRE', 'Ajustement inventaire'), ('CASSE', 'Cass├®'), ('VOL', 'Vol'), ('CONFUSION', 'Confusion'), ('ERR_ENTREE', "Erreur d'entr├®e en stock"), ('AVARIE', 'Avari├®'), ('USAGE_INT', 'Usage interne')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='commande_produit',
            field=models.ForeignKey(blank=True, help_text='R├®f├®rence ├á la ligne de commande (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_lot', to='api.commandeproduit'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='date_reception',
            field=models.DateTimeField(help_text='Date de r├®ception du lot (pour FIFO)'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='fournisseur_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='lot',
            field=models.CharField(blank=True, db_index=True, help_text='Num├®ro de lot auto-g├®n├®r├® ou manuel', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='price_cost',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire effectif (ajust├® avec UG)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='produit_nom',
            field=models.CharField(blank=True, help_text='Nom du produit sauvegard├®', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_free',
            field=models.IntegerField(default=0, help_text='Unit├®s gratuites (UG)'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_initial',
            field=models.IntegerField(help_text='Quantit├® totale initiale (pay├®e + gratuites)'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_paid',
            field=models.IntegerField(default=0, help_text='Quantit├® pay├®e uniquement'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_remaining',
            field=models.IntegerField(help_text='Quantit├® restante dans le lot'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de vente lors de la r├®ception', max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='forme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='api.forme'),
        ),
    ]
