# Generated by Django 5.2.5 on 2026-01-26 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_groupe_produit_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleRisque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau_risque', models.CharField(choices=[('STANDARD', 'Standard'), ('HAUT', 'Haut Risque')], default='STANDARD', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='famille_risque',
            field=models.ForeignKey(blank=True, help_text='Famille pour contrôle interactions (ex: AINS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='api.famillerisque'),
        ),
    ]
