# Generated by Django 5.2.5 on 2026-01-28 02:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_produit_rayon_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement'), ('AVOIR', 'Avoir'), ('AUTRE', 'Autre')], default='ESP', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Numéro de chèque, référence virement, etc.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('commande', models.ForeignKey(blank=True, help_text='Facture spécifique liée à ce paiement (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='api.commande')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs_deites', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to='api.fournisseur')),
            ],
            options={
                'verbose_name': 'Paiement Fournisseur',
                'verbose_name_plural': 'Paiements Fournisseurs',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
    ]
