# Generated by Django 5.2.5 on 2026-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_paiementfournisseur_date_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_supplier_exclusive',
            field=models.BooleanField(default=False, help_text='Si activé, ce produit ne peut être commandé que chez ce fournisseur.'),
        ),
    ]
