# Generated by Django 5.2.5 on 2026-02-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_inventaire_inventory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventaire',
            name='inventory_type',
        ),
    ]
