# Generated by Django 5.2.5 on 2026-03-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_alter_facture_numero_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
