# Generated by Django 5.2.5 on 2026-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_alter_couponmonnaie_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_modify_invoice',
            field=models.BooleanField(default=False, verbose_name='Modifier des factures (Caisse)'),
        ),
    ]
