# Generated by Django 5.2.5 on 2026-03-21 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_userdailysession_workstation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='RuptureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date à laquelle le produit est redevenu disponible', null=True)),
                ('est_resolu', models.BooleanField(default=False)),
                ('remarques', models.TextField(blank=True, default='')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruptures_signalees', to='api.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruptures_fournisseurs', to='api.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['est_resolu', '-date_debut'], name='api_rupture_est_res_5aafb1_idx'), models.Index(fields=['produit', 'est_resolu'], name='api_rupture_produit_8bcb00_idx')],
            },
        ),
    ]
