# Generated by Django 6.0.3 on 2026-04-19 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_profile_can_validate_zero_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='is_multi_caisse',
            field=models.BooleanField(default=False, help_text='Activer le mode Multi-Caisse (plusieurs postes de caisse)'),
        ),
        migrations.CreateModel(
            name='PosteCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Code court pour identification (ex: CAISSE-01)', unique=True)),
                ('est_ouvert', models.BooleanField(default=False)),
                ('date_ouverture', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouvert_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_caisses_ouverts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poste de Caisse',
                'verbose_name_plural': 'Postes de Caisse',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='poste_caisse',
            field=models.ForeignKey(blank=True, help_text='Poste de caisse auquel cette facture est assignée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_assignees', to='api.postecaisse'),
        ),
    ]
