# Generated by Django 6.0.3 on 2026-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_cloturecaisse_poste_caisse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='availability_weight',
            field=models.IntegerField(default=60, help_text='Poids de la disponibilité dans le score de santé global (0-100)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='rotation_weight',
            field=models.IntegerField(default=40, help_text='Poids de la rotation dans le score de santé global (0-100)'),
        ),
    ]
