# Generated by Django 6.0.3 on 2026-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_commande_source_alter_orderschedule_execution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='periode_releve_jours',
            field=models.IntegerField(default=10, help_text="Durée en jours d'une tranche de relevé (ex: 10 = du 1-10, 11-20, 21-31). Utilisé uniquement si type_reglement=RELEVE."),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='delai_paiement_jours',
            field=models.IntegerField(default=0, help_text='Délai de paiement accordé en jours après fin de tranche/facture (ex: 10, 15). 0 = au comptant.'),
        ),
    ]
