# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_create_emergency_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_chat_id', models.CharField(help_text='Chat ID Telegram du destinataire', max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_path', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('FACTURE', 'Envoi Facture'), ('PROMIS', 'Disponibilité Promis'), ('MANUEL', 'Envoi Manuel'), ('RAPPEL', 'Rappel Paiement'), ('RAPPORT', 'Rapport Flash')], default='RAPPORT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('DELIVERED', 'Reçu')], default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_logs', to='api.client')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_logs', to='api.facture')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Telegram',
                'verbose_name_plural': 'Journal Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
