# Generated by Django 5.2.5 on 2026-06-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_add_fournisseur_logistics_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='delai_couverture_jours',
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='delai_couverture_jours',
            field=models.IntegerField(default=30, help_text='Autonomie de stock souhaitée après réception (jours de vente à couvrir). Peut varier pour un même fournisseur.'),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='analysis_period_days',
            field=models.IntegerField(default=30, help_text="Période d'analyse des ventes pour calculer la VMD (jours)."),
        ),
    ]
