# Generated by Django 5.2.15 on 2026-06-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_commandeproduit_taux_marge'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='stock_apres_reception',
            field=models.IntegerField(default=0, help_text='Stock du produit après réception (capturé au moment de la clôture)'),
        ),
    ]
