# Generated by Django 5.2.15 on 2026-06-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_commandeproduit_stock_apres_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='min_margin_threshold',
            field=models.DecimalField(decimal_places=2, default=1.34, help_text='Taux de marge minimum acceptable pour les commandes (ex: 1.34 = 25% de marge)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reapprosession',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
