# Generated by Django 5.2.15 on 2026-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_pharmacysettings_min_margin_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='version',
            field=models.IntegerField(default=1, help_text='Version pour optimistic locking — incrémentée à chaque modification de lignes'),
        ),
    ]
