# Generated by Django 5.2.15 on 2026-07-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0218_postevente_alter_caisse_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevente',
            name='mode_pos',
            field=models.BooleanField(default=False, help_text='True si ouvert depuis la Facturation (point de vente), False si ouvert depuis la Caisse Centrale (caisse physique)'),
        ),
    ]
