# Generated by Django 6.0.3 on 2026-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_add_mode_pos_to_postevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_rendu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Monnaie rendue au client (pour ticket de caisse)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Montant total reçu du client (pour ticket de caisse)', max_digits=12, null=True),
        ),
    ]
