# Generated by Django 6.0.3 on 2026-07-24 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_add_composite_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('leave_type', models.CharField(choices=[('CONGE', 'Congé payé'), ('MALADIE', 'Maladie'), ('SANS_SOLDE', 'Sans solde'), ('AUTRE', 'Autre')], default='CONGE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('MATIN', 'Matin'), ('NUIT', 'Nuit'), ('GARDE', 'Garde'), ('REPOS', 'Repos'), ('CONGE', 'Congé')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['date', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='ShiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days_before_rest', models.PositiveIntegerField(default=5, verbose_name='Jours de travail avant repos')),
                ('rest_days', models.PositiveIntegerField(default=2, verbose_name='Jours de repos')),
                ('rotate_shifts', models.BooleanField(default=True, verbose_name='Rotation matin/nuit')),
                ('guard_frequency_days', models.PositiveIntegerField(default=7, verbose_name='Fréquence des gardes (jours)')),
                ('morning_start', models.CharField(default='08:00', max_length=5, verbose_name='Début quart matin')),
                ('morning_end', models.CharField(default='16:00', max_length=5, verbose_name='Fin quart matin')),
                ('night_start', models.CharField(default='16:00', max_length=5, verbose_name='Début quart nuit')),
                ('night_end', models.CharField(default='22:00', max_length=5, verbose_name='Fin quart nuit')),
                ('annual_leave_days', models.PositiveIntegerField(default=26, verbose_name='Jours de congé annuel')),
            ],
            options={
                'verbose_name': 'Configuration des quarts',
                'verbose_name_plural': 'Configurations des quarts',
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mois (1er jour)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié (visible par les opérateurs)')),
            ],
            options={
                'verbose_name': 'Planning mensuel',
                'verbose_name_plural': 'Plannings mensuels',
                'ordering': ['-month'],
            },
        ),
        migrations.RenameIndex(
            model_name='caisse',
            new_name='api_caisse_mode_pa_49a9aa_idx',
            old_name='caisse_mode_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='caisse',
            new_name='api_caisse_date_pa_4b4f61_idx',
            old_name='caisse_date_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='facture',
            new_name='api_facture_is_acti_b3d4a8_idx',
            old_name='facture_active_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='factureproduit',
            new_name='api_facture_facture_cf998d_idx',
            old_name='factureproduit_facture_idx',
        ),
        migrations.RenameIndex(
            model_name='stocklot',
            new_name='api_stocklo_produit_c2533d_idx',
            old_name='stocklot_prod_qty_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='stocklot',
            new_name='api_stocklo_date_ex_657685_idx',
            old_name='stocklot_date_exp_idx',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.shiftschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftschedule',
            unique_together={('month',)},
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('schedule', 'user', 'date')},
        ),
    ]
