# Generated by Django 6.0.3 on 2026-07-25 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_alter_client_phone_alter_fournisseur_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftconfig',
            name='team_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Par individu'), ('FIXED', 'Équipes fixes'), ('ROTATING', 'Équipes tournantes')], default='INDIVIDUAL', max_length=20, verbose_name="Mode d'affectation par équipe"),
        ),
        migrations.AddField(
            model_name='shiftconfig',
            name='team_rotation_days',
            field=models.PositiveIntegerField(default=3, verbose_name="Durée d'un bloc équipe (jours)"),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('default_shift', models.CharField(choices=[('MATIN', 'Matin'), ('NUIT', 'Nuit'), ('GARDE', 'Garde'), ('REPOS', 'Repos')], default='MATIN', max_length=10, verbose_name='Poste par défaut (mode équipe fixe)')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['ordering', 'name'],
            },
        ),
    ]
