# Generated by Django 5.2.17 on 2026-08-30 23:33
# Corrigée : les index existent déjà (créés par 0231 en CONCURRENTLY).
# Rendu idempotent avec IF NOT EXISTS pour éviter l'erreur en dev/prod.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False  # requis pour CREATE INDEX CONCURRENTLY

    dependencies = [
        ('api', '0238_billetage_caisse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS facture_poste_status_idx ON api_facture (poste_caisse_id, status, date DESC)',
            reverse_sql='DROP INDEX IF EXISTS facture_poste_status_idx',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS facture_creator_date_idx ON api_facture (created_by_id, date DESC)',
            reverse_sql='DROP INDEX IF EXISTS facture_creator_date_idx',
        ),
    ]
