import requests
import logging
from django.utils import timezone

logger = logging.getLogger(__name__)

class TelegramService:
    """
    Service pour l'envoi de messages via Telegram Bot API.
    Les credentials sont lus depuis PharmacySettings.
    """

    # Dictionnaire de traduction pour les rapports
    TRANSLATIONS = {
        'fr-FR': {
            'report_title': 'Rapport d\'Activité',
            'flash_report_title': 'Rapport Flash',
            'inventory_report_title': 'Rapport Inventaire',
            'period': 'Période',
            'generated_on': 'Généré le',
            'sales_ttc': 'CA TTC',
            'daily_ca': 'CA du jour',
            'sales_ht': 'CA HT',
            'orders': 'Ventes',
            'avg_basket': 'panier moy.',
            'gross_margin': 'Marge brute',
            'discounts': 'Remises',
            'collections': 'Encaissements',
            'on_account': 'En compte',
            'receivables': 'Créances',
            'cash_movements': 'Mouvements caisse',
            'inflow': 'Entrées',
            'outflow': 'Sorties',
            'balance': 'Solde',
            'stock_outs': 'Ruptures',
            'theoretical_value': 'Valeur théorique',
            'physical_value': 'Valeur physique',
            'diff_value': 'Valeur écart',
            'total_diff': 'Écart total',
            'surplus': 'Excédents',
            'shortage': 'Manquants',
            'top_surplus': 'Top excédents',
            'top_shortage': 'Top manquants',
            'top_suppliers': 'Top Fournisseurs',
            'footer': 'Généré par Zenith Pharma',
            'units': 'unités',
            'products': 'produit(s)',
            'error_token': 'Token bot Telegram manquant',
            'error_chat': 'Chat ID manquant',
            'error_no_inventory': 'Aucun inventaire trouvé',
            'test_title': 'Test Connexion',
            'test_success': 'La connexion Telegram fonctionne correctement !',
            'success': 'Message envoyé avec succès ✅'
        },
        'en-US': {
            'report_title': 'Activity Report',
            'flash_report_title': 'Flash Report',
            'inventory_report_title': 'Inventory Report',
            'period': 'Period',
            'generated_on': 'Generated on',
            'sales_ttc': 'Total Sales (TTC)',
            'daily_ca': 'Daily Sales',
            'sales_ht': 'Total Sales (Excl. Tax)',
            'orders': 'Orders',
            'avg_basket': 'avg. basket',
            'gross_margin': 'Gross Margin',
            'discounts': 'Discounts',
            'collections': 'Total Collections',
            'on_account': 'On Account',
            'receivables': 'Receivables',
            'cash_movements': 'Cash Movements',
            'inflow': 'Inflow',
            'outflow': 'Outflow',
            'balance': 'Balance',
            'stock_outs': 'Stock Outs',
            'theoretical_value': 'Theoretical Value',
            'physical_value': 'Physical Value',
            'diff_value': 'Variance Value',
            'total_diff': 'Total Variance',
            'surplus': 'Surplus',
            'shortage': 'Shortages',
            'top_surplus': 'Top Surplus',
            'top_shortage': 'Top Shortages',
            'top_suppliers': 'Top Suppliers',
            'footer': 'Generated by Zenith Pharma',
            'units': 'units',
            'products': 'product(s)',
            'error_token': 'Missing Telegram bot token',
            'error_chat': 'Missing Chat ID',
            'error_no_inventory': 'No inventory found',
            'test_title': 'Connection Test',
            'test_success': 'Telegram connection is working correctly!',
            'success': 'Message sent successfully ✅'
        }
    }

    @staticmethod
    def t(key: str, lang: str = 'fr-FR') -> str:
        """Traduit une clé selon la langue (fallback en français)."""
        translations = TelegramService.TRANSLATIONS.get(lang, TelegramService.TRANSLATIONS['fr-FR'])
        return translations.get(key, key)

    @staticmethod
    def _get_credentials():
        from .models import PharmacySettings
        try:
            ps = PharmacySettings.objects.first()
            if ps:
                return (ps.telegram_bot_token or '').strip(), (ps.telegram_chat_id or '').strip()
        except Exception:
            pass
        return '', ''

    @staticmethod
    def send_message(text: str, bot_token: str = None, chat_id: str = None, parse_mode: str = 'HTML') -> tuple[bool, str]:
        """
        Envoie un message texte via le bot Telegram.
        Retourne (success: bool, message: str).
        """
        if not bot_token or not chat_id:
            token, cid = TelegramService._get_credentials()
            bot_token = bot_token or token
            chat_id = chat_id or cid

        if not bot_token:
            return False, "Token bot Telegram manquant"
        if not chat_id:
            return False, "Chat ID manquant"

        # Telegram limite les messages à 4096 caractères
        if len(text) > 4096:
            text = text[:4090] + "\n…"

        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": text,
            "parse_mode": parse_mode,
        }

        try:
            resp = requests.post(url, json=payload, timeout=10)
            data = resp.json()
            if resp.status_code == 200 and data.get('ok'):
                logger.info(f"[Telegram] Message envoyé à chat_id={chat_id}")
                return True, "Message envoyé avec succès ✅"

            error_desc = data.get('description', 'Erreur inconnue')
            error_code = data.get('error_code', resp.status_code)
            logger.warning(f"[Telegram] Erreur {error_code}: {error_desc}")
            return False, f"Erreur Telegram ({error_code}): {error_desc}"

        except requests.exceptions.Timeout:
            return False, "Timeout — impossible de joindre l'API Telegram"
        except Exception as e:
            logger.error(f"[Telegram] Exception: {e}")
            return False, str(e)
