from django.test import TestCase
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from .models import Produit, Rayon, Fournisseur, Commande, Facture, FactureProduit, Client
from decimal import Decimal

# Create your tests here.

class RayonAPITests(APITestCase):
    def test_create_rayon(self):
        """Ensure we can create a new rayon object."""
        url = reverse('rayon-list') # 'rayon-list' is generated by the router
        data = {'name': 'Nouveau Rayon'}
        response = self.client.post(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Rayon.objects.count(), 1)
        self.assertEqual(Rayon.objects.get().name, 'Nouveau Rayon')

class ProduitAPITests(APITestCase):
    def setUp(self):
        """Crée les objets de base (rayon, fournisseur) pour les tests de produits."""
        self.rayon = Rayon.objects.create(name="Fruits & Légumes")
        self.fournisseur = Fournisseur.objects.create(
            name="Ferme locale",
            address="123 rue de la ferme",
            phone="0102030405",
            email="contact@ferme.fr"
        )
        self.produit_data = {
            'name': 'Pomme',
            'description': 'Une belle pomme rouge',
            'stock': 100,
            'cost_price': 0.50,
            'selling_price': 1.50,
            'rayon': self.rayon.id,
            'fournisseur': self.fournisseur.id
        }
        self.url = reverse('produit-list')

    def test_create_produit(self):
        """Ensure we can create a new produit object."""
        response = self.client.post(self.url, self.produit_data, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Produit.objects.count(), 1)
        self.assertEqual(Produit.objects.get().name, 'Pomme')

class CommandeAPITests(APITestCase):
    def setUp(self):
        """Crée un fournisseur pour les tests de commandes."""
        self.fournisseur = Fournisseur.objects.create(
            name="Grand Fournisseur",
            address="456 Avenue des Commandes",
            phone="0987654321",
            email="commandes@fournisseur.com"
        )
        self.url = reverse('commande-list')

    def test_create_commande(self):
        """Vérifie qu'on peut créer une commande sans fournir de total."""
        data = {'fournisseur': self.fournisseur.id}
        response = self.client.post(self.url, data, format='json')

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Commande.objects.count(), 1)
        # Vérifie que la réponse contient le total calculé (qui est 0.00 pour une nouvelle commande)
        self.assertEqual(response.data['total'], "0.00")

        commande = Commande.objects.get()
        self.assertEqual(commande.fournisseur.id, self.fournisseur.id)



