"""
Langue des documents générés côté serveur (PDF, exports).

Lit ``PharmacySettings.locale`` ('fr-FR', 'en-US', ...) et expose un petit
dictionnaire de traductions pour les chaînes écrites dans les documents.

Usage::

    from api.utils_doclang import T, get_document_language

    lang = get_document_language()          # 'fr' ou 'en'
    titre = T(lang, 'doc_report')           # 'RAPPORT' ou 'REPORT'
    label = T(lang, 'title_rapport_mensuel', mois='2026-01')

Aucune dépendance à django.utils.translation : le dict simple suffit.
"""


def get_document_language() -> str:
    """
    Retourne 'en' si ``PharmacySettings.locale`` commence par 'en', sinon 'fr'.

    Robuste : toute erreur (DB inaccessible, settings absents, champ manquant)
    retombe sur 'fr'.
    """
    try:
        from api.models import PharmacySettings
        ps = PharmacySettings.objects.first()
        locale = (getattr(ps, 'locale', None) or 'fr-FR') if ps else 'fr-FR'
        return 'en' if str(locale).strip().lower().startswith('en') else 'fr'
    except Exception:
        return 'fr'


DOC_STRINGS = {
    'fr': {
        # ── Titres de documents (endpoints) ─────────────────────────────────
        'doc_report': 'RAPPORT',
        'title_rapport_mensuel': 'RAPPORT MENSUEL — {mois}',
        'title_rapport_activite': "RAPPORT D'ACTIVITÉ — {debut} au {fin}",

        # ── build_rapport_pdf : KPIs ────────────────────────────────────────
        'kpi_ca_ttc': 'CA TTC',
        'kpi_ca_ht': 'CA HT',
        'kpi_marge_brute': 'Marge Brute',
        'kpi_marge_pct': 'Marge %',
        'kpi_remises': 'Remises',
        'kpi_nb_ventes': 'Nb Ventes',

        # ── build_rapport_pdf : titres de sections ─────────────────────────
        'section_enc_achats': '💰 Encaissements & Achats',
        'section_clients_ug': '👥 Clients Professionnels & Unités Gratuites',
        'section_tva_creances': '📊 TVA, Créances & Mouvements',
        'section_detail_mvt': '📋 Détail des Mouvements de Caisse',

        # ── build_rapport_pdf : en-têtes de colonnes ───────────────────────
        'col_mode': 'Mode',
        'col_montant': 'Montant',
        'col_fournisseur': 'Fournisseur',
        'col_cmd': 'Cmd',
        'col_client': 'Client',
        'col_ca': 'CA',
        'col_reste': 'Reste',
        'col_produit': 'Produit',
        'col_qte': 'Qté',
        'col_valeur': 'Valeur',
        'col_taux': 'Taux',
        'col_tva': 'TVA',
        'col_ttc': 'TTC',
        'col_date': 'Date',
        'col_type': 'Type',
        'col_motif': 'Motif',
        'col_utilisateur': 'Utilisateur',

        # ── build_rapport_pdf : lignes / libellés financiers ───────────────
        'row_depots': 'Dépôts',
        'row_total_encaissements': 'Total Encaissements',
        'row_ventes_credit': 'Ventes à crédit',
        'row_coupons': 'Coupons',
        'row_aucun_achat': 'Aucun achat',
        'row_total': 'Total',
        'row_total_recouv': 'Total ({pct}% recouv.)',
        'row_total_pct_ca': 'Total ({pct}% CA)',
        'row_creances': 'Créances à Percevoir',
        'row_mvt_caisse': 'Mouvements Caisse',
        'row_entrees_diverses': 'Entrées diverses',
        'row_sorties_diverses': 'Sorties diverses',
        'row_solde': 'Solde',
        'row_entree': 'Entrée',
        'row_sortie': 'Sortie',
        'user_unknown': 'Inconnu',
        'user_systeme': 'Système',

        # ── Modes de paiement (clés = codes Caisse.MODES_PAIEMENT) ─────────
        'pay_especes': 'Espèces',
        'pay_cheque': 'Chèque',
        'pay_carte': 'Carte',
        'pay_virement': 'Virement',
        'pay_om': 'Orange Money',
        'pay_momo': 'Mobile Money',
        'pay_coupon': 'Coupon',
        'pay_en_compte': 'En compte',
        'pay_depot': 'Dépôt',
        'pay_recouvrement': 'Recouvrement',

        # ── valeur_stock_pdf (inventory.py) ────────────────────────────────
        'stock_type_pharmacie': ' - PHARMACIE (sans divers)',
        'stock_doc_title': 'VALEUR STOCK{suffix} ({valo})',
        'stock_doc_title_divers': 'VALEUR STOCK DIVERS ({valo})',
        'stock_valo_pmp': 'PMP',
        'stock_valo_vente': 'VENTE',
        'stock_type_label_pmp': "COÛT D'ACHAT (PMP)",
        'stock_type_label_vente': 'PRIX DE VENTE (TTC)',
        'stock_recap_title': 'RÉCAPITULATIF GÉNÉRAL — {label}',
        'stock_col_methode': 'MÉTHODE DE VALORISATION',
        'stock_col_montant': 'MONTANT RECONSTITUÉ',
        'stock_row_ht': 'Valeur Totale HT',
        'stock_row_tva': 'Montant Total TVA',
        'stock_row_total': 'VALEUR TOTALE {valo}',
        'stock_tva_title': 'RÉPARTITION DÉTAILLÉE PAR TAUX DE TVA',
        'stock_col_taux_tva': 'Taux TVA',
        'stock_col_base_ht': 'Base HT',
        'stock_col_montant_tva': 'Montant TVA',
        'stock_col_total_reconstitue': 'Total Reconstitué',
        'stock_note': '<b>Note comptable :</b> Cette valorisation est {desc}',
        'stock_desc_pmp': 'fondée sur le PMP stocké en base.',
        'stock_desc_vente': 'fondée sur les prix de vente publics actuels.',

        # ── Libellés génériques de documents ─────────────────────────────────
        'doc_tel': 'Tél : {v}',
        'doc_edited': 'Édité le : {d}',
        'doc_generated': 'Généré le {d}',
        'doc_period': ' | Période : {d} → {f}',
        'doc_at': 'à',
        'col_statut': 'Statut',
        'col_libelle': 'Libellé',
        'col_designation': 'Désignation',
        'col_reference': 'Référence',
        'col_lot': 'N° Lot',
        'col_lot_simple': 'Lot',
        'col_stock': 'Stock',
        'col_rayon': 'Rayon',
        'col_forme': 'Forme',
        'col_heure': 'Heure',
        'col_caisse': 'Caisse',
        'col_description': 'Description',
        'col_montant_f': 'Montant (F)',
        'col_montant_ht': 'Montant HT (F)',
        'col_montant_ttc': 'Montant TTC',
        'col_montant_total': 'Montant Total (F)',
        'col_total_ht': 'Total HT',
        'col_total_tva': 'Total TVA',
        'col_total_ttc': 'Total TTC',
        'col_remise': 'Remise',
        'col_num_facture': 'N° Facture',
        'col_facture': 'Facture',
        'col_facture_num': 'Facture #',
        'col_num_avoir': 'N° Avoir',
        'col_nb_factures': 'Nb Factures',
        'col_rang': 'Rang',
        'col_vendeur': 'Vendeur',
        'col_caissier': 'Caissier',
        'col_mode_paiement': 'Mode de Paiement',
        'col_quantite': 'Quantité',
        'col_prix': 'Prix',
        'col_prix_vente': 'Prix Vente',
        'col_prix_achat': 'Prix Achat',
        'col_nom': 'Nom',
        'col_numero': 'Numéro',
        'col_panier_moyen': 'Panier Moyen',
        'col_pct_ca': '% / CA',
        'col_detail': 'Détail',
        'col_observation': 'Observation',
        'col_saisi_par': 'Saisi par',
        'col_cree_par': 'Créé par',
        'col_annule_par': 'Annulé par',
        'col_taux_marge': 'Taux Marge %',
        'col_qte_vendue': 'Qté vendue',
        'col_ca_ttc_f': 'CA TTC (F)',
        'col_cout_achat': 'Coût achat (F)',
        'col_marge_f': 'Marge (F)',
        'col_total_commande': 'Total Commandé (F)',
        'col_total_paye': 'Total Payé (F)',
        'col_solde_du': 'Solde Dû (F)',
        'col_echu': 'Échu (F)',
        'col_a_venir': 'À venir (F)',
        'col_prochaine_ech': 'Prochaine échéance',
        'col_paye_f': 'Payé (F)',
        'col_restant_du': 'Restant Dû (F)',
        'col_jours_retard': 'Jours retard (max)',
        'col_nb_refs': 'Nb Références',
        'col_qte_totale': 'Qté totale',
        'col_valeur_pmp': 'Valeur Stock PMP (F)',
        'col_stock_min': 'Stock minimum',
        'col_alertes_rupture': 'Alertes rupture',
        'col_alertes_peremption': 'Alertes péremption',
        'col_nb_commandes': 'Nb Commandes',
        'col_precompte': 'Précompte (F)',
        'col_nb_avoirs': 'Nb Avoirs',
        'col_montant_avoirs': 'Montant Avoirs (F)',
        'col_net': 'Net (F)',
        'col_ug_recues': 'UG reçues',
        'col_ug_vendues': 'UG vendues',
        'col_ug_restantes': 'UG restantes',
        'col_lot_num': 'Lot #',
        'col_caisse_vendeur': 'Caisse / Vendeur',
        'col_heure_ouv': 'Heure ouverture',
        'col_heure_ferm': 'Heure fermeture',
        'col_ventes_f': 'Ventes (F)',
        'col_ventes': 'Ventes',
        'col_entrees_f': 'Entrées (F)',
        'col_sorties_f': 'Sorties (F)',
        'col_montant_theo': 'Montant théorique (F)',
        'col_montant_reel': 'Montant réel (F)',
        'col_ecart_f': 'Écart (F)',
        'col_remise_globale': 'Remise Globale',
        'col_remise_lignes': 'Remise Lignes',
        'col_remise_fidelite': 'Remise Fidélité',
        'col_total_remise': 'Total Remise',
        'xcol_remise_globale': 'Remise Globale (F)',
        'xcol_remise_lignes': 'Remises Lignes (F)',
        'xcol_fidelite': 'Fidélité (F)',
        'xcol_total_remise': 'Total Remise (F)',
        'col_chiffre_affaires': 'Chiffre Affaires',
        'col_id_produit': 'ID Produit',
        'col_nom_produit': 'Nom Produit',
        'col_nb_ruptures': 'Nombre de Ruptures',
        'col_qte_change': 'Qté Change',
        'col_valorisation': 'Valorisation',
        'col_facture_origine': 'Facture origine',
        'col_nb_lignes': 'Nb lignes',
        'col_om': 'OM',
        'col_momo': 'MOMO',
        'col_valeur_stock': 'Valeur Stock',
        'col_derniere_vente': 'Dernière Vente',
        'col_part': 'Part (%)',
        'col_total_jour': 'Total jour (F)',
        'col_date_annulation': 'Date annulation',
        'col_qte_retournee': 'Qté retournée',
        'col_nb_mouvements': 'Nb mouvements',
        'col_panier_moyen_f': 'Panier Moyen (F)',
        'col_remises_acc': 'Remises accordées (F)',
        'col_taux_remise': 'Taux Remise %',
        'col_annulations': 'Annulations',
        'col_semaine': 'Semaine',
        'col_encaissements': 'Encaissements (F)',
        'col_depenses_f': 'Dépenses (F)',
        'col_achats_f': 'Achats fournisseurs (F)',
        'col_solde_net': 'Solde net semaine (F)',
        'col_solde_cumule': 'Solde cumulé (F)',
        'col_qte_detruite': 'Qté détruite',
        'col_pmp_f': 'PMP (F)',
        'col_valeur_perdue': 'Valeur perdue (F)',
        'col_promotion': 'Promotion',
        'col_valeur_remise': 'Valeur / Remise',
        'col_date_debut': 'Date début',
        'col_date_fin': 'Date fin',
        'col_nb_produits': 'Nb produits',
        'col_ca_mois': 'CA du mois (F)',
        'col_encours': 'Encours total (F)',
        'col_plafond': 'Plafond crédit (F)',
        'col_taux_util': 'Taux utilisation %',
        'user_system': 'Système',
        'client_passage': 'Client de passage',
        'client_passage_short': 'Passage',
        'client_comptant': 'Comptant',
        'client_inconnu': 'Client inconnu',
        'produit_inconnu': 'Produit inconnu',
        'company_fallback': 'Entreprise',
        'grp_sans_rayon': 'Sans Rayon',
        'grp_sans_forme': 'Sans Forme',
        'grp_sans_groupe': 'Sans Groupe',
        'grp_sans_fournisseur': 'SANS FOURNISSEUR',
        'grp_autres': 'AUTRES',
        'grp_non_classe': 'Non classé',
        'grp_sans_rayon_paren': '(Sans rayon)',
        'val_divers': 'Divers',
        'val_pharmacie': 'Pharmacie',
        'val_jamais': 'Jamais',
        'pay_cb': 'Carte bancaire',
        'pay_mobile_money': 'Mobile Money',
        'pay_assurance': 'Assurance / Tiers payant',
        'pay_fidelite': 'Points Fidélité',

        # ── invoice_pdf.py (PDF facture) ─────────────────────────────────────
        'inv_facture': 'FACTURE',
        'inv_proforma': 'PROFORMA',
        'inv_lbl_invoice_no': 'Facture N° :',
        'inv_lbl_n_facture': 'N° Facture :',
        'inv_lbl_date': 'Date :',
        'inv_lbl_statut': 'Statut :',
        'inv_lbl_tel': 'Tel :',
        'inv_lbl_client': 'Client :',
        'inv_col_pu': 'P.U',
        'inv_subtotal': 'Sous-total :',
        'inv_tva': 'TVA :',
        'inv_remise': 'Remise :',
        'inv_total_payer': 'TOTAL À PAYER :',
        'inv_total_ttc_lbl': 'Total TTC :',
        'inv_page': 'Page {n}',

        # ── creances.py (reçu, relevé, export Excel) ─────────────────────────
        'cre_sheet': 'Créances',
        'cre_col_client_assurance': 'Client / Assurance',
        'cre_col_beneficiaire': 'Bénéficiaire',
        'cre_col_paye': 'Montant Payé',
        'cre_col_reste': 'Reste à Payer',
        'cre_title': 'Listing des Créances',
        'cre_title_history': ' — Historique',
        'cre_title_pending': ' — En attente',
        'cre_period_between': ' ({d} au {f})',
        'cre_period_from': ' (à partir du {d})',
        'cre_period_until': " (jusqu'au {f})",
        'cre_status_paid': 'Payée',
        'cre_status_pending': 'En attente',
        'cre_total_line': 'TOTAL ({n} facture(s))',
        'recu_title': 'REÇU DE PAIEMENT',
        'recu_lbl_facture': 'Facture N° :',
        'recu_lbl_date_paiement': 'Date du paiement :',
        'recu_lbl_mode': 'Mode de règlement :',
        'recu_lbl_beneficiaire': 'Bénéficiaire :',
        'recu_dette_avant': 'Dette avant paiement',
        'recu_montant_paye': 'MONTANT PAYÉ CE JOUR',
        'recu_reste': 'RESTE À PAYER',
        'recu_thanks': 'Merci de votre confiance.',
        'releve_title': 'RÉCAPITULATIF DE RÈGLEMENT',
        'releve_lbl_reference': 'Référence :',
        'releve_total': 'TOTAL RÈGLEMENT :',

        # ── etat_inventaire.py (PDF état d'inventaire) ───────────────────────
        'einv_title_grouped': "ÉTAT D'INVENTAIRE PAR {g}",
        'einv_title_filtered': "ÉTAT D'INVENTAIRE - {g} : {name}",
        'einv_group_forme': 'FORME',
        'einv_group_rayon': 'RAYON',
        'einv_group_groupe': 'GROUPE',
        'einv_stock_machine': 'Stock Machine',
        'einv_stock_nonzero': 'Stocks Non Nuls',
        'einv_stock_zero': 'Stock à Zéro',
        'einv_option_line': 'Option : {opt} | Imprimé le {d}',
        'einv_col_pv': 'PV',
        'einv_col_qte_phys': 'Qté Physique',
        'einv_products_count': '({n} produits)',

        # ── ordonnancier_view.py ─────────────────────────────────────────────
        'ord_title': '📋 ORDONNANCIER',
        'ord_col_patient': 'Patient',
        'ord_col_presc': 'Prescripteur',
        'ord_col_meds': 'Médicaments',
        'ord_col_surv': 'Surv.',
        'ord_footer_total': 'Total : {n} entrée(s)',
        'ord_footer_limit': ' (limité à {n})',

        # ── inventaire/pdf.py (écarts + état + print data) ───────────────────
        'invd_ecarts_title': 'RAPPORT DES ÉCARTS - #{id}',
        'invd_date': 'Date : {d}',
        'invd_no_ecart': 'Aucun écart constaté.',
        'invd_rayon_prefix': 'RAYON : {r}',
        'invd_col_theo': 'Theo.',
        'invd_col_phys': 'Phys.',
        'invd_col_ecart': 'Ecart',
        'invd_col_val': 'Val.',
        'invd_total_ecarts': 'TOTAL GLOBAL ÉCARTS (VALEUR) : {v} F',
        'invd_etat_title': "ÉTAT D'INVENTAIRE #{id}",
        'invd_desc': 'Description : {d}',
        'invd_report_title': "RAPPORT D'INVENTAIRE",
        'invd_sheet_title': 'FEUILLE DE SAISIE INVENTAIRE',
        'invd_ref_desc': 'Réf : #{id} - {desc}',
        'invd_ref': 'Réf : #{id}',

        # ── reappro_history.py ───────────────────────────────────────────────
        'reap_title': 'SESSION DE RÉAPPROVISIONNEMENT #{id}',
        'reap_by': 'Effectué par : {v}',
        'reap_volume': 'Volume total : {u} unités ({p} produits)',
        'reap_col_expiry': 'PÉREMPTION',
        'reap_empty': 'Aucun produit enregistré pour cette session.',
        'reap_doc_title': 'CONFIRMATION DE RÉAPPROVISIONNEMENT',

        # ── pdf_generation.py (étiquettes commandes) ─────────────────────────
        'lbl_fact_prefix': 'Fact:{v}',

        # ── promis.py (tickets) ──────────────────────────────────────────────
        'prm_ticket_title': 'TICKET PROMIS',
        'prm_copy_pharmacy': 'EXEMPLAIRE PHARMACIE',
        'prm_copy_client': 'EXEMPLAIRE CLIENT',
        'prm_client': 'CLIENT :',
        'prm_tel': 'Tél : {v}',
        'prm_produit': 'PRODUIT PROMIS :',
        'prm_quantite': 'Quantité : {n}',
        'prm_keep1': 'Conservez ce ticket comme preuve',
        'prm_keep2': 'de votre réservation.',
        'prm_statut': 'Statut : {s}',
        'prm_cut': '✂ DECOUPER ICI ✂',
        'prm_group_title': 'TICKET PROMIS (RELIQUAT)',
        'prm_keep_group': 'Veuillez conserver ce ticket pour récupérer vos produits.',

        # ── categories.py (PDF état de stock par rayon) ──────────────────────
        'cat_title_rayon': 'ÉTAT DE STOCK - RAYON : {name}',
        'cat_title_sans': 'ÉTAT DE STOCK - SANS RAYON',
        'cat_nonzero': ' (Non-Nuls)',
        'cat_tot': 'Tot : {n}',

        # ── inventaire/listing_excel.py ──────────────────────────────────────
        'lx_sheet_stock': 'Listing Stock (Lots)',
        'lx_sheet_inv': 'Listing Inventaire',
        'lx_sheet_blind': 'Listing Inventaire Aveugle',
        'lx_grp_forme': 'Forme galénique',
        'lx_grp_groupe': 'Groupe thérapeutique',
        'lx_flt_tous': 'Tous les stocks',
        'lx_flt_zero': 'Stocks nuls (Qté = 0)',
        'lx_flt_nonzero': 'Stocks non nuls (Qté > 0)',
        'lx_col_stock_theo': 'Stock Théo.',
        'lx_col_qte_comptee': 'Qté Comptée',
        'lx_col_ecart': 'Écart',
        'lx_col_val_ecart': 'Val. Écart',
        'lx_col_stock_res': 'Stock Rés.',
        'lx_col_stock_rayon': 'Stock Rayon',
        'lx_col_val_stock': 'Val. Stock',
        'lx_col_exp_lot': 'Exp. Lot',
        'lx_title': "LISTING D'INVENTAIRE DE STOCK",
        'lx_src_stock': 'Stock courant (par lots)',
        'lx_src_inv': 'Inventaire',
        'lx_src_blind': "Inventaire à l'aveugle (sans stock théorique)",
        'lx_src_default': 'Stock courant',
        'lx_info_line': 'Édité le : {now}  |  Source : {src}  |  Regroupement : {grp}  |  Filtre : {flt}',
        'lx_subtotal': '  Total {g}  —  {r} réf.  |  {l} lot(s)  |  {s} boîte(s)',
        'lx_grand_total': '  TOTAL GÉNÉRAL  ({r} réf. / {l} lot(s))',

        # ── excel_general.py (rapport mensuel multi-feuilles) ────────────────
        'xs_sheet_synthese': 'Synthèse',
        'xs_sheet_ca_marges': 'CA & Marges',
        'xs_sheet_remises': 'Remises & Avoirs',
        'xs_sheet_top': 'Top Produits',
        'xs_sheet_dettes': 'Dettes Fournisseurs',
        'xs_sheet_creances': 'Créances Clients',
        'xs_sheet_stock': 'Stock & Inventaire',
        'xs_sheet_fiscal': 'Synthèse Fiscale',
        'xs_sheet_ugs': 'UGs (Unités Gratuites)',
        'xs_sheet_achats': 'Achats Fournisseurs',
        'xs_sheet_caisses': 'État des Caisses',
        'xs_sheet_depenses': 'Dépenses',
        'xs_t_synthese': 'SYNTHÈSE DU MOIS — {mois}',
        'xs_t_ca': 'CA & MARGES JOURNALIERS — {mois}',
        'xs_t_remises': 'REMISES & AVOIRS — {mois}',
        'xs_t_top': 'TOP PRODUITS — {mois}',
        'xs_t_dettes': 'DETTES FOURNISSEURS — {mois}',
        'xs_t_creances': 'CRÉANCES CLIENTS — {mois}',
        'xs_t_stock': 'STOCK & INVENTAIRE — {mois}',
        'xs_t_fiscal': 'SYNTHÈSE FISCALE — {mois}',
        'xs_t_ugs': 'UNITÉS GRATUITES (UGs) — {mois}',
        'xs_t_achats': 'ACHATS FOURNISSEURS — {mois}',
        'xs_t_caisses': 'ÉTAT DES CAISSES — {mois}',
        'xs_t_depenses': 'DÉPENSES — {mois}',
        'xs_r_ca_pharma_ttc': 'CA PHARMACIE TTC',
        'xs_r_ca_divers_ttc': 'CA DIVERS TTC',
        'xs_r_ca_total_ttc': 'CA TOTAL TTC',
        'xs_r_marge_pharma': 'Marge brute Pharmacie',
        'xs_r_taux_pharma': 'Taux marge Pharmacie',
        'xs_r_marge_divers': 'Marge brute Divers',
        'xs_r_marge_totale': 'Marge brute TOTALE',
        'xs_r_taux_total': 'Taux marge TOTAL',
        'xs_r_remises': 'Remises accordées',
        'xs_r_rem_glob': '  dont remises globales',
        'xs_r_rem_lignes': '  dont remises lignes',
        'xs_r_rem_fid': '  dont fidélité',
        'xs_r_nb_ventes': 'Nombre de ventes',
        'xs_r_panier': 'Panier moyen TTC',
        'xs_r_creances': 'Créances clients',
        'xs_r_dettes': 'Dettes fournisseurs',
        'xs_col_indicateur': 'Indicateur',
        'xs_col_montant_valeur': 'Montant / Valeur',
        'xsc_ca_pharma': 'CA Pharmacie TTC',
        'xsc_ca_divers': 'CA Divers TTC',
        'xsc_ca_total': 'CA Total TTC',
        'xsc_marge_pharma': 'Marge Pharmacie',
        'xsc_marge_divers': 'Marge Divers',
        'xsc_marge_totale': 'Marge Totale',
        'xs_sec_remises': 'REMISES ACCORDÉES',
        'xs_sec_avoirs': 'AVOIRS FOURNISSEURS',
        'xs_sec_resume': 'RÉSUMÉ',
        'xs_sec_recap': 'RÉCAPITULATIF GÉNÉRAL',
        'xs_caissier': 'CAISSIER : {nom}',
        'fis_regime': 'Régime fiscal',
        'fis_mode': "Mode d'imposition",
        'fis_ca': "CHIFFRE D'AFFAIRES",
        'fis_tva': 'TVA collectée',
        'fis_achats': 'ACHATS & PRÉCOMPTE',
        'fis_total_achats': 'Total achats HT',
        'fis_taux_precompte': 'Taux précompte ({regime})',
        'fis_total_precompte': 'Total précompte',
        'fis_precompte_na': 'Précompte (non applicable en Marge Administrée)',
        'fis_accompte': 'ACCOMPTE (sur CA)',
        'fis_base_marge': 'Marge brute',
        'fis_base_ca': "Chiffre d'affaires HT",
        'fis_accompte_base': 'Accompte base',
        'fis_cac': 'CAC ({t}%)',
        'fis_accompte_total': 'Accompte total',
        'ug_total_recues': 'Total UGs reçues (achats)',
        'ug_total_vendues': 'Total UGs vendues (avec factures)',
        'ug_total_restantes': 'Total UGs restantes (en stock)',
        'ug_taux_rotation': 'Taux de rotation UG',
        'dep_total_sorties': 'Total SORTIES (dépenses)',
        'dep_total_entrees': 'Total ENTRÉES',
        'dep_solde': 'SOLDE',

        # ── excel_general_extra.py ───────────────────────────────────────────
        'xe_sheet_modes': 'Modes de Paiement',
        'xe_t_modes': 'MODES DE PAIEMENT — {mois}',
        'xe_sec_recap': 'RÉCAPITULATIF GLOBAL',
        'xe_sec_cloture': 'DÉTAIL PAR CLÔTURE DE CAISSE (JSON)',
        'xe_sec_evo_mode': 'ÉVOLUTION JOURNALIÈRE PAR MODE',
        'xe_sec_evo': 'ÉVOLUTION vs MOIS PRÉCÉDENT',
        'xe_ca_cur': 'CA mois actuel',
        'xe_ca_prev': 'CA mois précédent',
        'xe_var_ca': 'Variation CA',
        'xe_marge_cur': 'Marge mois actuel',
        'xe_marge_prev': 'Marge mois précédent',
        'xe_var_marge': 'Variation marge',
        'xe_nb_cur': 'Nb ventes actuel',
        'xe_nb_prev': 'Nb ventes précédent',
        'xe_var_nb': 'Variation nb ventes',
        'xe_sec_obj': 'OBJECTIF COMMERCIAL',
        'xe_obj_ca': 'Objectif CA mensuel',
        'xe_ca_realise': 'CA réalisé',
        'xe_taux': "Taux d'atteinte",
        'xe_ecart_obj': 'Écart objectif',
        'xe_sheet_retours': 'Retours & Annulations',
        'xe_t_retours': 'RETOURS & ANNULATIONS — {mois}',
        'xe_sec_fact_ann': 'FACTURES ANNULÉES',
        'xe_no_ann': 'Aucune annulation ce mois',
        'xe_sec_retours': 'PRODUITS LES PLUS RETOURNÉS (MouvementStock)',
        'xe_no_retour': 'Aucun retour enregistré ce mois',
        'xe_sheet_perf': 'Performance Vendeurs',
        'xe_t_perf': 'PERFORMANCE VENDEURS — {mois}',
        'xe_no_perf': 'Aucune donnée vendeur pour cette période',
        'xe_sheet_treso': 'Suivi Trésorerie',
        'xe_t_treso': 'SUIVI TRÉSORERIE — {mois}',
        'xe_sec_projection': 'PROJECTION MOIS SUIVANT',
        'xe_creances_recouvrer': 'Créances à recouvrer (solde dû)',
        'xe_solde_net': 'Solde net trésorerie du mois',
        'xe_treso_prev': 'Trésorerie prévisionnelle',
        'xe_sheet_perimes': 'Périmés & Pertes',
        'xe_t_perimes': 'PÉRIMÉS & PERTES — {mois}',
        'xe_no_perime': 'Aucun périmé enregistré ce mois',
        'xe_sheet_promos': 'Promotions',
        'xe_t_promos': 'PROMOTIONS ACTIVES — {mois}',
        'xe_no_promo': 'Aucune promotion active ce mois',
        'xe_sheet_clients_pro': 'Clients Pro & Mutuelles',
        'xe_t_clients_pro': 'CLIENTS PRO & MUTUELLES — {mois}',
        'xe_no_client_pro': 'Aucun client pro actif ce mois',

        # ── finance.py (CSV comptable, Excel remises, livre de caisse) ───────
        'fin_sheet_remises_details': 'Détails Remises',
        'fin_t_remises_details': 'Détail des Remises par Facture',
        'fin_sheet_remises': 'Remises',
        'fin_t_remises': 'Rapport des Remises par Utilisateur',
        'fin_sheet_livre': 'Livre de Caisse',
        'fin_t_livre': 'Livre de Caisse — Période du {d} au {f}',
        'fin_periode': 'Période : {d} au {f}',
        'col_entrees_man': 'Entrées manuelles',
        'col_sorties_man': 'Sorties manuelles',
        'col_solde_jour': 'Solde jour',
        'fin_total_general': 'TOTAL GÉNÉRAL',
        'fin_sheet_detail': 'Détail des opérations',
        'fin_t_detail': 'Détail des opérations — Période du {d} au {f}',
        'col_facture_ref': 'N° Facture / Réf.',
        'col_type_op': 'Type opération',
        'col_rubrique': 'Rubrique / Mode',
        'col_motif_desc': 'Motif / Description',
        'col_sens': 'Sens',
        'op_vente': 'Vente',
        'op_entree_man': 'Entrée manuelle',
        'op_sortie_man': 'Sortie manuelle',
        'op_credit': 'Crédit',
        'op_debit': 'Débit',
        'fin_sous_total': 'Sous-total {d}',
        'fin_total_credit': 'TOTAL CRÉDIT',
        'fin_total_debit': 'TOTAL DÉBIT',
        'fin_solde_net': 'SOLDE NET',

        # ── audit.py / sales.py / ruptures.py / adjustments.py / autres ─────
        'aud_col_datetime': 'Date/Heure',
        'aud_col_action': 'Action',
        'aud_col_modele': 'Modèle',
        'aud_col_objet': 'Objet',
        'adj_sheet': 'Ajustements Stock',
        'adj_title': 'Journal des Ajustements de Stock',
        'avo_sheet': 'Avoirs clients',
        'hv_sheet': 'Historique Ventes',
        'bal_title': '{title} - {d} au {f}',

        # ── commandes/export.py ──────────────────────────────────────────────
        'cmd_sans_cip': '--- PRODUITS SANS CIP ---',
        'cmd_txt_head': 'Commande #{id} - Fournisseur : {f}',
        'cmd_cip_demande': 'CIP demandé : {c}',
        'cmd_sans_cip_txt': 'PRODUITS SANS CIP (à saisir manuellement) :',
    },

    'en': {
        # ── Titres de documents (endpoints) ─────────────────────────────────
        'doc_report': 'REPORT',
        'title_rapport_mensuel': 'MONTHLY REPORT — {mois}',
        'title_rapport_activite': 'ACTIVITY REPORT — {debut} to {fin}',

        # ── build_rapport_pdf : KPIs ────────────────────────────────────────
        'kpi_ca_ttc': 'Sales (incl. tax)',
        'kpi_ca_ht': 'Sales (excl. tax)',
        'kpi_marge_brute': 'Gross Margin',
        'kpi_marge_pct': 'Margin %',
        'kpi_remises': 'Discounts',
        'kpi_nb_ventes': '# Sales',

        # ── build_rapport_pdf : titres de sections ─────────────────────────
        'section_enc_achats': '💰 Collections & Purchases',
        'section_clients_ug': '👥 Business Clients & Free Units',
        'section_tva_creances': '📊 VAT, Receivables & Movements',
        'section_detail_mvt': '📋 Cash Movements Detail',

        # ── build_rapport_pdf : en-têtes de colonnes ───────────────────────
        'col_mode': 'Method',
        'col_montant': 'Amount',
        'col_fournisseur': 'Supplier',
        'col_cmd': 'Ord.',
        'col_client': 'Client',
        'col_ca': 'Sales',
        'col_reste': 'Due',
        'col_produit': 'Product',
        'col_qte': 'Qty',
        'col_valeur': 'Value',
        'col_taux': 'Rate',
        'col_tva': 'VAT',
        'col_ttc': 'Incl. tax',
        'col_date': 'Date',
        'col_type': 'Type',
        'col_motif': 'Reason',
        'col_utilisateur': 'User',

        # ── build_rapport_pdf : lignes / libellés financiers ───────────────
        'row_depots': 'Deposits',
        'row_total_encaissements': 'Total Collections',
        'row_ventes_credit': 'Credit Sales',
        'row_coupons': 'Coupons',
        'row_aucun_achat': 'No purchases',
        'row_total': 'Total',
        'row_total_recouv': 'Total ({pct}% recov.)',
        'row_total_pct_ca': 'Total ({pct}% of sales)',
        'row_creances': 'Receivables',
        'row_mvt_caisse': 'Cash Movements',
        'row_entrees_diverses': 'Misc. inflows',
        'row_sorties_diverses': 'Misc. outflows',
        'row_solde': 'Balance',
        'row_entree': 'Inflow',
        'row_sortie': 'Outflow',
        'user_unknown': 'Unknown',
        'user_systeme': 'System',

        # ── Modes de paiement (clés = codes Caisse.MODES_PAIEMENT) ─────────
        'pay_especes': 'Cash',
        'pay_cheque': 'Check',
        'pay_carte': 'Card',
        'pay_virement': 'Transfer',
        'pay_om': 'Orange Money',
        'pay_momo': 'Mobile Money',
        'pay_coupon': 'Coupon',
        'pay_en_compte': 'On account',
        'pay_depot': 'Deposit',
        'pay_recouvrement': 'Recovery',

        # ── valeur_stock_pdf (inventory.py) ────────────────────────────────
        'stock_type_pharmacie': ' - PHARMACY (excl. misc.)',
        'stock_doc_title': 'STOCK VALUE{suffix} ({valo})',
        'stock_doc_title_divers': 'STOCK VALUE — MISC. ({valo})',
        'stock_valo_pmp': 'AVG. COST',
        'stock_valo_vente': 'SALE PRICE',
        'stock_type_label_pmp': 'PURCHASE COST (AVG.)',
        'stock_type_label_vente': 'RETAIL PRICE (incl. tax)',
        'stock_recap_title': 'GENERAL SUMMARY — {label}',
        'stock_col_methode': 'VALUATION METHOD',
        'stock_col_montant': 'COMPUTED AMOUNT',
        'stock_row_ht': 'Total Value (excl. tax)',
        'stock_row_tva': 'Total VAT Amount',
        'stock_row_total': 'TOTAL VALUE ({valo})',
        'stock_tva_title': 'DETAILED BREAKDOWN BY VAT RATE',
        'stock_col_taux_tva': 'VAT Rate',
        'stock_col_base_ht': 'Net Base',
        'stock_col_montant_tva': 'VAT Amount',
        'stock_col_total_reconstitue': 'Computed Total',
        'stock_note': '<b>Accounting note:</b> This valuation is {desc}',
        'stock_desc_pmp': 'based on the weighted average cost stored in the database.',
        'stock_desc_vente': 'based on current retail prices.',

        # ── Libellés génériques de documents ─────────────────────────────────
        'doc_tel': 'Tel: {v}',
        'doc_edited': 'Generated: {d}',
        'doc_generated': 'Generated on {d}',
        'doc_period': ' | Period: {d} → {f}',
        'doc_at': 'at',
        'col_statut': 'Status',
        'col_libelle': 'Description',
        'col_designation': 'Description',
        'col_reference': 'Reference',
        'col_lot': 'Lot No.',
        'col_lot_simple': 'Lot',
        'col_stock': 'Stock',
        'col_rayon': 'Shelf',
        'col_forme': 'Form',
        'col_heure': 'Time',
        'col_caisse': 'Till',
        'col_description': 'Description',
        'col_montant_f': 'Amount (F)',
        'col_montant_ht': 'Net Amount (F)',
        'col_montant_ttc': 'Amount (incl. tax)',
        'col_montant_total': 'Total Amount (F)',
        'col_total_ht': 'Net Total',
        'col_total_tva': 'Total VAT',
        'col_total_ttc': 'Total (incl. tax)',
        'col_remise': 'Discount',
        'col_num_facture': 'Invoice No.',
        'col_facture': 'Invoice',
        'col_facture_num': 'Invoice #',
        'col_num_avoir': 'Credit Note No.',
        'col_nb_factures': '# Invoices',
        'col_rang': 'Rank',
        'col_vendeur': 'Salesperson',
        'col_caissier': 'Cashier',
        'col_mode_paiement': 'Payment Method',
        'col_quantite': 'Quantity',
        'col_prix': 'Price',
        'col_prix_vente': 'Sale Price',
        'col_prix_achat': 'Purchase Price',
        'col_nom': 'Name',
        'col_numero': 'Number',
        'col_panier_moyen': 'Avg. Basket',
        'col_pct_ca': '% / Sales',
        'col_detail': 'Detail',
        'col_observation': 'Note',
        'col_saisi_par': 'Entered by',
        'col_cree_par': 'Created by',
        'col_annule_par': 'Cancelled by',
        'col_taux_marge': 'Margin %',
        'col_qte_vendue': 'Qty sold',
        'col_ca_ttc_f': 'Sales incl. tax (F)',
        'col_cout_achat': 'Purchase cost (F)',
        'col_marge_f': 'Margin (F)',
        'col_total_commande': 'Total Ordered (F)',
        'col_total_paye': 'Total Paid (F)',
        'col_solde_du': 'Balance Due (F)',
        'col_echu': 'Overdue (F)',
        'col_a_venir': 'Upcoming (F)',
        'col_prochaine_ech': 'Next due date',
        'col_paye_f': 'Paid (F)',
        'col_restant_du': 'Remaining Due (F)',
        'col_jours_retard': 'Days late (max)',
        'col_nb_refs': '# Items',
        'col_qte_totale': 'Total qty',
        'col_valeur_pmp': 'Stock Value avg. cost (F)',
        'col_stock_min': 'Min. stock',
        'col_alertes_rupture': 'Stockout alerts',
        'col_alertes_peremption': 'Expiry alerts',
        'col_nb_commandes': '# Orders',
        'col_precompte': 'Levy (F)',
        'col_nb_avoirs': '# Credit notes',
        'col_montant_avoirs': 'Credit Notes (F)',
        'col_net': 'Net (F)',
        'col_ug_recues': 'FU received',
        'col_ug_vendues': 'FU sold',
        'col_ug_restantes': 'FU remaining',
        'col_lot_num': 'Lot #',
        'col_caisse_vendeur': 'Till / Cashier',
        'col_heure_ouv': 'Opening time',
        'col_heure_ferm': 'Closing time',
        'col_ventes_f': 'Sales (F)',
        'col_ventes': 'Sales',
        'col_entrees_f': 'Inflows (F)',
        'col_sorties_f': 'Outflows (F)',
        'col_montant_theo': 'Expected amount (F)',
        'col_montant_reel': 'Actual amount (F)',
        'col_ecart_f': 'Variance (F)',
        'col_remise_globale': 'Global Discount',
        'col_remise_lignes': 'Line Discounts',
        'col_remise_fidelite': 'Loyalty Discount',
        'col_total_remise': 'Total Discount',
        'xcol_remise_globale': 'Global Discount (F)',
        'xcol_remise_lignes': 'Line Discounts (F)',
        'xcol_fidelite': 'Loyalty (F)',
        'xcol_total_remise': 'Total Discount (F)',
        'col_chiffre_affaires': 'Revenue',
        'col_id_produit': 'Product ID',
        'col_nom_produit': 'Product Name',
        'col_nb_ruptures': 'Stockout Count',
        'col_qte_change': 'Qty Change',
        'col_valorisation': 'Valuation',
        'col_facture_origine': 'Original Invoice',
        'col_nb_lignes': '# Lines',
        'col_om': 'OM',
        'col_momo': 'MOMO',
        'col_valeur_stock': 'Stock Value',
        'col_derniere_vente': 'Last Sale',
        'col_part': 'Share (%)',
        'col_total_jour': 'Day total (F)',
        'col_date_annulation': 'Cancellation date',
        'col_qte_retournee': 'Qty returned',
        'col_nb_mouvements': '# Movements',
        'col_panier_moyen_f': 'Avg. Basket (F)',
        'col_remises_acc': 'Discounts granted (F)',
        'col_taux_remise': 'Discount rate %',
        'col_annulations': 'Cancellations',
        'col_semaine': 'Week',
        'col_encaissements': 'Collections (F)',
        'col_depenses_f': 'Expenses (F)',
        'col_achats_f': 'Supplier purchases (F)',
        'col_solde_net': 'Net weekly balance (F)',
        'col_solde_cumule': 'Cumulative balance (F)',
        'col_qte_detruite': 'Qty destroyed',
        'col_pmp_f': 'Avg. cost (F)',
        'col_valeur_perdue': 'Value lost (F)',
        'col_promotion': 'Promotion',
        'col_valeur_remise': 'Value / Discount',
        'col_date_debut': 'Start date',
        'col_date_fin': 'End date',
        'col_nb_produits': '# Products',
        'col_ca_mois': 'Monthly sales (F)',
        'col_encours': 'Total outstanding (F)',
        'col_plafond': 'Credit limit (F)',
        'col_taux_util': 'Utilization %',
        'user_system': 'System',
        'client_passage': 'Walk-in customer',
        'client_passage_short': 'Walk-in',
        'client_comptant': 'Cash sale',
        'client_inconnu': 'Unknown client',
        'produit_inconnu': 'Unknown product',
        'company_fallback': 'Company',
        'grp_sans_rayon': 'No Shelf',
        'grp_sans_forme': 'No Form',
        'grp_sans_groupe': 'No Group',
        'grp_sans_fournisseur': 'NO SUPPLIER',
        'grp_autres': 'OTHER',
        'grp_non_classe': 'Unclassified',
        'grp_sans_rayon_paren': '(No shelf)',
        'val_divers': 'Misc.',
        'val_pharmacie': 'Pharmacy',
        'val_jamais': 'Never',
        'pay_cb': 'Bank card',
        'pay_mobile_money': 'Mobile Money',
        'pay_assurance': 'Insurance / Third-party payer',
        'pay_fidelite': 'Loyalty Points',

        # ── invoice_pdf.py (PDF facture) ─────────────────────────────────────
        'inv_facture': 'INVOICE',
        'inv_proforma': 'PROFORMA',
        'inv_lbl_invoice_no': 'Invoice No.:',
        'inv_lbl_n_facture': 'Invoice No.:',
        'inv_lbl_date': 'Date:',
        'inv_lbl_statut': 'Status:',
        'inv_lbl_tel': 'Tel:',
        'inv_lbl_client': 'Client:',
        'inv_col_pu': 'Unit Price',
        'inv_subtotal': 'Subtotal:',
        'inv_tva': 'VAT:',
        'inv_remise': 'Discount:',
        'inv_total_payer': 'TOTAL DUE:',
        'inv_total_ttc_lbl': 'Total (incl. tax):',
        'inv_page': 'Page {n}',

        # ── creances.py (reçu, relevé, export Excel) ─────────────────────────
        'cre_sheet': 'Receivables',
        'cre_col_client_assurance': 'Client / Insurance',
        'cre_col_beneficiaire': 'Beneficiary',
        'cre_col_paye': 'Amount Paid',
        'cre_col_reste': 'Balance Due',
        'cre_title': 'Receivables Listing',
        'cre_title_history': ' — History',
        'cre_title_pending': ' — Pending',
        'cre_period_between': ' ({d} to {f})',
        'cre_period_from': ' (from {d})',
        'cre_period_until': ' (until {f})',
        'cre_status_paid': 'Paid',
        'cre_status_pending': 'Pending',
        'cre_total_line': 'TOTAL ({n} invoice(s))',
        'recu_title': 'PAYMENT RECEIPT',
        'recu_lbl_facture': 'Invoice No.:',
        'recu_lbl_date_paiement': 'Payment date:',
        'recu_lbl_mode': 'Payment method:',
        'recu_lbl_beneficiaire': 'Beneficiary:',
        'recu_dette_avant': 'Balance before payment',
        'recu_montant_paye': 'AMOUNT PAID TODAY',
        'recu_reste': 'BALANCE DUE',
        'recu_thanks': 'Thank you for your trust.',
        'releve_title': 'PAYMENT SUMMARY',
        'releve_lbl_reference': 'Reference:',
        'releve_total': 'TOTAL PAYMENT:',

        # ── etat_inventaire.py (PDF état d'inventaire) ───────────────────────
        'einv_title_grouped': 'INVENTORY REPORT BY {g}',
        'einv_title_filtered': 'INVENTORY REPORT - {g}: {name}',
        'einv_group_forme': 'FORM',
        'einv_group_rayon': 'SHELF',
        'einv_group_groupe': 'GROUP',
        'einv_stock_machine': 'System Stock',
        'einv_stock_nonzero': 'Non-Zero Stock',
        'einv_stock_zero': 'Zero Stock',
        'einv_option_line': 'Option: {opt} | Printed on {d}',
        'einv_col_pv': 'Price',
        'einv_col_qte_phys': 'Physical Qty',
        'einv_products_count': '({n} products)',

        # ── ordonnancier_view.py ─────────────────────────────────────────────
        'ord_title': '📋 PRESCRIPTION REGISTER',
        'ord_col_patient': 'Patient',
        'ord_col_presc': 'Prescriber',
        'ord_col_meds': 'Medications',
        'ord_col_surv': 'Monit.',
        'ord_footer_total': 'Total: {n} entry(ies)',
        'ord_footer_limit': ' (limited to {n})',

        # ── inventaire/pdf.py (écarts + état + print data) ───────────────────
        'invd_ecarts_title': 'DISCREPANCY REPORT - #{id}',
        'invd_date': 'Date: {d}',
        'invd_no_ecart': 'No discrepancy found.',
        'invd_rayon_prefix': 'SHELF: {r}',
        'invd_col_theo': 'Theo.',
        'invd_col_phys': 'Phys.',
        'invd_col_ecart': 'Var.',
        'invd_col_val': 'Val.',
        'invd_total_ecarts': 'GRAND TOTAL VARIANCE (VALUE): {v} F',
        'invd_etat_title': 'INVENTORY REPORT #{id}',
        'invd_desc': 'Description: {d}',
        'invd_report_title': 'INVENTORY REPORT',
        'invd_sheet_title': 'INVENTORY COUNT SHEET',
        'invd_ref_desc': 'Ref: #{id} - {desc}',
        'invd_ref': 'Ref: #{id}',

        # ── reappro_history.py ───────────────────────────────────────────────
        'reap_title': 'RESTOCKING SESSION #{id}',
        'reap_by': 'Performed by: {v}',
        'reap_volume': 'Total volume: {u} units ({p} products)',
        'reap_col_expiry': 'EXPIRY',
        'reap_empty': 'No product recorded for this session.',
        'reap_doc_title': 'RESTOCKING CONFIRMATION',

        # ── pdf_generation.py (étiquettes commandes) ─────────────────────────
        'lbl_fact_prefix': 'Inv:{v}',

        # ── promis.py (tickets) ──────────────────────────────────────────────
        'prm_ticket_title': 'PROMISE TICKET',
        'prm_copy_pharmacy': 'PHARMACY COPY',
        'prm_copy_client': 'CUSTOMER COPY',
        'prm_client': 'CUSTOMER:',
        'prm_tel': 'Tel: {v}',
        'prm_produit': 'PROMISED PRODUCT:',
        'prm_quantite': 'Quantity: {n}',
        'prm_keep1': 'Keep this ticket as proof',
        'prm_keep2': 'of your reservation.',
        'prm_statut': 'Status: {s}',
        'prm_cut': '✂ CUT HERE ✂',
        'prm_group_title': 'PROMISE TICKET (BACKORDER)',
        'prm_keep_group': 'Please keep this ticket to collect your products.',

        # ── categories.py (PDF état de stock par rayon) ──────────────────────
        'cat_title_rayon': 'STOCK REPORT - SHELF: {name}',
        'cat_title_sans': 'STOCK REPORT - NO SHELF',
        'cat_nonzero': ' (Non-Zero)',
        'cat_tot': 'Tot: {n}',

        # ── inventaire/listing_excel.py ──────────────────────────────────────
        'lx_sheet_stock': 'Stock Listing (Lots)',
        'lx_sheet_inv': 'Inventory Listing',
        'lx_sheet_blind': 'Blind Inventory Listing',
        'lx_grp_forme': 'Dosage form',
        'lx_grp_groupe': 'Therapeutic group',
        'lx_flt_tous': 'All stock',
        'lx_flt_zero': 'Zero stock (Qty = 0)',
        'lx_flt_nonzero': 'Non-zero stock (Qty > 0)',
        'lx_col_stock_theo': 'Theo. Stock',
        'lx_col_qte_comptee': 'Counted Qty',
        'lx_col_ecart': 'Variance',
        'lx_col_val_ecart': 'Var. Value',
        'lx_col_stock_res': 'Reserve Stk',
        'lx_col_stock_rayon': 'Shelf Stock',
        'lx_col_val_stock': 'Stock Value',
        'lx_col_exp_lot': 'Lot Exp.',
        'lx_title': 'STOCK INVENTORY LISTING',
        'lx_src_stock': 'Current stock (by lot)',
        'lx_src_inv': 'Inventory',
        'lx_src_blind': 'Blind inventory (no system stock)',
        'lx_src_default': 'Current stock',
        'lx_info_line': 'Generated: {now}  |  Source: {src}  |  Grouping: {grp}  |  Filter: {flt}',
        'lx_subtotal': '  Total {g}  —  {r} ref.  |  {l} lot(s)  |  {s} pack(s)',
        'lx_grand_total': '  GRAND TOTAL  ({r} ref. / {l} lot(s))',

        # ── excel_general.py (rapport mensuel multi-feuilles) ────────────────
        'xs_sheet_synthese': 'Summary',
        'xs_sheet_ca_marges': 'Sales & Margins',
        'xs_sheet_remises': 'Discounts & Credit Notes',
        'xs_sheet_top': 'Top Products',
        'xs_sheet_dettes': 'Supplier Debts',
        'xs_sheet_creances': 'Customer Receivables',
        'xs_sheet_stock': 'Stock & Inventory',
        'xs_sheet_fiscal': 'Tax Summary',
        'xs_sheet_ugs': 'Free Units',
        'xs_sheet_achats': 'Supplier Purchases',
        'xs_sheet_caisses': 'Cash Registers',
        'xs_sheet_depenses': 'Expenses',
        'xs_t_synthese': 'MONTHLY SUMMARY — {mois}',
        'xs_t_ca': 'DAILY SALES & MARGINS — {mois}',
        'xs_t_remises': 'DISCOUNTS & CREDIT NOTES — {mois}',
        'xs_t_top': 'TOP PRODUCTS — {mois}',
        'xs_t_dettes': 'SUPPLIER DEBTS — {mois}',
        'xs_t_creances': 'CUSTOMER RECEIVABLES — {mois}',
        'xs_t_stock': 'STOCK & INVENTORY — {mois}',
        'xs_t_fiscal': 'TAX SUMMARY — {mois}',
        'xs_t_ugs': 'FREE UNITS — {mois}',
        'xs_t_achats': 'SUPPLIER PURCHASES — {mois}',
        'xs_t_caisses': 'CASH REGISTERS — {mois}',
        'xs_t_depenses': 'EXPENSES — {mois}',
        'xs_r_ca_pharma_ttc': 'PHARMACY SALES (incl. tax)',
        'xs_r_ca_divers_ttc': 'MISC. SALES (incl. tax)',
        'xs_r_ca_total_ttc': 'TOTAL SALES (incl. tax)',
        'xs_r_marge_pharma': 'Pharmacy gross margin',
        'xs_r_taux_pharma': 'Pharmacy margin rate',
        'xs_r_marge_divers': 'Misc. gross margin',
        'xs_r_marge_totale': 'TOTAL gross margin',
        'xs_r_taux_total': 'TOTAL margin rate',
        'xs_r_remises': 'Discounts granted',
        'xs_r_rem_glob': '  incl. global discounts',
        'xs_r_rem_lignes': '  incl. line discounts',
        'xs_r_rem_fid': '  incl. loyalty',
        'xs_r_nb_ventes': 'Number of sales',
        'xs_r_panier': 'Avg. basket (incl. tax)',
        'xs_r_creances': 'Customer receivables',
        'xs_r_dettes': 'Supplier debts',
        'xs_col_indicateur': 'Indicator',
        'xs_col_montant_valeur': 'Amount / Value',
        'xsc_ca_pharma': 'Pharmacy Sales (incl. tax)',
        'xsc_ca_divers': 'Misc. Sales (incl. tax)',
        'xsc_ca_total': 'Total Sales (incl. tax)',
        'xsc_marge_pharma': 'Pharmacy Margin',
        'xsc_marge_divers': 'Misc. Margin',
        'xsc_marge_totale': 'Total Margin',
        'xs_sec_remises': 'DISCOUNTS GRANTED',
        'xs_sec_avoirs': 'SUPPLIER CREDIT NOTES',
        'xs_sec_resume': 'SUMMARY',
        'xs_sec_recap': 'GENERAL SUMMARY',
        'xs_caissier': 'CASHIER: {nom}',
        'fis_regime': 'Tax regime',
        'fis_mode': 'Taxation mode',
        'fis_ca': 'REVENUE',
        'fis_tva': 'VAT collected',
        'fis_achats': 'PURCHASES & LEVY',
        'fis_total_achats': 'Total purchases (excl. tax)',
        'fis_taux_precompte': 'Levy rate ({regime})',
        'fis_total_precompte': 'Total levy',
        'fis_precompte_na': 'Levy (not applicable under Managed Margin)',
        'fis_accompte': 'INSTALLMENT (on sales)',
        'fis_base_marge': 'Gross margin',
        'fis_base_ca': 'Revenue (excl. tax)',
        'fis_accompte_base': 'Base installment',
        'fis_cac': 'CAC ({t}%)',
        'fis_accompte_total': 'Total installment',
        'ug_total_recues': 'Total FU received (purchases)',
        'ug_total_vendues': 'Total FU sold (with invoices)',
        'ug_total_restantes': 'Total FU remaining (in stock)',
        'ug_taux_rotation': 'FU turnover rate',
        'dep_total_sorties': 'Total OUTFLOWS (expenses)',
        'dep_total_entrees': 'Total INFLOWS',
        'dep_solde': 'BALANCE',

        # ── excel_general_extra.py ───────────────────────────────────────────
        'xe_sheet_modes': 'Payment Methods',
        'xe_t_modes': 'PAYMENT METHODS — {mois}',
        'xe_sec_recap': 'GLOBAL SUMMARY',
        'xe_sec_cloture': 'DETAIL PER CASH CLOSURE (JSON)',
        'xe_sec_evo_mode': 'DAILY BREAKDOWN BY METHOD',
        'xe_sec_evo': 'VS PREVIOUS MONTH',
        'xe_ca_cur': 'Current month sales',
        'xe_ca_prev': 'Previous month sales',
        'xe_var_ca': 'Sales change',
        'xe_marge_cur': 'Current month margin',
        'xe_marge_prev': 'Previous month margin',
        'xe_var_marge': 'Margin change',
        'xe_nb_cur': 'Current month # sales',
        'xe_nb_prev': 'Previous month # sales',
        'xe_var_nb': 'Sales count change',
        'xe_sec_obj': 'SALES TARGET',
        'xe_obj_ca': 'Monthly sales target',
        'xe_ca_realise': 'Sales achieved',
        'xe_taux': 'Achievement rate',
        'xe_ecart_obj': 'Target gap',
        'xe_sheet_retours': 'Returns & Cancellations',
        'xe_t_retours': 'RETURNS & CANCELLATIONS — {mois}',
        'xe_sec_fact_ann': 'CANCELLED INVOICES',
        'xe_no_ann': 'No cancellations this month',
        'xe_sec_retours': 'MOST RETURNED PRODUCTS (MouvementStock)',
        'xe_no_retour': 'No returns recorded this month',
        'xe_sheet_perf': 'Sales Rep Performance',
        'xe_t_perf': 'SALES REP PERFORMANCE — {mois}',
        'xe_no_perf': 'No salesperson data for this period',
        'xe_sheet_treso': 'Cash Flow Tracking',
        'xe_t_treso': 'CASH FLOW TRACKING — {mois}',
        'xe_sec_projection': 'NEXT MONTH PROJECTION',
        'xe_creances_recouvrer': 'Receivables to collect (balance due)',
        'xe_solde_net': 'Net cash flow for the month',
        'xe_treso_prev': 'Projected cash position',
        'xe_sheet_perimes': 'Expired & Losses',
        'xe_t_perimes': 'EXPIRED & LOSSES — {mois}',
        'xe_no_perime': 'No expired items recorded this month',
        'xe_sheet_promos': 'Promotions',
        'xe_t_promos': 'ACTIVE PROMOTIONS — {mois}',
        'xe_no_promo': 'No active promotions this month',
        'xe_sheet_clients_pro': 'Business Clients & Insurers',
        'xe_t_clients_pro': 'BUSINESS CLIENTS & INSURERS — {mois}',
        'xe_no_client_pro': 'No active business clients this month',

        # ── finance.py (CSV comptable, Excel remises, livre de caisse) ───────
        'fin_sheet_remises_details': 'Discount Details',
        'fin_t_remises_details': 'Discount Detail per Invoice',
        'fin_sheet_remises': 'Discounts',
        'fin_t_remises': 'Discount Report by User',
        'fin_sheet_livre': 'Cash Book',
        'fin_t_livre': 'Cash Book — {d} to {f}',
        'fin_periode': 'Period: {d} to {f}',
        'col_entrees_man': 'Manual inflows',
        'col_sorties_man': 'Manual outflows',
        'col_solde_jour': 'Daily balance',
        'fin_total_general': 'GRAND TOTAL',
        'fin_sheet_detail': 'Transaction Detail',
        'fin_t_detail': 'Transaction Detail — {d} to {f}',
        'col_facture_ref': 'Invoice No. / Ref.',
        'col_type_op': 'Operation type',
        'col_rubrique': 'Category / Method',
        'col_motif_desc': 'Reason / Description',
        'col_sens': 'Direction',
        'op_vente': 'Sale',
        'op_entree_man': 'Manual inflow',
        'op_sortie_man': 'Manual outflow',
        'op_credit': 'Credit',
        'op_debit': 'Debit',
        'fin_sous_total': 'Subtotal {d}',
        'fin_total_credit': 'TOTAL CREDIT',
        'fin_total_debit': 'TOTAL DEBIT',
        'fin_solde_net': 'NET BALANCE',

        # ── audit.py / sales.py / ruptures.py / adjustments.py / autres ─────
        'aud_col_datetime': 'Date/Time',
        'aud_col_action': 'Action',
        'aud_col_modele': 'Model',
        'aud_col_objet': 'Object',
        'adj_sheet': 'Stock Adjustments',
        'adj_title': 'Stock Adjustments Log',
        'avo_sheet': 'Customer Credit Notes',
        'hv_sheet': 'Sales History',
        'bal_title': '{title} - {d} to {f}',

        # ── commandes/export.py ──────────────────────────────────────────────
        'cmd_sans_cip': '--- PRODUCTS WITHOUT CIP ---',
        'cmd_txt_head': 'Order #{id} - Supplier: {f}',
        'cmd_cip_demande': 'Requested CIP: {c}',
        'cmd_sans_cip_txt': 'PRODUCTS WITHOUT CIP (enter manually):',
    },
}


def T(lang: str, key: str, **kwargs) -> str:
    """
    Retourne la chaîne traduite pour ``key`` dans ``lang``.

    Fallback : table 'fr', puis la clé elle-même si absente partout.
    Les placeholders ``{nom}`` sont remplacés via ``**kwargs`` (str.format).
    """
    table = DOC_STRINGS.get(lang) or DOC_STRINGS['fr']
    s = table.get(key, DOC_STRINGS['fr'].get(key, key))
    if kwargs:
        try:
            return s.format(**kwargs)
        except Exception:
            return s
    return s


def format_doc_date(value, lang: str = 'fr', with_time: bool = False) -> str:
    """
    Formate une date/datetime selon la langue du document :
    ``jj/mm/aaaa`` en français, ``mm/dd/yyyy`` en anglais.

    Retourne ``str(value)`` en dernier recours.
    """
    fmt = '%m/%d/%Y' if lang == 'en' else '%d/%m/%Y'
    if with_time:
        fmt += ' %H:%M'
    try:
        return value.strftime(fmt)
    except Exception:
        return str(value)
