# Generated by Django 5.2.5 on 2025-08-18 23:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='price',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fournisseur'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rayon'),
        ),
    ]
