# Generated by Django 5.2.5 on 2025-12-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_can_do_returns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte'), ('virement', 'Virement'), ('en_compte', 'En compte')], max_length=20),
        ),
    ]
