# Generated by Django 5.2.5 on 2025-12-15 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_mouvementcaisse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_avoir', models.CharField(choices=[('PERIME', 'Produit périmé'), ('AVARIE', 'Produit avarié'), ('NON_FACTURE', 'Livré non facturé'), ('ERREUR', 'Erreur de livraison'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_created', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='api.fournisseur')),
            ],
            options={
                'verbose_name': 'Avoir fournisseur',
                'verbose_name_plural': 'Avoirs fournisseurs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneAvoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix de retour', max_digits=10)),
                ('lot', models.CharField(blank=True, max_length=100)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('avoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.avoir')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produit')),
            ],
            options={
                'verbose_name': "Ligne d'avoir",
                'verbose_name_plural': "Lignes d'avoir",
            },
        ),
    ]
