# Generated by Django 5.2.5 on 2025-12-17 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_avoir_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=2, help_text='Ratio de conversion (ex: 20.00 si 1 boîte = 20 détails)', max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit_destination', models.ForeignKey(help_text='Produit résultant (ex: DETAIL)', on_delete=django.db.models.deletion.CASCADE, related_name='transformations_destination', to='api.produit')),
                ('produit_source', models.ForeignKey(help_text='Produit à transformer (ex: BOITE)', on_delete=django.db.models.deletion.CASCADE, related_name='transformations_source', to='api.produit')),
            ],
            options={
                'verbose_name': 'Relation de transformation',
                'verbose_name_plural': 'Relations de transformation',
                'unique_together': {('produit_source', 'produit_destination')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_source', models.IntegerField(help_text='Quantité transformée (source)')),
                ('quantite_destination', models.IntegerField(help_text='Quantité obtenue (destination)')),
                ('date_transformation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('produit_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist_trans_dest', to='api.produit')),
                ('produit_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist_trans_source', to='api.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.relationtransformation')),
            ],
            options={
                'verbose_name': 'Historique de transformation',
                'verbose_name_plural': 'Historiques de transformations',
                'ordering': ['-date_transformation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (Commande)'), ('SORTIE', 'Sortie (Vente)'), ('RETOUR', 'Retour (Annulation)'), ('AJUSTEMENT', 'Ajustement Inventaire'), ('TRANSFORMATION_ENTREE', 'Transformation (Entrée)'), ('TRANSFORMATION_SORTIE', 'Transformation (Sortie)')], max_length=30)),
                ('quantite', models.IntegerField(help_text='Quantité mouvementée (positive ou négative)')),
                ('stock_apres', models.IntegerField(blank=True, help_text='Stock après mouvement (snapshot)', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='api.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['produit', 'date'], name='api_mouveme_produit_91e775_idx')],
            },
        ),
    ]
