# Generated by Django 5.2.5 on 2025-12-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_client_is_loyalty_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
