# Generated by Django 5.2.5 on 2025-12-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_label_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TVA applicable à cette ligne (copiée du produit lors de la création)', max_digits=5),
        ),
    ]
