# Generated by Django 5.2.5 on 2026-01-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='part_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part à payer par le client (Tiers Payant)', max_digits=12, null=True),
        ),
    ]
