# Generated by Django 5.2.5 on 2026-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_stock_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason_detail',
            field=models.TextField(blank=True, default='', help_text='Note optionnelle'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason_type',
            field=models.CharField(choices=[('INVENTAIRE', 'Ajustement inventaire'), ('CASSE', 'Cassé'), ('VOL', 'Vol'), ('CONFUSION', 'Confusion'), ('ERR_ENTREE', "Erreur d'entrée en stock"), ('AVARIE', 'Avarié'), ('USAGE_INT', 'Usage interne')], max_length=10),
        ),
    ]
