# Generated by Django 5.2.5 on 2026-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_produit_is_public_produit_public_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='type',
            field=models.CharField(choices=[('STD', 'Standard'), ('RETRO', 'Rétrocession')], default='STD', help_text='Type de facture (Standard ou Rétrocession)', max_length=5),
        ),
        migrations.AddField(
            model_name='produit',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dernier prix d'achat unitaire (pour rétrocessions)", max_digits=10, null=True),
        ),
    ]
