# Generated by Django 5.2.5 on 2026-01-31 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_configurationoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduit',
            name='free_quantity',
            field=models.IntegerField(default=0, help_text='Unités gratuites (Promotion)'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de la promotion (ex: Soldes d'été)", max_length=200)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Pourcentage (%)'), ('FIXED_AMOUNT', 'Montant Fixe (F)'), ('BUY_X_GET_Y', 'Acheter X, Recevoir Y')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Valeur de la remise (en % ou en F)', max_digits=10)),
                ('buy_quantity', models.IntegerField(default=1, help_text='Quantité minimale à acheter pour déclencher la promo')),
                ('get_quantity', models.IntegerField(default=0, help_text='Quantité offerte (pour Buy X Get Y)')),
                ('priority', models.IntegerField(default=1, help_text="Priorité d'application (plus élevé = prioritaire)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='api.produit')),
                ('rayons', models.ManyToManyField(blank=True, related_name='promotions', to='api.rayon')),
            ],
        ),
    ]
