# Generated by Django 5.2.5 on 2026-02-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_ticketsessionsequence_facture_ticket_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_cancel_invoice',
            field=models.BooleanField(default=False, verbose_name='Annuler des factures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_cancel_promis',
            field=models.BooleanField(default=False, verbose_name='Annuler des promis'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_avoirs',
            field=models.BooleanField(default=False, verbose_name='Gérer les avoirs fournisseurs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_perimes',
            field=models.BooleanField(default=False, verbose_name='Gérer les produits périmés'),
        ),
    ]
