# Generated by Django 5.2.5 on 2026-02-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_factureproduit_treatment_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='capacite_rayon',
            field=models.IntegerField(default=0, help_text="Capacité maximale d'exposition en rayon"),
        ),
        migrations.AddField(
            model_name='produit',
            name='has_reserve_storage',
            field=models.BooleanField(default=False, help_text='Active la gestion Réserve / Rayon pour ce produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='min_rayon',
            field=models.IntegerField(default=0, help_text='Seuil de déclenchement du réapprovisionnement'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_reserve',
            field=models.IntegerField(default=0, help_text='Quantité totale en réserve (stock tampon)'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='quantity_reserved',
            field=models.IntegerField(default=0, help_text='Quantité en réserve pour ce lot'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity_remaining',
            field=models.IntegerField(help_text='Quantité restante en rayon'),
        ),
        migrations.AlterField(
            model_name='whatsapplog',
            name='type',
            field=models.CharField(choices=[('FACTURE', 'Envoi Facture'), ('PROMIS', 'Disponibilité Promis'), ('MANUEL', 'Envoi Manuel'), ('RAPPEL', 'Rappel Paiement'), ('RENOUVELLEMENT', 'Renouvellement Traitement')], default='FACTURE', max_length=20),
        ),
    ]
