# Generated by Django 5.2.5 on 2026-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_alter_mouvementstock_type_mouvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
