# Generated by Django 5.2.5 on 2026-03-08 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_alter_produit_cost_price_alter_produit_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturecaisse',
            name='cloture_par',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur (admin) ayant effectué la clôture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Le caissier dont la caisse est clôturée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL),
        ),
    ]
