# Generated by Django 5.2.5 on 2026-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_client_solde_depot_alter_caisse_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_deposit_enabled',
            field=models.BooleanField(default=False, help_text='Si activé, ce client peut utiliser le système de dépôt'),
        ),
    ]
