# Generated by Django 6.0.3 on 2026-04-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_alter_produit_cip1_alter_produit_cip2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_validate_zero_amount',
            field=models.BooleanField(default=False, verbose_name='Valider des ventes à montant nul ou négatif'),
        ),
    ]
