# Generated by Django 6.0.3 on 2026-04-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_invoicesettings_is_multi_caisse_postecaisse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturecaisse',
            name='poste_caisse',
            field=models.ForeignKey(blank=True, help_text='Le poste de caisse physique associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures', to='api.postecaisse'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='poste_caisse',
            field=models.ForeignKey(blank=True, help_text='Caisse sur laquelle le mouvement est effectué', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='api.postecaisse'),
        ),
    ]
