# Generated by Django 6.0.3 on 2026-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_orderschedule_analysis_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='source',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('AUTO', 'Planification auto')], default='MANUEL', help_text='Origine de la commande (manuelle ou auto-générée)', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='execution_mode',
            field=models.CharField(choices=[('SIMPLE', 'Remplacement des ventes (Simple)'), ('OPTIMISE', 'Analyse prédictive (Intelligent)'), ('CUMULATIF', 'Cumulatif depuis dernière commande')], default='OPTIMISE', max_length=10),
        ),
    ]
