# Generated by Django 5.2.14 on 2026-06-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_remove_commande_cmd_fourn_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_cash_sessions',
            field=models.BooleanField(default=False, verbose_name="Voir l'historique des sessions de caisse"),
        ),
    ]
