# Generated by Django 5.2.5 on 2026-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_profile_can_view_cash_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='taux_change_actif',
            field=models.DecimalField(decimal_places=3, default=655.957, help_text='Taux de change actif pour les commandes directes (Euro -> FCFA). Source de vérité unique.', max_digits=10),
        ),
    ]
