# Generated by Django 6.0.3 on 2026-07-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_add_marge_objectif_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='disabled_payment_modes',
            field=models.JSONField(blank=True, default=list, help_text="Liste des modes de paiement désactivés (ex: ['cheque', 'virement'])"),
        ),
    ]
