# Generated by Django 5.2.15 on 2026-07-25 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0226_planning_operateurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^$|^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^$|^\\+?1?\\d{9,15}$')]),
        ),
    ]
