# Generated by Django 5.2.16 on 2026-08-13 20:31
#
# ⚠️ atomic = False : nécessaire pour CREATE INDEX CONCURRENTLY
# (PostgreSQL interdit CREATE INDEX CONCURRENTLY dans une transaction).
# Les AlterField sont des opérations rapides sur des colonnes existantes
# (ajout de db_index=True), le risque sans transaction est minimal.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False  # CREATE INDEX CONCURRENTLY ne peut pas être dans une transaction

    dependencies = [
        ('api', '0230_historiquetransformation_reversed_reversed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('PROFESSIONNEL', 'Professionnel')], db_index=True, default='PARTICULIER', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Client actif (visible dans les recherches)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Commande active (non supprimée dans la corbeille)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('PREP', 'En préparation'), ('ATT', 'En attente'), ('CLOT', 'Clôturée')], db_index=True, default='PREP', max_length=10),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Fournisseur actif (visible dans les recherches)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Produit actif (visible dans les recherches)'),
        ),
        # Index composites sur Facture — CREATE INDEX CONCURRENTLY pour éviter
        # de bloquer les écritures pendant la création (important en prod avec
        # plusieurs milliers de factures).
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS facture_poste_status_idx ON api_facture (poste_caisse_id, status, date DESC)',
            reverse_sql='DROP INDEX IF EXISTS facture_poste_status_idx',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS facture_creator_date_idx ON api_facture (created_by_id, date DESC)',
            reverse_sql='DROP INDEX IF EXISTS facture_creator_date_idx',
        ),
    ]
