# Generated by Django 5.2.17 on 2026-09-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_loyalty_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
