export interface PharmacySettings {
    id?: number
    pharmacy_name: string
    address: string
    phone: string
    phone2?: string
    email: string
    nif?: string
    rccm?: string
    ticket_footer_message?: string
    receipt_header?: string
    pharmacist_name?: string
    show_pharmacist_on_documents?: boolean
    logo?: string
    coefficient_direct_commande?: string
    niu?: string
    registre_commerce?: string
    primary_color?: string
    secondary_color?: string
    accent_color?: string
    font_family?: string
    website?: string
    low_stock_threshold_days?: number
    dormant_stock_days?: number
    debt_alert_threshold?: string
    ticket_paper_width?: number
    currency_symbol?: string
    locale?: string
    whatsapp_enabled?: boolean
    whatsapp_access_token?: string
    whatsapp_phone_id?: string
    whatsapp_business_id?: string
    pharmacist_whatsapp_number?: string
    auto_logout_timeout?: number
    hide_cash_totals?: boolean
    billetage_obligatoire?: boolean
    // Rétention automatique (purge planifiée des données anciennes)
    retention_enabled?: boolean
    retention_audit_days?: number
    retention_activity_days?: number
    retention_message_log_days?: number
    retention_session_days?: number
    retention_trash_days?: number
    retention_draft_invoice_days?: number
    retention_mouvement_stock_days?: number
}
