import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, '..', 'src');
const versionFile = path.join(srcDir, 'version.ts');

let gitHash = 'unknown';
try {
    gitHash = execSync('git rev-parse --short HEAD', { cwd: path.join(__dirname, '..'), encoding: 'utf8' }).trim();
} catch {
    // git not available
}

const buildDate = new Date().toISOString();
const buildNumber = Date.now();

const content = `// Auto-generated by scripts/generate-version.mjs — do not edit manually
export const BUILD_VERSION = {
    hash: '${gitHash}',
    date: '${buildDate}',
    number: ${buildNumber},
    env: '${process.env.NODE_ENV || 'development'}',
};

export const formatVersion = (): string => {
    const d = new Date(BUILD_VERSION.date);
    const dateStr = d.toLocaleDateString('fr-FR', { day: '2-digit', month: '2-digit', year: 'numeric' });
    const timeStr = d.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
    return \`v\${BUILD_VERSION.hash} — \${dateStr} \${timeStr}\`;
};
`;

fs.writeFileSync(versionFile, content, 'utf8');
console.log(`✓ Version generated: ${gitHash} @ ${buildDate}`);
