# Generated by Django 5.2.5 on 2025-09-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commande_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
