# Generated by Django 5.2.5 on 2025-11-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_do_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_sell_negative_stock',
            field=models.BooleanField(default=False),
        ),
    ]
