# Generated by Django 5.2.5 on 2025-12-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_caisse_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client_name_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.client'),
        ),
    ]
