# Generated by Django 5.2.5 on 2025-12-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_client_client_type_client_plafond_ayantdroit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayantdroit',
            name='societe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='ayant_droit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='api.ayantdroit'),
        ),
    ]
