# Generated by Django 5.2.5 on 2025-12-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ayantdroit_societe_facture_ayant_droit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
