# Generated by Django 5.2.5 on 2025-12-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_produit_use_lot_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotSequence',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('last_number', models.IntegerField(default=0, help_text='Dernier numéro de séquence utilisé')),
            ],
            options={
                'db_table': 'lot_sequence',
            },
        ),
    ]
