# Generated by Django 5.2.5 on 2026-01-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_invoicesettings_centralized_cash_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PHARMACIEN', 'Pharmacien'), ('VENDEUR', 'Vendeur'), ('CAISSIER', 'Caissier')], default='VENDEUR', max_length=20),
        ),
    ]
