# Generated by Django 5.2.5 on 2026-01-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_add_auditlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
    ]
