# Generated by Django 5.2.5 on 2026-01-07 22:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_commande_date_cloture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='requires_prescription',
            field=models.BooleanField(default=False, help_text='Ce produit nécessite une ordonnance'),
        ),
        migrations.AddField(
            model_name='produit',
            name='surveillance_category',
            field=models.CharField(choices=[('NONE', 'Aucune'), ('STANDARD', 'Surveillance standard'), ('RENFORCEE', 'Surveillance renforcée')], default='NONE', help_text='Catégorie de surveillance du médicament', max_length=20),
        ),
        migrations.CreateModel(
            name='Ordonnancier',
            fields=[
                ('numero_ordre', models.AutoField(primary_key=True, serialize=False)),
                ('date_delivrance', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_nom', models.CharField(help_text='Nom du patient', max_length=200)),
                ('prescripteur_nom', models.CharField(help_text='Nom du médecin prescripteur', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnancier_entries', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnancier_entries', to='api.facture')),
            ],
            options={
                'verbose_name': 'Ordonnancier',
                'verbose_name_plural': 'Ordonnancier',
                'ordering': ['-numero_ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_nom', models.CharField(help_text='Copie du nom pour historique', max_length=200)),
                ('quantite', models.IntegerField()),
                ('surveillance_category', models.CharField(default='NONE', max_length=20)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnancier_lignes', to='api.produit')),
                ('ordonnancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.ordonnancier')),
            ],
            options={
                'verbose_name': 'Ligne Ordonnancier',
                'verbose_name_plural': 'Lignes Ordonnancier',
            },
        ),
    ]
