# Generated by Django 5.2.5 on 2026-01-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_add_dernier_achat_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_adjust_stock',
            field=models.BooleanField(default=False, verbose_name='Ajuster le stock manuellement'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_close_commande',
            field=models.BooleanField(default=False, verbose_name='Clôturer des commandes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_commande',
            field=models.BooleanField(default=False, verbose_name='Supprimer des commandes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_fournisseur',
            field=models.BooleanField(default=False, verbose_name='Supprimer des fournisseurs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_product',
            field=models.BooleanField(default=False, verbose_name='Supprimer des produits'),
        ),
    ]
