# Generated by Django 5.2.5 on 2026-01-17 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_commande_frais_coefficient_commande_taux_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklot',
            name='commande_produit',
            field=models.ForeignKey(blank=True, help_text='Référence à la ligne de commande (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_lot', to='api.commandeproduit'),
        ),
    ]
