# Generated by Django 5.2.5 on 2026-01-28 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_paiementfournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
