# Generated by Django 5.2.5 on 2026-01-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_factureproduit_free_quantity_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='application_mode',
            field=models.CharField(choices=[('AUTO_SHOW', 'Affichage automatique'), ('AUTO_SUGGEST', 'Proposition automatique'), ('AUTO_APPLY', 'Remise automatique')], default='AUTO_APPLY', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée', null=True),
        ),
    ]
