# Generated by Django 5.2.5 on 2026-01-31 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_promotion_application_mode_promotion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Pourcentage (%)'), ('FIXED_AMOUNT', 'Montant Fixe (F)'), ('BUY_X_GET_Y', 'Acheter X, Recevoir Y'), ('BUNDLE', 'Pack / Lot (Prix Fixe)')], default='PERCENTAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur de la remise (en % ou en F) ou Prix Total du Pack', max_digits=10),
        ),
        migrations.CreateModel(
            name='PromotionPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantité requise dans le pack')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='api.promotion')),
            ],
            options={
                'unique_together': {('promotion', 'product')},
            },
        ),
    ]
