# Generated by Django 5.2.5 on 2026-02-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_facture_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Client actif (visible dans les recherches)'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Fournisseur actif (visible dans les recherches)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Produit actif (visible dans les recherches)'),
        ),
    ]
