# Generated by Django 5.2.5 on 2026-02-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_pharmacysettings_central_server_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='currency_symbol',
            field=models.CharField(default='FCFA', help_text='Symbole de la devise (ex: FCFA, €, $)', max_length=10),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='debt_alert_threshold',
            field=models.DecimalField(decimal_places=0, default=100000, help_text="Seuil d'alerte pour la dette client (FCFA)", max_digits=12),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='dormant_stock_days',
            field=models.IntegerField(default=90, help_text='Seuil pour considérer un stock comme dormant (sans vente depuis X jours)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='locale',
            field=models.CharField(default='fr-FR', help_text='Code locale pour le formatage (ex: fr-FR, en-US)', max_length=10),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='low_stock_threshold_days',
            field=models.IntegerField(default=15, help_text="Seuil d'alerte stock bas (en jours de couverture)"),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='ticket_paper_width',
            field=models.IntegerField(choices=[(80, '80mm'), (58, '58mm')], default=80, help_text='Largeur du papier pour les tickets (mm)'),
        ),
    ]
