# Generated by Django 5.2.5 on 2026-02-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_pharmacysettings_currency_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(decimal_places=2, help_text='Taux de TVA en pourcentage (ex: 19.25)', max_digits=5, unique=True)),
                ('libelle', models.CharField(blank=True, help_text='Description optionnelle (ex: Taux Normal)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taux de TVA',
                'verbose_name_plural': 'Taux de TVA',
                'ordering': ['-taux'],
            },
        ),
    ]
