# Generated by Django 5.2.5 on 2026-02-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_configurationobjectifs_alter_loyaltysetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('EXPORT', 'Export'), ('OTHER', 'Autre'), ('STOCK_ADJ', 'Ajustement stock'), ('PRICE_CHG', 'Changement prix'), ('CLOTURE', 'Clôture caisse'), ('INV_CANCEL', 'Annulation facture'), ('INV_DEL', 'Suppression facture'), ('INV_VALID', 'Validation facture'), ('INV_CRE', 'Création inventaire'), ('INV_VAL', 'Validation inventaire'), ('ORD_RECV', 'Réception commande'), ('ORD_CNCL', 'Annulation réception'), ('SUDO_VAL', 'Validation Sudo')], max_length=10),
        ),
    ]
