# Generated by Django 5.2.5 on 2026-02-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_pharmacysettings_whatsapp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduit',
            name='treatment_duration_days',
            field=models.IntegerField(blank=True, help_text='Durée du traitement en jours pour ce produit (pour rappels chroniques)', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='default_treatment_days',
            field=models.IntegerField(default=30, help_text='Durée par défaut du traitement en jours (utilisé pour les rappels)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_chronic',
            field=models.BooleanField(default=False, help_text='Indique si ce produit est destiné à un traitement chronique (diabète, hypertension, etc.)'),
        ),
    ]
