# Generated by Django 5.2.5 on 2026-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_stocklot_quantity_free_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='auto_logout_timeout',
            field=models.IntegerField(default=15, help_text="Délai d'inactivité avant déconnexion automatique (en minutes, 0 pour désactiver)"),
        ),
    ]
