# Generated by Django 6.0.3 on 2026-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_pharmacysettings_pharmacist_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnancier',
            name='image_ordonnance',
            field=models.ImageField(blank=True, help_text="Image scannée de l'ordonnance", null=True, upload_to='ordonnances/%Y/%m/'),
        ),
    ]
