# Generated by Django 6.0.3 on 2026-05-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_avoir_is_active_commande_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
