# Generated by Django 6.0.3 on 2026-05-02 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_facture_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.TextField(help_text='Le token JWT complet')),
                ('date_installation', models.DateTimeField(auto_now_add=True)),
                ('derniere_verification', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Licence Système',
                'verbose_name_plural': 'Licences Système',
            },
        ),
    ]
