# Generated by Django 6.0.3 on 2026-05-07 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_add_telegram_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='majoration_pro_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage de majoration des prix pour les clients professionnels (compensation délais longs)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Majoration Pro (%)'),
        ),
    ]
