# Generated by Django 6.0.3 on 2026-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_client_niu_client_registre_commerce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='is_divers',
            field=models.BooleanField(default=False, help_text="Lot provenant d'une commande diverse"),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type',
            field=models.CharField(choices=[('LOC', 'Locale'), ('DIR', 'Directe'), ('DIV', 'Divers')], default='LOC', help_text='Type de commande (Locale ou Directe)', max_length=3),
        ),
    ]
