# Generated by Django 5.2.14 on 2026-06-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_add_hide_cash_totals'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commande',
            name='cmd_fourn_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='facture',
            name='fact_date_status_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='mouvementstock',
            name='mvt_stock_prod_type_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklot',
            name='stocklot_prod_qty_exp_idx',
        ),
    ]
