# Generated by Django 5.2.15 on 2026-06-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_fournisseur_delai_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='critical_stock_days',
            field=models.IntegerField(default=7, help_text='Seuil stock critique (jours)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='good_coverage_max_days',
            field=models.IntegerField(default=90, help_text='Couverture stock max (jours) pour score santé'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='good_coverage_min_days',
            field=models.IntegerField(default=15, help_text='Couverture stock min (jours) pour score santé'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='imminent_rupture_days',
            field=models.IntegerField(default=3, help_text='Seuil rupture imminente (jours)'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='perf_alert_hour',
            field=models.IntegerField(default=14, help_text="Heure à partir de laquelle l'alerte performance se déclenche"),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='perf_drop_threshold',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Seuil de baisse CA pour alerte (0.7 = 30% de baisse)', max_digits=3),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='shortage_alert_threshold',
            field=models.IntegerField(default=10, help_text='Nb de produits en rupture avant alerte'),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='traffic_analysis_days',
            field=models.IntegerField(default=30, help_text="Fenêtre d'analyse du trafic horaire (jours)"),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='delai_livraison_jours',
            field=models.IntegerField(default=7, help_text='Délai moyen entre validation de la commande et réception physique (jours).'),
        ),
        migrations.AlterField(
            model_name='pharmacysettings',
            name='dormant_stock_days',
            field=models.IntegerField(default=90, help_text='Seuil de jours pour stock dormant'),
        ),
        migrations.DeleteModel(
            name='ProduitFournisseurSeuil',
        ),
    ]
