# Generated by Django 5.2.15 on 2026-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_pharmacysettings_critical_stock_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='taux_marge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux de marge appliqué (ex: 1.60)', max_digits=5, null=True),
        ),
    ]
