# Generated by Django 5.2.15 on 2026-07-22 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_fix_quantity_free_remaining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='avoir',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé cet avoir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_avoirs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé ce client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé cette commande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé cette facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_factures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé ce fournisseur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fournisseurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé cet inventaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_inventaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé ce produit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_produits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la suppression', null=True),
        ),
        migrations.AddField(
            model_name='promis',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé ce promis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_promis', to=settings.AUTH_USER_MODEL),
        ),
    ]
