# Generated by Django 5.2.5 on 2026-08-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_p2_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delai_paiement_negocie_jours',
            field=models.IntegerField(blank=True, help_text='Délai de paiement négocié en jours pour cette commande (utilisé uniquement si is_mise_en_place=True, remplace le délai standard du fournisseur).', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='is_mise_en_place',
            field=models.BooleanField(default=False, help_text='Achat de mise en place / condition négociée avec le grossiste (délai de paiement propre à cette commande, différent du délai standard du fournisseur).'),
        ),
    ]
