# Generated by Django 5.2 on 2026-09-01

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_facture_facture_poste_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoirClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=10)),
                ('type_motif', models.CharField(choices=[('ERREUR', 'Erreur'), ('RETOUR', 'Retour'), ('REMISE', 'Remise'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_clients', to='api.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_clients_created', to=settings.AUTH_USER_MODEL)),
                ('facture_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_clients', to='api.facture')),
            ],
            options={
                'verbose_name': 'Avoir client',
                'verbose_name_plural': 'Avoirs clients',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneAvoirClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lot', models.CharField(blank=True, default='', max_length=100)),
                ('avoir_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.avoirclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produit')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stocklot')),
            ],
            options={
                'verbose_name': "Ligne d'avoir client",
                'verbose_name_plural': "Lignes d'avoir client",
            },
        ),
    ]
