// Auto-generated by scripts/generate-version.mjs — do not edit manually
export const BUILD_VERSION = {
    hash: '1716107',
    date: '2026-06-18T00:24:51.559Z',
    number: 1781742291560,
    env: 'development',
};

export const formatVersion = (): string => {
    const d = new Date(BUILD_VERSION.date);
    const dateStr = d.toLocaleDateString('fr-FR', { day: '2-digit', month: '2-digit', year: 'numeric' });
    const timeStr = d.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
    return `v${BUILD_VERSION.hash} — ${dateStr} ${timeStr}`;
};
