// Auto-generated by scripts/generate-version.mjs — do not edit manually
export const BUILD_VERSION = {
    hash: 'e49ec5f1',
    date: '2026-10-08T22:09:44.417Z',
    number: 1791497384417,
    env: 'development',
};

export const formatVersion = (): string => {
    const d = new Date(BUILD_VERSION.date);
    const dateStr = d.toLocaleDateString('fr-FR', { day: '2-digit', month: '2-digit', year: 'numeric' });
    const timeStr = d.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
    return `v${BUILD_VERSION.hash} — ${dateStr} ${timeStr}`;
};
