// Auto-generated by scripts/generate-version.mjs — do not edit manually
export const BUILD_VERSION = {
    hash: '7c5427dd',
    date: '2026-08-17T21:23:03.043Z',
    number: 1787001783044,
    env: 'development',
};

export const formatVersion = (): string => {
    const d = new Date(BUILD_VERSION.date);
    const dateStr = d.toLocaleDateString('fr-FR', { day: '2-digit', month: '2-digit', year: 'numeric' });
    const timeStr = d.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
    return `v${BUILD_VERSION.hash} — ${dateStr} ${timeStr}`;
};
