import { StyleSheet } from 'react-native';
import { theme } from '../config/theme';
import { moderateScale as ms } from '../utils/scale';

// Styles de l'écran de facturation uniquement — les styles des modals
// extraits (ClientModal, AyantDroitSection…) vivent dans leurs fichiers.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.bg },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: ms(16),
    paddingVertical: ms(12),
    backgroundColor: theme.bgElevated,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  headerLeft: { flex: 1, minWidth: 0 },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', minWidth: 0 },
  headerTitle: { fontSize: ms(18), fontWeight: '800', color: theme.text },
  headerUser: { fontSize: ms(12), color: theme.textMuted, flexShrink: 1 },
  headerSubtitle: { flexDirection: 'row', alignItems: 'center', gap: ms(5), marginTop: ms(2), alignSelf: 'flex-start', maxWidth: '100%' },
  headerSubtitleText: { fontSize: ms(12), fontWeight: '500', color: theme.textSecondary, flexShrink: 1 },
  headerRight: { flexDirection: 'row', alignItems: 'center' },
  iconBtn: { padding: ms(7) },
  cancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ms(5),
    backgroundColor: theme.dangerWash,
    borderWidth: 1,
    borderColor: 'rgba(220, 38, 38, 0.25)',
    borderRadius: ms(20),
    paddingHorizontal: ms(12),
    paddingVertical: ms(6),
    marginLeft: ms(4),
    marginRight: ms(2),
  },
  cancelBtnText: { fontSize: ms(13), fontWeight: '600', color: theme.danger },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.bgElevated, borderRadius: ms(12), paddingHorizontal: ms(12), paddingVertical: ms(10), marginHorizontal: ms(12), marginTop: ms(12), marginBottom: ms(10), borderWidth: 1, borderColor: theme.border },
  searchInput: { flex: 1, marginLeft: ms(8), color: theme.text, fontSize: ms(14) },
  scanBtn: { padding: ms(6), marginLeft: ms(4) },
  mainBox: {
    flex: 1,
    marginHorizontal: ms(12),
    borderRadius: ms(16),
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.borderStrong,
    backgroundColor: theme.bgElevated,
    overflow: 'hidden',
  },
  resultsOverlay: {
    position: 'absolute',
    left: ms(12),
    right: ms(12),
    borderRadius: ms(16),
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.borderStrong,
    backgroundColor: theme.bgElevated,
    overflow: 'hidden',
    zIndex: 20,
    elevation: 8,
  },
  mainList: { flexGrow: 1, padding: ms(8) },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: ms(12), paddingVertical: ms(40) },
  emptyStateText: { fontSize: ms(13), color: theme.textMuted },
  clientCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: ms(12),
    marginTop: ms(10),
    backgroundColor: theme.bgElevated,
    borderRadius: ms(12),
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: ms(14),
    paddingVertical: ms(10),
  },
  clientCardLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: ms(10), minWidth: 0 },
  clientCardText: { flex: 1, minWidth: 0 },
  clientLabel: { fontSize: ms(10), fontWeight: '700', color: theme.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  clientName: { fontSize: ms(14), fontWeight: '700', color: theme.text },
  clientEdit: { fontSize: ms(13), fontWeight: '700', color: theme.primary, paddingLeft: ms(10) },
  remiseRow: { flexDirection: 'row', alignItems: 'center', marginHorizontal: ms(12), marginTop: ms(10), gap: ms(10) },
  remiseLabel: { fontSize: ms(12), color: theme.textSecondary, flex: 1 },
  remiseControls: { flexDirection: 'row', alignItems: 'center', gap: ms(6) },
  remiseInput: {
    width: ms(64),
    backgroundColor: theme.bg,
    borderRadius: ms(6),
    paddingHorizontal: ms(8),
    paddingVertical: ms(6),
    color: theme.text,
    fontSize: ms(13),
    borderWidth: 1,
    borderColor: theme.border,
    textAlign: 'right',
  },
  remiseToggle: { flexDirection: 'row', borderRadius: ms(6), overflow: 'hidden', borderWidth: 1, borderColor: theme.borderStrong },
  remiseModeBtn: { paddingHorizontal: ms(10), paddingVertical: ms(6), backgroundColor: theme.bg },
  remiseModeBtnActive: { backgroundColor: theme.primary },
  remiseModeText: { fontSize: ms(12), fontWeight: '700', color: theme.textMuted },
  remiseModeTextActive: { color: '#fff' },
  remiseAmount: { fontSize: ms(12), fontWeight: '700', color: theme.primary, minWidth: ms(60), textAlign: 'right' },
  footerRow: { flexDirection: 'row', alignItems: 'stretch', gap: ms(10), marginHorizontal: ms(12), marginTop: ms(10), marginBottom: ms(4) },
  totalBox: {
    flex: 1,
    backgroundColor: theme.bgMuted,
    borderRadius: ms(12),
    paddingHorizontal: ms(14),
    paddingVertical: ms(10),
    justifyContent: 'center',
  },
  totalLabel: { fontSize: ms(10), fontWeight: '700', color: theme.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  totalValue: { fontSize: ms(20), fontWeight: '800', color: theme.primary },
  sousTotal: { fontSize: ms(11), color: theme.textSecondary, marginTop: ms(2) },
  sudoBadge: { flexDirection: 'row', alignItems: 'center', gap: ms(4), marginTop: ms(4) },
  sudoBadgeText: { fontSize: ms(10), color: theme.primary, fontWeight: '600' },
  pendingBadge: {
    position: 'absolute',
    top: ms(-4),
    right: ms(-4),
    minWidth: ms(16),
    height: ms(16),
    borderRadius: ms(8),
    backgroundColor: theme.warning,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: ms(3),
  },
  pendingBadgeText: { fontSize: ms(9), fontWeight: '800', color: '#fff' },
  sendBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: ms(8), backgroundColor: theme.primary, borderRadius: ms(12), paddingVertical: ms(14) },
  sendBtnDisabled: { backgroundColor: theme.borderStrong },
  sendBtnText: { color: '#fff', fontSize: ms(15), fontWeight: '700' },
  // ── Densité compacte (petite hauteur < 720dp) : resserre les sections
  // fixes pour agrandir la zone liste du panier.
  headerCompact: { paddingVertical: ms(8) },
  searchBarCompact: { marginTop: ms(6), marginBottom: ms(6), paddingVertical: ms(6) },
  clientCardCompact: { marginTop: ms(6), paddingVertical: ms(6) },
  remiseRowCompact: { marginTop: ms(6) },
  footerRowCompact: { marginTop: ms(6), marginBottom: ms(2) },
  totalBoxCompact: { paddingVertical: ms(6) },
  sendBtnCompact: { paddingVertical: ms(8) },
});
