# Dockerfile Production - Frontend React
FROM node:20-alpine AS builder

WORKDIR /app

# Copier package.json
COPY package*.json ./
RUN npm config set fetch-retries 5 && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm ci

# Copier le code source
COPY . .

# Build de production
RUN npm run build

# Serveur Nginx pour servir les fichiers statiques
FROM nginx:alpine

# Copier les fichiers buildés
COPY --from=builder /app/dist /usr/share/nginx/html

# Config Nginx pour SPA (Single Page Application)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
